### PR TITLE
libfetchers/github: allow `url` attribute

### PR DESCRIPTION
**Pull request by Ma27**
Since 108debef6f703aa3ca1f6d6c45428880624ec6f8 we allow a
`url`-attribute for the `github`-fetcher to fetch tarballs from
self-hosted `gitlab`/`github` instances.

However it's not used when defining e.g. a flake-input

    foobar = {
        type = "github";
        url = "gitlab.myserver";
        /* ... */
    }

and breaks with an evaluation-error:

    error: --- Error --------------------------------------nix
    unsupported input attribute 'url'
    (use '--show-trace' to show detailed location information)

This patch allows flake-inputs to be fetched from self-hosted instances
as well.

### CODE REVIEW

**Comment by edolstra** [comment]
`url` seems wrong since `gitlab.server` is not a valid URL. Maybe it should be `server` or `host` or something like that?

**Comment by Ma27** [comment]
@edolstra you're obviously right and I'm fine with a rename. I'd just like to point out that I used the name-decision that was originally taken in 108debef6f703aa3ca1f6d6c45428880624ec6f8.

I think `host` is better. If you agree with this I'll update my PR accordingly.

**Comment by edolstra** [comment]
Ah, sorry about that. Yes please do!

**Comment by Ma27** [comment]
@edolstra fixed. Please note that this needs to be fixed as well now in https://github.com/edolstra/flake-compat/blob/master/default.nix :)

**Pull request merged**
