### PR TITLE
Add mising #include for strerror

### PR DESCRIPTION
**Pull request by Ericson2314**
\[I think we're overdue for some CI that always ensures the merge builds too.\]

### CODE REVIEW

**Comment by Ericson2314** [comment]
@gilligan looks like I unbroke the build, but the unit tests need fixing.

**Comment by gilligan** [comment]
@Ericson2314 oh that's too bad. i'll have a look at it and also ping @bburdette

**Comment by gilligan** [comment]
> [I think we're overdue for some CI that always ensures the merge builds too.]

I think this can either be changed in the GitHub actions config _or_ PRs could be required to be up to date with master for merge.

@domenkozar changing the github actions config to also run tests on the PR merged into master shouldn't be too hard I guess?

**Comment by gilligan** [comment]
Had a quick look at it. The tests were broken by https://github.com/NixOS/nix/commit/8b099812eab7ccad9ebc6906450b637044de9369 which was pushed directly to master so no change to CI is going to help in this case.

**Comment by gilligan** [comment]
@Ericson2314 https://github.com/gilligan/nix/commit/4dae6ebe500e7d41bba73d525d3a92243c03c22e this fixes the unit tests

**Pull request merged**
