### PR TITLE
Make profile element names stable

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

The profile manifest is now an object keyed on the name returned by `getNameFromURL()` at installation time, instead of an array. This ensures that the names of profile elements don't change when other  elements are added/removed.

It also removes profile element indices entirely.

Followup to #8678.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by bobvanderlinden** [comment]
I still need give this a try, but from what I've seen so far it looks good.

This closes https://github.com/NixOS/nix/issues/7967 by introducing stable identifiers.
This closes https://github.com/NixOS/nix/issues/9171 by removing indexes.

Removing indexes is a backwards incompatible change for CLI.

**Review by bobvanderlinden — COMMENTED** [review]
I tried it. Upgrades the `manifest.json` upon making changes quite nicely.

One issue I ran into was the URL that was used for `getNameFromURL`. Instead of `github:nixos/nixpkgs/nixpkgs-unstable#hello` it now passes `github:nixos/nixpkgs/nixpkgs-unstable#legacyPackages.x86_64-linux.hello`. Unfortunately `getNameFromURL` doesn't support `legacyPackages` and there are no tests for this as well. The resulting entry is named `legacyPackages.x86_64-linux.hello`. Unrelated to this PR, but it did expose the problem for me. I've created https://github.com/edolstra/nix/pull/9 to support `legacyPackages`.

Apart from that, I didn't run into trouble with my profile/manifest. I do wonder whether the migration from manifest version 2 to 3 should have a test?

Btw, I'm on vacation for the next week, so expect my feedback after that.

**Comment by roberth** [comment]
This should have a release note indicating that it changes the profile format, and previous versions will not be able to parse it anymore.
Ideally the note includes the error message from the old nix and a manual solution.

**Comment by edolstra** [comment]
Updated the release notes and added a migration test.

**Pull request merged**
