### PR TITLE
Input::fetchToStore(): Don't try to substitute

### LINKED ISSUE #10601: Incorrect lastModified value
**Describe the bug**

I observed this random failure in the flake regression test suite:

```
diff --git a/tests/acaloiaro/di-tui/0.1.85+rev-12ae555a00205926da7cb5216d7f070e57b7508e/contents.json b/tests/acaloiaro/di-tui/0.1.85+rev-12ae555a00205926da7cb5216d7f070e57b7508e/contents-new.json
index 478c4e8..81b18d3 100644
--- a/tests/acaloiaro/di-tui/0.1.85+rev-12ae555a00205926da7cb5216d7f070e57b7508e/contents.json
+++ b/tests/acaloiaro/di-tui/0.1.85+rev-12ae555a00205926da7cb5216d7f070e57b7508e/contents-new.json
@@ -1 +1 @@
 {"docs":{"devShells":"The `devShells` flake output contains derivations that provide a build environment for `nix develop`.\n","packages":"The `packages` flake output contains packages that can be added to a shell using `nix shell`.\n"},"inventory":{"devShells":{"children":{"aarch64-darwin":{"children":{"default":{"derivation":"/nix/store/1br0kf1jymr6hfymmsnql1nw09qiw9cf-nix-shell.drv","forSystems":["aarch64-darwin"],"outputs":{"out":"/nix/store/p5dgb83nm1q1vrsds85gk7l4vvfa93g0-nix-shell"},"shortDescription":"","what":"development environment"}}},"aarch64-linux":{"children":{"default":{"derivation":"/nix/store/lrhq97gbihryj828fyf77aji4g44iyj9-nix-shell.drv","forSystems":["aarch64-linux"],"outputs":{"out":"/nix/store/xk0yxvlzkar69ipnksl215zsl94a1598-nix-shell"},"shortDescription":"","what":"development environment"}}},"x86_64-darwin":{"children":{"default":{"derivation":"/nix/store/1yplmrjp3976qg1aw5bc0km3sfa7qf56-nix-shell.drv","forSystems":["x86_64-darwin"],"outputs":{"out":"/nix/store/y8p6an9pwqbdvvln32gazpk8gj5bx37w-nix-shell"},"shortDescription":"","what":"development environment"}}},"x86_64-linux":{"children":{"default":{"derivation":"/nix/store/7wbzj4rf0hbjx9i3maxn6x8161afmyj5-nix-shell.drv","forSystems":["x86_64-linux"],"outputs":{"out":"/nix/store/n8k7k154h8pcr8zygw773ddy1m7506bp-nix-shell"},"shortDescription":"","what":"development environment"}}}}},"packages":{"children":{"aarch64-darwin":{"children":{"default":{"derivation":"
-/nix/store/5nxrgmw3s2rq3r3rpkrg5g8sga6sa5hh-di-tui-19700101.drv
+/nix/store/1pdn1icf5xv9afmdarx5rvaj6kbfd550-di-tui-20230915.drv
 ","forSystems":["aarch64-darwin"],"outputs":{"out":"
-/nix/store/z6gx1fpm6ckrqjc8ahr50hr8i5balgh4-di-tui-19700101
+/nix/store/gxzqxpwnwn97ijwfp9vi7yhzh3yilylr-di-tui-20230915
 "},"shortDescription":"","what":"package"}}},"aarch64-linux":{"children":{"default":{"derivation":"
-/nix/store/znqkcfw9cliq5vymfv831bdyw2jdsrps-di-tui-19700101.drv
+/nix/store/w0v14fhvb1xwwvvfr0qyhvsbggxshn0i-di-tui-20230915.drv
 ","forSystems":["aarch64-linux"],"outputs":{"out":"
-/nix/store/qdx3m7cqah8r6l28b7i9lj33sh8w2nnd-di-tui-19700101
+/nix/store/6yjc58p6nw3ljsj06fdjhflnz4pr4b71-di-tui-20230915
 "},"shortDescription":"","what":"package"}}},"x86_64-darwin":{"children":{"default":{"derivation":"
-/nix/store/hgg0i7pn588d4cbhvj19j2b3mz2lm6ad-di-tui-19700101.drv
+/nix/store/64g3dmkbxl4als9xwvrb8ym4qbsfdsln-di-tui-20230915.drv
 ","forSystems":["x86_64-darwin"],"outputs":{"out":"
-/nix/store/1qcdm8a8xgimi06d8swpqp2cffa1wn70-di-tui-19700101
+/nix/store/b0aziipy3c6j0dyiw8a7my4xa5wl6h9v-di-tui-20230915
 "},"shortDescription":"","what":"package"}}},"x86_64-linux":{"children":{"default":{"derivation":"
-/nix/store/izp8wbyfpd4h05fk9k6agskahlk9bixg-di-tui-19700101.drv
+/nix/store/q9r0xx4lwklaws7m1j6a9whmzypf558h-di-tui-20230915.drv
 ","forSystems":["x86_64-linux"],"outputs":{"out":"
-/nix/store/sg8pf2mi34m372ydfii7qjmwbqanxnrz-di-tui-19700101
+/nix/store/paqqrhbjdwn0wgk7xs5pcxd7sazrh3r2-di-tui-20230915
 "},"shortDescription":"","what":"package"}}}}}},"version":1}
~
❌ tests/acaloiaro/di-tui/0.1.85+rev-12ae555a00205926da7cb5216d7f070e57b7508e
```

The diff suggests that the `lastModified` value of the flake input isn't always passed correctly.

**Steps To Reproduce**

**Expected behavior**

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

Having a `narHash` doesn't mean that we have the other attributes returned by the fetcher (such as `lastModified` or `rev`). For instance,

```
$ nix flake metadata github:NixOS/patchelf/7c2f768bf9601268a4e71c2ebe91e2011918a70f
Last modified: 2024-01-15 10:51:22
```

but

```
$ nix flake metadata github:NixOS/patchelf/7c2f768bf9601268a4e71c2ebe91e2011918a70f?narHash=sha256-PPXqKY2hJng4DBVE0I4xshv/vGLUskL7jl53roB8UdU%3D
(does not print a "Last modified")
```

The latter only happens if the store path already exists or is substitutable, which made this impure behaviour unpredictable.

Fixes #10601. Note: lazy-trees already had this fix, because it no longer requires all locked nodes to have a `narHash`.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by roberth** [comment]
(thoughts)

I'd still be concerned about similar bugs, because the code isn't structured in a way that would make such a bug somewhat harder to write.
We have the requirement that
- Given any input to fetchTree, it must only succeed with one possible return value - ie referential transparency in the happy path.

This crucial property is hard to test, so we should try to structure the code in a way that makes this property easy to determine (I won't say prove; too absolute to be realistic).
A mutable map makes that hard.

In my previous attempt to improve this, I focused on giving types to the input side, which wasn't all that fruitful, given the amount of change and effort required. Maybe it'd be more effective to put the *output* into a struct before returning it as attributes?

**Comment by roberth** [comment]
Is it necessary not to substitute? What if the the missing fields can be obtained from the lock file instead?
I suppose we'd have to tell `fetchTree` not to return any new attributes except `outPath`. IIRC we don't have such a flag yet?

**Comment by edolstra** [comment]
Substitution could still be done for locked flake inputs, because there we *know* that we have all the attributes.

We do have the `isLocked()` method, but we can't use it for the tarball fetcher, since the HTTP headers can return additional lock attributes like `lastModified` and `rev`.

**Comment by roberth** [comment]
> but we can't use it for the tarball fetcher, since the HTTP headers can return additional lock attributes like `lastModified` and `rev`.

Aren't those saved to the lock then?

**Comment by edolstra** [comment]
They are, this problem only occurs on the CLI if you pass `narHash` but not the other attributes.

**Comment by roberth** [comment]
Fair enough. Optimizations can be done later, unless we move towards a non-optimizable design. I don't think that's the case here.

**Comment by Ericson2314** [comment]
I would like to keep substituting, because I would like to be able to substitute from things like Software Heritage by being able to look up content addresses too and not just store paths.

**Comment by roberth** [comment]
Right, this isn't actually just an optimization.
Another use case is where a (private) cache is used for [`requireFile`](https://nixos.org/manual/nixpkgs/stable/index.html#requirefile)-like functionality.

If we move the metadata into a separate attrset, we can both fix the problem and keep supporting these use cases.
This can be done with a `derivation`/`strictDerivation`-like arrangement, where `fetchTree` is a builtin expression that calls the  primops lazily.

**Comment by edolstra** [comment]
Since this is an actual correctness bug (the evaluation result can change depending on whether the flake store exists in a substituter/local store), which is more important than an optimization, let's merge this.

I did have to disable a test that uses relative path flakes because they're completely broken, but this was masked by the `fetchToStore()` behaviour (see 12fd65d1799f6b1fe0c7e07d5a8022afc6b6dc40). This will be fixed in #10089.

**Comment by pwaller** [comment]
> We can figure out how to bring back substitution in the future, if anybody cares.

Have I understood correctly that this means flake inputs will no longer substitute from the cache? If so...

I care! I am tracking things in a substituter which cease to exist at their original urls and require the cache, and so users of my flakes will not be able to build them anymore with this change.

It also sounded to me from the above thread that both @Ericson2314 and @roberth care too:

> I would like to keep substituting, because I would like to be able to substitute from things like Software Heritage by being able to look up content addresses too and not just store paths.

> Right, this isn't actually just an optimization. Another use case is where a (private) cache is used for [requireFile](https://nixos.org/manual/nixpkgs/stable/index.html#requirefile)-like functionality.

**Comment by minijackson** [comment]
I also have a similar usecase, where I use a cache server as an insurance that I can rebuild potentially really old projects. I would like very much that this solution can work transparently for both derivations and flake inputs.

**Comment by a-h** [comment]
I think I also need flake inputs to be able to continue to collect source code from a binary cache.

My understanding is that during flake evaluation, Flake inputs are collected and evaluated, in order to work out the hashes to download binaries from the cache.

Those flake inputs are often libraries, and are coming from github etc., e.g. `github:hercules-ci/gitignore.nix` or `github:nix-community/gomod2nix` so they're needed to evaluate the flake outputs.

In an offline environment (e.g. airgapped, or on a train running through the countryside), flake inputs can't simply be re-collected from the public Internet.

Today, in my offline environments, I have a binary cache that I populate with an export of everything required to build some software products. I'm then able to change the source code and rebuild locally using Nix, without connecting to the Internet.

If I understand this change, and the behaviour of Nix flake evaluation, it _sounds_ like this might break that behaviour?

**Comment by roberth** [comment]
Not super happy about this merge, and apparently I'm not the only one.
Substitution _is_ useful, and this bugfix is a regression for us.

I think we could fix the fix by adding back substitution as a fallback only (considering the performance argument mentioned elsewhere). The extra attributes would either have to be read from the lock file (and trusted, which is ok), or they should result in a lazy error that only triggers on those attributes. We already support multiple return types for attributes; may as well add a variant for an evaluation error (translated to `mkApp(throw, msg)`).

> Note: lazy-trees already had this fix, because it no longer requires all locked nodes to have a `narHash`.

We don't *need* to remove `narHash` in order to copy sources to the store lazily. We *can* remove it as a side effect of trusting libfetchers to produce the right thing.
Removing `narHash` saves us from having to compute it during locking, but I don't think this is significant, except in the case of building a dirty Git workdir, in which case we could just choose not to compute it.
The `narHash` computation could be a step before writing out the lock file, and if we don't expose this hash to the language, its omission from dirty Git inputs is not observable to the evaluation of this temporary source.

@a-h

> My understanding is that during flake evaluation, Flake inputs are collected and evaluated, in order to work out the hashes to download binaries from the cache.

This is how it happens during locking. Once locked, `inputs` are loaded on demand only using `builtins.fetchTree` (called internally, lazily).

**Comment by pwaller** [comment]
> This is how it happens during locking. Once locked, `inputs` are loaded on demand only using `builtins.fetchTree` (called internally, lazily).

(Digression) Except if you refer to the outPath of the flake input, in which case https://github.com/NixOS/nix/issues/9570 happens; which means a flake input doesn't quite behave the same as a src for a derivation with respect to cache hits. AFAIU, The current behaviour source gets fetched during the computation of a derivation using the outPath, either way, when ideally it would only be fetched if you actually needed to use files within. [unless this has been fixed by lazy trees or something? I'm unsure if I am uptodate on this]

**Comment by roberth** [comment]
> Except if you refer to the outPath of the flake input,

Any attribute, or probably even `isAttrs inputs.something`, especially when not `flake = false;` is sufficient to force the `fetchTree` call.
My point was that you don't need to fetch sources that aren't referenced in your evaluation (e.g. something for `packages.b` when you only ask for `.#a` and there's no dependency on `b`).

Switching to fixed output derivations (as also suggested in #9570 as referenced) may solve the problem for you, but at the cost of needing more tooling, and it only works for `inputs` where you can put `flake = false;`. We wouldn't want you to do "import from derivation", which would combine the sequentialization (like builtin fetchers) with the performance overhead of fixed-output fetchers, all during instantiation. While probably slower, it is a viable workaround that allows for substitution though.

**Comment by roberth** [comment]
But yeah, back to the topic, I think we need to

- Add a fallback on substitution
- Make sure the attrs in question are in the lock node (ie `fetchTree` argument)
  - Return a lazy error when they're not
- Later: handle the optional need for narHash gracefully in the context of virtual, "lazy" sources

**Comment by edolstra** [comment]
See #11701 which brings back the ability to substitute inputs in a safer way.

**Pull request merged**
