### PR TITLE
Always keep the CA derivations around

### PR DESCRIPTION
**Pull request by regnat**
Workaround for https://github.com/NixOS/nix/issues/4138

### CODE REVIEW

**Comment by edolstra** [comment]
Does this mean that CA derivations are never garbage-collected?

**Comment by regnat** [comment]
They aren't until their output-path is (like if `keep-derivations` is set to `true` in the config)

**Comment by Ericson2314** [comment]
In fact, perhaps they should be kept around even if their output isn't.

Suppose we have:

> ( resolved-gcc.drv , "out" ) -> `foo`
> ( resolved-bash.drv [ `foo` / "gcc" ] , "out" ) -> `bar`

If we get rid of the row for `foo`, then if someone tries to rebuild (unresolved) bash.drv they'll end up rebuilding GCC!

We're going to need a pretty big migration I'm afraid to have the `bar` row preserve the `foo` row without also preserving the `foo` path itself.

**Review by Ericson2314 — APPROVED** [review]
All that said, this PR makes the situation wholly better, and it is an easy enough stop-gap to back out of whenever we do do the sqlite overhaul.

**Comment by regnat** [comment]
> In fact, perhaps they should be kept around even if their output isn't.
> 
> Suppose we have:
> 
> > ( resolved-gcc.drv , "out" ) -> `foo`
> > ( resolved-bash.drv [ `foo` / "gcc" ] , "out" ) -> `bar`
> 
> If we get rid of the row for `foo`, then if someone tries to rebuild (unresolved) bash.drv they'll end up rebuilding GCC!
> 
> We're going to need a pretty big migration I'm afraid to have the `bar` row preserve the `foo` row without also preserving the `foo` path itself.

I'm not 100% sure, but I think that the `DerivationOutputs` entries stay there as long as the corresponding derivation is there (even if their output is gc-ed), so in that case the first mapping would stay alive because `resolved-gcc.drv` would (as it's a dependency of `resolve-bash.drv`)

**Comment by Ericson2314** [comment]
Ah, but `resolved-gcc.drv` is *not* a dependency of `resolve-bash.drv`, because resolved floating CA derivations always have empty `inputDrvs`. That's the difficulty.

**Comment by Ericson2314** [comment]
Ah CI failed because of that annoying spurious failure. Do we have an issue for it?

**Comment by regnat** [comment]
> Ah, but `resolved-gcc.drv` is _not_ a dependency of `resolve-bash.drv`, because resolved floating CA derivations always have empty `inputDrvs`. That's the difficulty.

Oh yes because we only have this mapping for resolved drvs :thinking: 
I think we need to dig all that a little to properly fix this (but the workaround is worth keeping in the meantime)

**Comment by edolstra** [comment]
> In fact, perhaps they should be kept around even if their output isn't.

But then derivations will accumulate forever... Or they could be treated like a cache and have some expiration policy.

**Pull request closed without merging**
