### PR TITLE
Make the “dumping large path” warning include information on what path is being large

### PR DESCRIPTION
**Pull request by Ekleog**
Disclaimer: this is my first time seriously modifying nix's source code, so I'm far from sure I did everything right. However, I do think that the added debug information is an incremental improvement, and can then be refined as we go, eg. if it turns out some of the debug labels are not precise enough.

Example output with the change:
```
[nix-shell:~/prog/nix]$ outputs/out/bin/nix-instantiate -E '"${./.}"'
warning: dumping very large path (> 256 MiB); this may run out of memory
  while dumping from source 'path:/home/ekleog/prog/nix'
```

What do you think? :)

### CODE REVIEW

**Comment by cole-h** [comment]
See also https://github.com/NixOS/nix/pull/4608.

**Comment by Ekleog** [comment]
Thank you! I'm going to comment on this other PR, both ways look reasonable to me. About the failed test, I _think_ it's due to a timeout that led to the test failing and thus a spurious failure, but not 100% sure about that

**Comment by roberth** [comment]
The occurrence of this message should have been greatly reduced by #4030. In which situation does the message still crop up? It'd be good to make that stream too.

That said, this PR does have merit of its own when it comes to `StringSink`. The warning should probably be removed from `FdSink` though, because that sink does not have a memory problem.
#4034 does describe another use case for logic _like_ this, except it's a linter-like warning instead of "we're about to crash". That can probably be implemented instead as a pass-through sink or source that takes the original path as a constructor argument.

**Comment by Ekleog** [comment]
Seeing how this is merge-conflicting, I'm going to close this as rebasing would probably be just as hard as reimplementing.

**Pull request closed without merging**
