### PR TITLE
Not working, but an attempt at allowing null bytes in strings

### PR DESCRIPTION
**Pull request by Infinisil**
In the hopes of potentially fixing #1307. Just very naively replaces the `char *` with `std::string *`. This most likely is a problem for garbage collection, but I'm not really sure how and why. The errors I currently get seem to hint at that.

Compilation often ends with
```
[nix-shell:~/src/nix]$ make install -j8
  CXX    src/nix/repl.o
  LD     /home/infinisil/src/nix/bin/nix
  GEN    doc/manual/nix.json
  GEN    doc/manual/conf-file.json
  GEN    doc/manual/builtins.json
  GEN    doc/manual/src/command-ref/conf-file.md
  GEN    doc/manual/src/expressions/builtins.md
  GEN    doc/manual/src/command-ref/new-cli
error: out of memory
error: out of memory
make: *** [doc/manual/local.mk:53: doc/manual/src/command-ref/conf-file.md] Error 1
make: *** Waiting for unfinished jobs....
make: *** [doc/manual/local.mk:66: doc/manual/src/expressions/builtins.md] Error 1
/nix/store/xmxgxig6zxrixicc7905ssgb4yc3lysa-bash-interactive-4.4-p23/bin/bash: line 1: 1749184 Segmentation fault      (core dumped) env -i HOME=/dummy NIX_CONF_DIR=/dummy NIX_SSL_CERT_FILE=/dummy/no-ca-bundle.crt NIX_STATE_DIR=/dummy /home/infinisil/src/nix/bin/nix eval --experimental-features nix-command -I nix/corepkgs=corepkgs --store dummy:// --impure --raw --write-to doc/manual/src/command-ref/new-cli --expr 'import doc/manual/generate-manpage.nix (builtins.fromJSON (builtins.readFile doc/manual/nix.json))'
make: *** [doc/manual/local.mk:49: doc/manual/src/command-ref/new-cli] Error 139
```

Segfault with gdb:
```
[nix-shell:~/src/nix]$ gdb --args bin/nix-instantiate --eval -E 'builtins.readFile doc/manual/nix.json'GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bin/nix-instantiate...
(gdb) run
Starting program: /home/infinisil/src/nix/bin/nix-instantiate --eval -E builtins.readFile\ doc/manual/nix.json
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libthread_db.so.1".
[New Thread 0x7ffff5d54640 (LWP 1792955)]
[New Thread 0x7ffff53d3640 (LWP 1792956)]
[New Thread 0x7ffff4bd2640 (LWP 1792957)]
[New Thread 0x7ffff43d1640 (LWP 1792958)]
[New Thread 0x7ffff3bd0640 (LWP 1792959)]
[New Thread 0x7ffff33cf640 (LWP 1792960)]
[New Thread 0x7ffff2bce640 (LWP 1792961)]
[New Thread 0x7ffff23cd640 (LWP 1792962)]

Thread 1 "nix-instantiate" received signal SIGSEGV, Segmentation fault.
nix::printValue (str=..., active=std::set with 1 element = {...}, v=...) at src/libexpr/eval.cc:90
90	           if (i == '\"' || i == '\\') str << "\\" << i;
(gdb) print i
$1 = (const char &) <error reading variable>
```

Suspecting that `i` points to a value that has been deallocated since, but I don't have time to try to figure that out. Anybody can feel free to use this PR as a starting point.

### CODE REVIEW

**Comment by kvtb** [comment]
If null-bytes are to be supported, should invalid UTF-8 (like "\xFF\xFF") be supported too?
For me it looks like there is a space for `binary`  or `bytestring` as a possible new built-in type for blobs.

**Comment by Kha** [comment]
Wouldn't replacing `char *` with `std::string_view` make more sense?

**Comment by Infinisil** [comment]
@Kha It needs to be a pointer to not increase the `sizeof(Value)`, and it can't be a (non-nullable) reference because the field might not be set since it's a union

**Comment by Infinisil** [comment]
Oh though the size wouldn't increase with an `std::string` reference I think, though it still needs to be nullable

**Comment by Infinisil** [comment]
Gonna close this for now, don't have any intention of continuing to work on this. But anybody else is free to use my changes here as a potential start

**Pull request closed without merging**
