### PR TITLE
Fix `nix eval nixpkgs#bash` segfault

### PR DESCRIPTION
**Pull request by 9999years**
`nix eval` forces values and prints derivations as attribute sets, so commands that print derivations (e.g. `nix eval nixpkgs#bash`) will infinitely loop and segfault.

Printing derivations as `.drv` paths makes `nix eval` complete as expected. Further work is needed, but this is better than a segfault.

### CODE REVIEW

**Review by tomberek — CHANGES_REQUESTED** [review]
Looks good. Please add a release note to notify people.

During team discussion we also considered additional behavior, but this seems to be a net-positive regardless of future changes.

**Comment by 9999years** [comment]
Added a release note, PTAL.

**Review by tomberek — APPROVED** [review]

**Comment by kjeremy** [comment]
Can we get a backport? I think I'm hitting this.

**Comment by thufschmitt** [comment]
The bot just opened backport PRs for 2.20 and 2.21 (the other ones didn't apply cleanly), but I actually don't think we can as this is a breaking change (not the fact that it doesn't segfault any more, but `nix eval --expr '{ type = "derivation"; drvPath = "blah"; }'` now behaves differently)

**Comment by 9999years** [comment]
@thufschmitt Not a breaking change, `nix-command` is an experimental feature with no stability guarantees.

**Comment by thufschmitt** [comment]
> @thufschmitt Not a breaking change, `nix-command` is an experimental feature with no stability guarantees.

I know (that's why it has been changed here), but it's still a trade-off (this potentially breaks people, and doing that on a patch release is uncool, even for experimental features).

Not married to it though, if you think it's worth backporting, feel free to reopen the PRs (I think you have the right, if not ping me).

**Comment by 9999years** [comment]
@kjeremy Yes, it's backported to 2.18, you can use it here: https://lix.systems/

https://gerrit.lix.systems/c/lix/+/446

**Pull request merged**
