### PR TITLE
_not_ round-trip tests for `fetchers::PublicKey` default `type`

### PR DESCRIPTION
**Pull request by haenoe**
# Motivation

Again, continuation of #10602 ^^'

@Ericson2314 Hopefully I understood your request correctly :D

That is also why I have one question. Isn't the second request

>[...] test that when read it is the same thing as if it was there (with the default), **and when written it gets that field.**

already handled by [this](https://github.com/haenoe/nix/blob/6bdb9ec6f9c22c0a910290158569b9ef531f677e/tests/unit/libfetchers/public-key.cc#L42) test?

And is it okay to _explicitly_ repeat the default `type` [here](https://github.com/haenoe/nix/blob/6bdb9ec6f9c22c0a910290158569b9ef531f677e/tests/unit/libfetchers/public-key.cc#L48C51-L48C54) or should I just leave it out of the constructor?

# Context

>@haenoe this is completely optional, but if you like you can add an intentionally *not* round-trip test where you skip the `type` field in the JSON, and test that when read it is the same thing as if it was there (with the default), and when written it gets that field.

_Originally posted by @Ericson2314 in https://github.com/NixOS/nix/issues/10602#issuecomment-2078171044_

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by Ericson2314** [comment]
> already handled by [this](https://github.com/haenoe/nix/blob/6bdb9ec6f9c22c0a910290158569b9ef531f677e/tests/unit/libfetchers/public-key.cc#L42) test?

Ah but that is for the C++ default, not the JSON default :)

**Comment by Ericson2314** [comment]
Rebased to not be stuck by broken `master`.

**Comment by Ericson2314** [comment]
Now there is a non-spurious failure?

**Comment by haenoe** [comment]
Yeah seems like it :/
I will try to take a look at it tomorrow ^^'

**Pull request merged**
