### PR TITLE
Add ignore-git option

### PR DESCRIPTION
**Pull request by balsoft**
Allows to ignore .git directories when interpreting local flake references,
thus interpreting all local flakes as path:// and not git+file://. This
has multiple effects, notably:

- (pro) Allows to use flakes without adding flake.nix to the index (useful for
  repositories where flake.nix cannot be commited for one reason or another,
  see https://discourse.nixos.org/t/my-painpoints-with-flakes/9750 for example);
- (con) Disables the gitignore behavior;
- (con) Puts the entire .git into nix store.

### CODE REVIEW

**Comment by blaggacao** [comment]
For completeness sake, another con is &mdash; I guess: doesn't provide `self.rev`

**Comment by balsoft** [comment]
Note: this may not be needed. I completely forgot about the already-existing behavior of `path:`. E.g. `nix build --ignore-git .` is equivalent to `nix build path:.`

**Comment by xaverdh** [comment]
Well it would be nice to have a flag which prevents adding the lock file to the index though?

**Comment by L-as** [comment]
I don't think this is needed to be quite honest.

**Pull request closed without merging**
