### PR TITLE
Upgrade docs: improve the upgrade command

### PR DESCRIPTION
**Pull request by grahamc**
and make it more copy-pastable.

Includes the changes from #2429

### CODE REVIEW

**Comment by grahamc** [comment]
image

**Comment by grahamc** [comment]
I've asked @LnL7 to review this before merging.

**Comment by LnL7** [comment]
Another thing that might be worth adding are some instructions on how to recover a daemon installation after performing a system upgrade. Apple will reset `/etc/bashrc` and friends as well as clear out `/var/root`, removing the .nix-channels entries for root.

**Comment by matthewbauer** [comment]
Great work!

One note:

After https://github.com/NixOS/nix/commit/74f6d8767de13980b0e83a249633ee4a7e6fc547, it should no longer be necessary to add ```-i``` to sudo for each command. However, since this concerns upgrading it's probably safest to leave it in.

**Pull request merged**
