### PR TITLE
Use libarchive for all decompression (except brotli)

### LINKED ISSUE #2255: Support zstd compression for binary caches
https://code.facebook.com/posts/1658392934479273/smaller-and-faster-data-compression-with-zstandard/

Requested by @nh2 in https://github.com/cachix/cachix/issues/55#issuecomment-399757675

### PR DESCRIPTION
**Pull request by yorickvP**
Libarchive, introduced in an earlier PR, can be used for arbitrary compression and decompression, as well as tar files. This handles support for (de)compression with gzip, bzip2, lzip, xz, lzma, zstd or compress. The main new feature here is zstd support.

The thing conspicuously missing here is brotli. This is because brotli does not have a magic header, so it cannot be automatically detected. We will still have to work around this, all other tests pass.

Fixes #2255.

##### Todo
- [x] brotli handling
- [ ] more parallelism where possible
- [x] bzip2-compressed logs
- [ ] drop dependency on bzip2, xz, zlib
- [ ] [add option for compression levels](https://github.com/nixos/nix/pull/2276)

##### cc:
@tomberek @puckipedia

### CODE REVIEW

**Comment by tomberek** [comment]
Exciting change. How are you building and testing zstd? I presume this will come with some release-common.nix and configure.ac changes.

**Comment by yorickvP** [comment]
`libarchive` already links statically with zstd (and falls back to zstd command line binary when it's not). No further changes are required. It might be good to test zstd specifically, if we plan on using it in global binary caches.

**Comment by tomberek** [comment]
Yes, while testing zstd it seems to fallback and then not find the command line binary (I specifically uninstalled it to check this).

**Comment by domenkozar** [comment]
https://guix.gnu.org/blog/2019/substitutes-are-now-available-as-lzip/

**Comment by domenkozar** [comment]
@yorickvP what's missing here?

**Comment by domenkozar** [comment]
Talking to @yorickvP this needs brolti fallback to the old behavior since there's no magic byte header.

**Comment by yorickvP** [comment]
Okay, this code now passes all tests.

**Comment by domenkozar** [comment]
Once https://github.com/serokell/nix/pull/4 is merged, this PR will have tests and can be reviewed.

**Comment by domenkozar** [comment]
@edolstra I'd really like this merged, could you review this PR? My downstream PR only fixes a tiny bug.

**Comment by edolstra** [comment]
Thanks, merged!

**Comment by domenkozar** [comment]
Wohooo 🥳

**Comment by dtzWill** [comment]
I'm looking at my PR for adding compression level option-- which is mentioned as possibly on the TODO, thank you -- and was wondering if you happen to have looked into that at all?  I've yet to read through these changes or look into how libarchive works yet so not sure if there were issues there or just wasn't a priority / mess plumbing things or whatever :).

Thanks regardless, have a good one!

**Pull request merged**
