### PR TITLE
Implement SSHStore on top of nix-daemon served over ssh

### LINKED ISSUE #986: SSHStore implementation
Flagging this here because I'm working on it as part of the perl removal work, this should replace download-via-ssh, improve or replace build-remote (possibly leading to build hooks just being store instances?), and be a major part of nix-copy-closure (which will then be usable with s3/http binary caches as well as ssh).

### PR DESCRIPTION
**Pull request by shlevy**
Fixes #986

### CODE REVIEW

**Comment by shlevy** [comment]
@edolstra ping, will merge this at the end of the week absent any issues

**Comment by edolstra** [comment]
Please don't, I'll want to review this first.

**Comment by shlevy** [comment]
OK, I'll count that as an issue :smile:

**Comment by shlevy** [comment]
@edolstra Can you give me a time frame for reviewing this? It's the most controversial change in the perl->c++ work and if I'm going to have to redo build-remote without it I'd rather know sooner than later...

**Comment by shlevy** [comment]
(erm, and nix-copy-closure)

**Comment by shlevy** [comment]
@edolstra Is there anything I can do to help get this reviewed? If I'm going to have to redo build-remote and nix-copy-closure without this it will be much easier now than in a few weeks (though still a pain now of course).

**Comment by edolstra** [comment]
To reduce the churn in this PR and make it easier to review, could you *not* rename RemoteStore to DaemonStore? We can always rename things sensibly later...

Also, wrt `build-remote`, the use of a separate protocol allows the use of a forced SSH command to root where the client can only do a few operations (copying paths and starting builds). How would that work here?

**Comment by shlevy** [comment]
OK, will do with the rename.

For build-remote, we could add a limited mode to the daemon? What do you think?

**Comment by edolstra** [comment]
Yeah that would be good. It would probably suffice to add a flag that causes the daemon to use "nobody" as the connecting user name rather than using the uid of the calling user.

**Comment by shlevy** [comment]
Replaced by #1053

**Pull request closed without merging**
