### PR TITLE
2.0.1 release

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by shlevy** [comment]
Would be nice to have a release with the recent fixes.

**Comment by puffnfresh** [comment]
Having a release with your ssh-ng fixes would be awesome for my team.

**Comment by edolstra** [comment]
Please just cherry-pick bug fixes to the 2.0-maintenance branch and don't add release notes for bug fix releases.

**Comment by shlevy** [comment]
Hmm I think maintenance branches are likely to put us back in the position of having significant divergence between the latest release and the latest master and make it harder to get out feature releases as well. Can you explain why you prefer the maintenance model over releasing from master?

**Comment by edolstra** [comment]
It would be appropriate to release 2.1 from master, but not 2.0.1. Users should be able to count on patch releases like 2.0.1 not introducing regressions.

**Comment by shlevy** [comment]
Do you have any thoughts on how we can avoid divergence under this model? My thought is just that we should just bump to 2.1 (not necessarily released, just in the version file) as soon as we make a change justifying that.

**Comment by shlevy** [comment]
@edolstra (and rest of @NixOS/nix-core ) can you join the nix-core ml? I'd like to move this discussion there.

**Comment by edolstra** [comment]
Doing more frequent major releases in no way removes the need for a maintenance branch, especially given the existence of stable NixOS branches, since it would be irresponsible to apply major Nix upgrades in a stable NixOS branch (it should only receive bug fixes).

**Comment by puffnfresh** [comment]
@shlevy I don't think these ended up cherry-picked into the maintenance branch. Is that right?

**Comment by shlevy** [comment]
@puffnfresh Correct, there's an ongoing discussion about Nix release process that I hope to turn into an RFC this week https://groups.google.com/forum/#!topic/nix-core/9L7jZ9W8VGc

**Comment by shlevy** [comment]
@puffnfresh https://github.com/NixOS/rfcs/pull/28

**Pull request closed without merging**
