### PR TITLE
Git fetcher: Ignore .gitmodules entries that are not submodules

### LINKED ISSUE #10739: builtins.fetchGit fails with .gitmodules entries that aren't submodules
**Describe the bug**

In the situation where a git submodule used to exist, has been moved into the main repo, but not removed from .gitmodules, Nix is unable to fetchGit with submodules.  `git clone` is able to handle this fine, because .gitmodules is not the source of truth for what submodules exist — it's only used as a lookup table for where to fetch unpopulated submodules.  I think the right thing for Nix to do here is look through the git tree, and only fill in submodules that are actually submodules, ignoring other .gitmodules entries.

**Steps To Reproduce**

```
nix-repl> builtins.fetchGit { url = https://chromium.googlesource.com/chromiumos/platform/crosvm; ref = "release-R124-15823.B"; submodules = true; }
error:
       … while calling the 'fetchGit' builtin
         at «string»:1:1:
            1| builtins.fetchGit { url = https://chromium.googlesource.com/chromiumos/platform/crosvm; ref = "release-R124-15823.B"; submodules = true; }
             | ^

       … while fetching the input 'git+https://chromium.googlesource.com/chromiumos/platform/crosvm?ref=release-R124-15823.B&submodules=1'

       error: '«unknown»/third_party/vmm_vhost' is not a submodule
```

**Expected behavior**

Works.

**`nix-env --version` output**

nix-env (Nix) 2.22.0

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation
Fixes #10739.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Review by roberth — CHANGES_REQUESTED** [review]
In the notes linked in the issue, we concluded that

> * `.gitmodules` must not be the source of truth.

The implied source of truth is the tree entry that has a commit in it.

This seems like it leads to a nicer architecture, where the main process of accessing sources is to just follow the tree, where the submodule logic is only invoked for commit nodes. (Not to mention that this is probably how git proper implements its logic.)

A nice side effect is that `.gitmodules` parsing can be delayed until a commit node needs to be traversed, which may not even happen.

Releasing a partial fix isn't without risk, so I would prefer a solution that aligns with our earlier findings, so that we don't need to delve into this again after this partial fix reaches a sufficient number of users.

**Comment by edolstra** [comment]
> .gitmodules must not be the source of truth.

`.gitmodules` is the source of truth for the URLs corresponding to the commit nodes. AFAIK there is no other place to get that information.

What better fix do you have in mind?

**Comment by roberth** [comment]
That is correct. It is the source of truth for the submodule _fetching_ process.
What I intended to say was source of truth for the contents, where iiuc the structure of the tree is the source of truth.


Or in Alyssa's words:

> .gitmodules is not the source of truth for what submodules exist 

I guess that translates to pseudocode like

```python
for node in traverse(tree):
  if node is commit:
    node.replace(fetchSubmodule(node))

# where fetchSubmodule is "secondary" and of course uses .gitmodules
```

as opposed to:

```python
for submodule in submodules:
  tree = overlay(tree, submodule)
```

**Comment by edolstra** [comment]
@roberth The first pseudocode is essentially equivalent to the current behaviour, just a lot more expensive because it needs to traverse the entire tree. There are two possibilities for a mismatch between `.gitmodules` and the tree:

* An entry exists in `.gitmodules` that doesn't have a corresponding commit node. With this PR, this is ignored, just as with your pseudocode.
* A commit node exists without a corresponding entry in `.gitmodules`. This will result in an empty directory both in your pseudocode and in the current implementation.

**Review by roberth — APPROVED** [review]

**Pull request merged**
