### PR TITLE
Improve antiquotation within indented strings.

### LINKED ISSUE #543: Proper indentation of string interpolation
I have recently looked into https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/hardware/synaptics.nix whose interesting content is essentially :

``` nix
let tapConfig = ''
      Option "MaxTapTime" "180"
      Option "MaxTapMove" "220"
    '';
in {
    services.xserver.config =
      ''
      ...
        # Automatically enable the synaptics driver for all touchpads.
          Section "InputClass"
            Identifier "synaptics touchpad catchall"
            MatchIsTouchpad "on"
            Driver "synaptics"
            ${tapConfig}
            Option "ClickFinger1" "1"
          EndSection
      '';
}
```

This piece of code results into 

``` text
...
  # Automatically enable the synaptics driver for all touchpads.
  Section "InputClass"
    Identifier "synaptics touchpad catchall"
    MatchIsTouchpad "on"
    Driver "synaptics"
    Option "MaxTapTime" "180"
Option "MaxTapMove" "220"

    Option "ClickFinger1" "1"
  EndSection
```

instead of the expected

``` text
...
  # Automatically enable the synaptics driver for all touchpads.
  Section "InputClass"
    Identifier "synaptics touchpad catchall"
    MatchIsTouchpad "on"
    Driver "synaptics"
    Option "MaxTapTime" "180"
    Option "MaxTapMove" "220"
    Option "ClickFinger1" "1"
  EndSection
```

Is my interpretation a desirable behaviour ?
Stated differently : Would a patch fixing indentation of embedded indented strings be accepted ?

### PR DESCRIPTION
**Pull request by layus**
This pull requests is a proposal to fix #543.

Antiquotations in indented strings will have their last empty line removed
(when applicable) and an indented antiquotation will see all its lines
correctly re-indented.

As a small example is better than a long description, the following expression

```nix
let 
  abc = ''
    A
    B
    C
  '';
  context = body: ''
    BEGIN
      ${body}
    END
  '';
in context (context abc)
```

results in 

```nix
''
BEGIN
  BEGIN
    A
    B
    C
  END
END
''
```

instead of the old

```
BEGIN
  BEGIN
  A
B
C

END

END
```

Re-indent only applies to antiquotations that start a (possibly indented) line.

Do you like it ?

### CODE REVIEW

**Comment by spwhitt** [comment]
:+1: Seems much more intuitive behavior to me!

**Comment by layus** [comment]
Thanks !

I should mention that multiline antiquotations are not yet perfect.

What should 
```nix
''BEGIN
  ${abc}${abc}
END''
```
look like anyway ?

With my patch, it is 
```nix
''BEGIN
  A
  B
  CA
B
C
END''
```

I am not sure it is possible to do better than that...

**Comment by shlevy** [comment]
This seems very likely to change the hash of everything in nixpkgs, and doesn't seem like the improvement, if it is that, is worth the churn that would cause. :-1: from me, or at least wait until some other changes that also require rebuilding the world come along to group it in with.

**Comment by layus** [comment]
@shlevy There seem to be very few derivations that use "multiline antiquotations". But I agree that this change could trigger a massive rebuild.

Does someone know how to find and count the packages that would require a rebuild with this patch ?

**Comment by shlevy** [comment]
Oh, sorry, I misread this as being about multiline double-single quote strings. Sorry, ignore my last comment (at least until I have time to review)

**Pull request closed without merging**
