### PR TITLE
Log what `nix flake check` does

### PR DESCRIPTION
**Pull request by 9999years**
There's still room for improvement, but this produces much more informative output with `-v`:

```
$ nix flake check -v
evaluating flake...
checking flake output 'checks'...
checking derivation 'checks.aarch64-darwin.ghcid-ng-tests'...
derivation evaluated to /nix/store/nh7dlvsrhds4cxl91mvgj4h5cbq6skmq-ghcid-ng-test-0.3.0.drv
checking derivation 'checks.aarch64-darwin.ghcid-ng-clippy'...
derivation evaluated to /nix/store/9cb5a6wmp6kf6hidqw9wphidvb8bshym-ghcid-ng-clippy-0.3.0.drv
checking derivation 'checks.aarch64-darwin.ghcid-ng-doc'...
derivation evaluated to /nix/store/8brdd3jbawfszpbs7vdpsrhy80as1il8-ghcid-ng-doc-0.3.0.drv
checking derivation 'checks.aarch64-darwin.ghcid-ng-fmt'...
derivation evaluated to /nix/store/wjhs0l1njl5pyji53xlmfjrlya0wmz8p-ghcid-ng-fmt-0.3.0.drv
checking derivation 'checks.aarch64-darwin.ghcid-ng-audit'...
derivation evaluated to /nix/store/z0mps8dyj2ds7c0fn0819y5h5611033z-ghcid-ng-audit-0.3.0.drv
checking flake output 'packages'...
checking derivation 'packages.aarch64-darwin.default'...
derivation evaluated to /nix/store/41abbdyglw5x9vcsvd89xan3ydjf8d7r-ghcid-ng-0.3.0.drv
checking flake output 'apps'...
checking flake output 'devShells'...
checking derivation 'devShells.aarch64-darwin.default'...
derivation evaluated to /nix/store/bc935gz7dylzmcpdb5cczr8gngv8pmdb-nix-shell.drv
running 5 flake checks...
warning: The check omitted these incompatible systems: aarch64-linux, x86_64-darwin, x86_64-linux
Use '--all-systems' to check all.
```

In the future, it would be nice to print out the output paths and whether or not they were actually built (sometimes the checks are cached).

# Motivation/Context
See #8882:

> As of Nix 2.17.0, when I run `nix flake check`, the output doesn't tell me what was checked:
>
>     $ nix flake check
>     warning: The check omitted these incompatible systems: aarch64-linux, x86_64-darwin, x86_64-linux
>     Use '--all-systems' to check all.

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] documentation in the internal API docs
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

### CODE REVIEW

**Comment by 9999years** [comment]
By the way, I'm very confused by the logging code in `nix`. When logged at `lvlChatty`, the message is displayed on the current line and erased when another log message is emitted. When logged at `lvlInfo`, the result is the same, except that when `--verbose` is used subsequent log messages are printed on new lines. I can't find the code that's responsible for this anywhere — as far as I can tell, the `--verbose` flag just controls which levels of log messages are shown or not:

https://github.com/NixOS/nix/blob/6f623618565b07eb33514be70331e735c827bac6/src/libmain/common-args.cc#L15

https://github.com/NixOS/nix/blob/6f623618565b07eb33514be70331e735c827bac6/src/libutil/logging.cc#L91-L92

I though this might have something to do with the progress bar logger, but the various `--option log-format` values didn't seem to have any effect:

https://github.com/NixOS/nix/blob/6f623618565b07eb33514be70331e735c827bac6/src/libmain/loggers.cc#L23-L41

Any pointers here would be appreciated.

**Comment by 9999years** [comment]
I was surprised to notice that `nix flake check` only builds the `checks` -- I would have expected it to build the `packages`, `devShells`, `apps`, and so on as well. Perhaps a future PR can address that?

**Comment by phip1611** [comment]
Any update here? Would love to see this too!

**Review by tomberek — APPROVED** [review]
Looks good. Log level changes are helpful. Needs a conflict rebase.

**Comment by 9999years** [comment]
@tomberek Rebased to fix conflicts, PTAL

**Comment by 9999years** [comment]
Actually, I'll need to give this some more attention. Even though the logs are emitted at `lvlInfo`, they seem to only be printed temporarily, even at `-v`, and are erased when the 'activity' ends. Really weird behavior.

**Pull request merged**
