### PR TITLE
Make installer allow preexisting by default

### PR DESCRIPTION
**Pull request by matthewbauer**
This seems to be working okay for me. What is currently holding this up?

/cc @grahamc

### CODE REVIEW

**Comment by shlevy** [comment]
I think the main problem is if the preexisting installation is somehow broken, continuing with an automated process is likely to make fixing it even harder. If you have a working preexisting solution, why aren't you just upgrading Nix with Nix?

**Comment by matthewbauer** [comment]
Well there are lots of times when the Nix commands can be broken & there is no way to upgrade. This will happen to users who upgrade to macOS Mojave with old Nix versions.

**Comment by edolstra** [comment]
We just need to make sure that all actions done by the installer are idempotent.

**Comment by grahamc** [comment]
Well, the actions need to be more than idempotent -- the installer needs to handle every possible installation which already exists and know the right thing to do: fixing permissions to make it multi-user compatible, or fall back to the single user, or fix permissions on a badly configured multi-user setup, or fail ... etc. I much prefer the safety as is, and I think that expanding the tool to support handling weird installs potentially makes this a _much_ more complicated process. This complexity is why I don't support it now.

**Comment by grahamc** [comment]
Note, I do agree we should allow the script to be re-run in happy paths, however it is all the scary dark paths that I am worried about.

**Comment by shlevy** [comment]
@matthewbauer Yes, it's in exactly those cases where automatically going ahead is something to worry about though.

**Comment by matthewbauer** [comment]
I don't see how it's going to mess up your system though. The only critical part is installing the daemon - everything else shouldn't break anything. At least on macOS, evan a misconfigured daemon won't break anything AFAICT.

**Comment by matthewbauer** [comment]
@grahamc If the new installer will not support upgrades, could you update the 3rd bullet in default.nix:

https://github.com/NixOS/nixpkgs/blob/master/default.nix

I am not sure what to say there, exactly. But it definitely will need to be updated in time for when we want to move minver.nix to 2.0.

**Pull request closed without merging**
