### PR TITLE
flake check: Recognize well known homeModule/homeModules attribute

### PR DESCRIPTION
**Pull request by elohmeier**
# Motivation

This avoids warning fatigue, making nix flake check more effective.

# Context

See also https://github.com/NixOS/nix/pull/7606 and https://github.com/nix-community/home-manager/issues/1783.

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by roberth** [comment]
While I do think `modules.homeManager` is preferable, this isn't wrong.

See this issue, though I disagree about `configurations.<class>`
- #6257

**Review by roberth — APPROVED** [review]

**Comment by edolstra** [comment]
Do we need `homeModule`? Wouldn't it be better to standardize on `homeModules.default`?

**Comment by nakoo** [comment]
I feel this had to add `homeManagerModules` too. 
2k use case is not a small amount considering `homeModules` + `homeModules` only use 0.3k.

https://github.com/search?q=+language%3ANix+path%3Aflake.nix+homeManagerModules&type=code
https://github.com/search?q=+language%3ANix+path%3Aflake.nix+homeModule&type=code

**Comment by donovanglover** [comment]
I switched from `homeManagerModules` to `homeModules` and like that it's shorter. I think it fits well for merging home-manager into nixpkgs since it's similar to `nixosModules`.

**Pull request merged**
