### PR TITLE
WIP: Multi-user Install Cleaning + Fixes + Optional Uninstaller

### PR DESCRIPTION
**Pull request by jeff-hykin**
# WIP status: Looking for design feedback 

- **Run Workflow Status**: 🛑 I will run local tests (Linux/MacOS-intel/MacOS-arm) and probably make tweaks before needing a workflow test
- **Change Scope**: only multi-user install script (does include darwin/systemd)
- **PR documentation status**: overview finished, more detail could be added

# Motivation

The shell code has many edgecases, both unhandled edgecases such as ones caused by the recent fish integration, and edgecases such as the `selinux` check which could be part of a pattern. From the perspective of future one-time contributors, the order-of-execution flow inside of `install-systemd-multi-user.sh` and `install-darwin-multi-user.sh` is not obvious. Before getting into the goals, I want to mention this change is entirely made with POSIX/system compatibility in mind, it is not is not an offhand bashism-filled refactoring.

This PR is trying to:
- make aspects, such as shells, modular and comprehensive
- organize functions/variable into clear groups
- make chonological orders obvious
- fix all of the edgecase bugs that were made obvious after those^ changes
- implement some of the TODO's I found in the codebase (such as listing all leftover backup files instead of erroring one-at-a-time)
- fulfill the original goal of the PR; adding an **optional** agressive-uninstall for the multi-user case

# Context

### Shell API

The recent Fish addition missed some changes such as in the welcome function:
(All the shell profiles are listed, but not the fish targets)

Screen Shot 2023-02-13 at 10 36 56 AM

Since this is a systematic problem (shell-specific code is has no common denotion/marking, is not grouped into one place, and does not have a system of checks in place for detecting partial-implemenations) this PR creates a systematic solution by adding a `shell_` interface (4 functions) conceptually similar to the `poly_` functions.
There are also instructions added for how to add support for a new shell.

Here's what a modular form of shells might look like (ignore the `_helper`'s):

Screen Shot 2023-02-13 at 10 39 36 AM

They are then combined into one abstracted API
Screen Shot 2023-02-13 at 10 49 22 AM

### Poly Changes

The poly interface was adjusted since there was still OS-specific code inside of the main function that could not be pulled out. The new interface includes an ordering for poly functions that are expected to have a specific order inside of the main function. The main function was also flattened (as much as possible) to make the order of operations clear.

Both darwin-multiuser and systemd-multiuser fill out the poly interfaces as usual, but specifically with the ordered poly interface at the bottom.

Screen Shot 2023-02-13 at 11 24 52 AM

### New Poly Function: `poly_4_agressive_remove_artifacts`

Note, even though this is an ordered poly method, it is skipped by default for non-interactive and requires answering two prompts for the user-interactive case. `poly_4_agressive_remove_artifacts` is effectively an uninstaller.

In particular, for reviewers, one step of `poly_4_agressive_remove_artifacts` undoes the changes to user profiles.
The `poly_4_agressive_remove_artifacts` calls:
- `shell_unsetup_profiles` triggers three methods; one for bash, zsh, and fish
- `restore_profile` is called by each of those three methods
- `extract_nix_profile_injection` called by restore_profile

That last function **is probably the function that needs the most validation**. It tries to detect weirdness, which triggers a manual-edit-required, but otherwise slices out text inbetween `# Nix` and `# Nix End`.

The rest of `poly_4_agressive_remove_artifacts` is effectively an uninstaller for multi-user cases. It not only handles daemons, users, groups, and nix-paths, but also purges the daemons/groups/user etc that may have been leftover from older versions of nix. Arguably, it should be in a seperate script so that users can run it as an uninstaller without going through the begining of the installer script.

### HEREDOC's

I want to make this clear; this is an objective readability improvement not a style-preference change.
I have used spaces all my life, literally all 270 of my repos are **exclusively** indented with spaces.
However this:

indented

Is undeniably more readable than this:
Screen Shot 2023-02-13 at 11 11 28 AM

Because indented HEREDOC's require being indented with tabs, the refactor includes switching to tab-based indentation.

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

### CODE REVIEW

**Comment by Ericson2314** [comment]
It seems you have done a very thorough job here thinking about the issue documenting those thoughts, this is appreciated! However, the indentation changes current make the diff very hard to read. Is that extra level of indentation intentional?

Please fix this up before it is complete, and also please use the GitHub mechanism for making the PR draft too.

**Comment by jeff-hykin** [comment]
> very hard to read

I agree that the Github diff is very hard to read, but I think that is restricted (almost exclusively) to Github.
For example, this is what the diff looks like on my end:
Screen Shot 2023-02-22 at 10 47 37 AM


Github made a trifecta of terrible choices:
- tab-widths default to 8 characters with no option to customize
- defaults to showing whitespace changes, also with no option to disable
- wordwrap with no option to disable

And every other diffing tool, including plain 'ole git diff has those options AFAIK
[git diff no whitespace differences](https://stackoverflow.com/a/33159593/4367134)
[vs code no whitespace differences](https://stackoverflow.com/a/33159593/4367134))
which I think is as readable as any other PR.
[gitkraken no whitespace differences](https://stackoverflow.com/a/69464224/4367134)
etc
 

>  Is that extra level of indentation intentional?

Yes, for a couple reasons. One of the PR goals is grouping similar things.
This table-of-contents below is possible with code folding, which I think almost all editors support out of the box:

Screen Shot 2023-02-22 at 10 51 45 AM

But that option is only really practical if the contents of the groups are indented.
I think having a table of contents like this is important for one-time contributors to quickly drill down into the thing they wanted to fix.

Another reason is, similar to using arrow keys to expand a file explorer that has a tree-view, the indent creates a heirarchy that is used by indent-based navigation tools like [indent jump](https://marketplace.visualstudio.com/items?itemName=aPinix.indent-jump), [block travel](https://github.com/sashaweiss/vscode_block_travel), [indent travel](https://marketplace.visualstudio.com/items?itemName=pipme.indent-travel), [block jumper](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.mario), etc.

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nix/blob/36e3598225da173ae3eb6ec87056eb9c872d3ac1/scripts/install-darwin-multi-user.sh

indenting code between comments is highly non-standard. No formatter would do this, for example. I see what you mean about the collapsing but that is no worth this non-standard indentation.

Please make the indentation normal again (and go back from tabs spaces). If there is another way to indicate sections for collapsing in editors, we can try that instead. Otherwise It's just not that important. (You could also break up the support code into more files which would achieve a similar effect.)

**Comment by jeff-hykin** [comment]
> I see what you mean about the collapsing but that is no worth this non-standard indentation.

Okay I'll go ahead and make that change.

>  go back from tabs to spaces

So because of HEREDOC's that would be a functional change if tabs were replaced directly with spaces.
Here's that section of the original  post about that:

> ## HEREDOC's
> I want to make this clear; I have used spaces all my life, literally all 270 of my repos are **exclusively** indented with spaces. I wouldn't consider using tabs, except that this (which requires tabs):
> 
> indented
> 
> Is undeniably more readable than this: 
> Screen Shot 2023-02-13 at 11 11 28 AM
> 
> Because indented HEREDOC's require being indented with tabs, the refactor includes switching to tab-based indentation.
> #

**Comment by Ericson2314** [comment]
Oh interesting, I missed that entirely. That is a decent motivation. But in that case, I would as a separate PR, either before or after this (your choice).

**Comment by jeff-hykin** [comment]
Might take a bit, but I'll see what I can do in terms of breaking things up. @Ericson2314 

The PR is going to take a while to validate anyways though so I don't think theres too much of a rush. (If master keeps getting updated, that's fine, it's pretty easy to map changes)

**Comment by abathur** [comment]
Hi Jeff,

I have a little high-level feedback, but first I'll clarify where I'm coming from:
- I'm not a committer/decider/gatekeeper. These are just my thoughts as another contributor who's worked on the installer and attended most of the installer workgroup meetings. Others may disagree, and if they are in a position to actually merge this then it probably makes sense to pay more attention to them.
- I think I'm the one who's most-recently slogged through a ~large installer PR, so I have a little perspective on the process and work involved.

So, my main thoughts:
1. There's a history of even single-line changes breaking the installer for someone somewhere. The stakes are fairly high, and the automated test coverage isn't yet good enough to keep us from breaking people's installs with a half-baked change (and then needing to provide support to someone who may be annoyed with us). It can be hard to find people eager to review/merge these, so the test/review cycles can be long.

    It may feel like a single PR will save time, but keeping them laser-focused should make review easier and mitigate the risk of the whole batch getting reverted and having to start over if it's causing trouble.

2. Unless a committer is helping shepherd it through, a single big changeset could well take at least a few (and maybe several) months of active tending to get through the pipeline. Here's a breakdown of how it went for me:

    My diff was a bit under 1500 lines and it took 7 months end to end to land the actual PR. 2 months iterating on the work until *I* thought it was roughly finished, and 5 more for review, testing, fixing, and rebasing before someone felt comfortable merging. It took ~6 months to get released (we weren't on the 6-week cadence yet); between merge and release I needed 2 fix triage/debug/fix cycles to tidy up things that broke on people who were already using unstable installers for one reason or another. After the official release, I needed 7 more of those cycles over 7 months to track down and fix additional problems people ran into at scale. (I am just counting cycles that led to a fix; I inevitably worked with a fair number more people in individual issue reports to get those ferreted out and fixed, and I still triage most install issues in general just to make sure I'm not letting problems with my changes fester.)

3. There's an ongoing independent effort to write a Rust installer. That effort is bearing fruit, but it also isn't clear whether or not that installer will eventually become official. Nix still has a Shell installer for now, and it needs to work, but some people may be reluctant to invest a lot of time developing changes that aren't user-facing fixes until it's clearer whether we'll be keeping the Shell installer or adopting the Rust one (and what kind of timeline we might be looking at).

4. Regardless of whether you break any of the others out, I agree with @Ericson2314 on splitting out the formatting (and maybe organization) changes so that they can go (or not) on their own merit without blocking some of the user-facing improvements here.
    
    I'd break at least the indent change off into a PR by itself. I personally use tabs in my own shell projects for exactly this reason, but it's worth noting that the Nix-community is already very space-centric--I'm unsure how this will be received.

    I think it's worth sending this one alone because, when GitHub shows everyone a big heckin' diff, it'll be ideal if the PR description makes it clear that it's just a whitespace change--and people are able to check the work out locally and verify that there's no diff when they ignore whitespace. Then we can just debate the merit.

**Comment by jeff-hykin** [comment]
Hey @abathur, just jumping back in here to say no hard feelings. I occasionally get large PR's too and know they're hard to accept.

Anyways I realized I'm probably not going to have the time to break this up and incrementally merge it so I'm going to close it to clean things up. Maybe it can be used as a reference for future changes, or more likely it'll just get superseded by the rust installer.

**Pull request closed without merging**
