### PR TITLE
don't abort when given unmatched '}' with 'start-condition stack unde…

### LINKED ISSUE #751: Unmatched closing braces cause 'start-condition stack underflow'
Simply `nix-instantiate --eval -E '}'` results in:
````
start-condition stack underflow
````

This comes from the generated `flex` lexer.

### PR DESCRIPTION
**Pull request by fkz**
…rflow'. This fixes  #751

### CODE REVIEW

**Comment by domenkozar** [comment]
@fkz what's the error with your fix? Let's make sure it's human readable.

**Comment by fkz** [comment]
before:

    $ nix-instantiate -E '}'
    start-condition stack underflow

after:

    $ nix-instantiate -E '}'
    error: syntax error, unexpected '}', at (string):1:1

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by fkz** [comment]
btw, in some cases

**Comment by domenkozar** [comment]
cc @shlevy

**Pull request merged**
