### PR TITLE
Search: no longer output to $PAGER

### PR DESCRIPTION
**Pull request by evils**
Output search results to stdout, let the user see the results for install command.
As requested in #1261

### CODE REVIEW

**Comment by zimbatm** [comment]
Users who don't want a pager can `export NIX_PAGER=cat` but the reverse is not true.

**Comment by Evils-Devils** [comment]
I wasn't aware of the `NIX_PAGER` variable when i made this PR
nor do i recall ever seeing documentation for it.
If this variable can be supported while the default behaviour can be changed to `cat`, that would be preferable to me, but i'm not familiar enough with how these things are implemented to do that.
I think the current behaviour is less useful as one would usually want to type a `nix-env -i` command right after, and can't view the result while typing if `less` is used.
That was my use case when i was trying out nix on debian, and i think a bias in favour of usability for newcomers is not detrimental here. (an advanced user should know how to use `NIX_PAGER`, a beginner shouldn't)
As `nix search` seems like a natural first point of contact, i think it sends a bad message to potential users to break this convention.

**Comment by zimbatm** [comment]
looks like NIX_PAGER is only in the release notes and should be documented in the manual:
```
$ git grep NIX_PAGER
doc/manual/release-notes/rl-1.9.xml:  <listitem><para>The environment variable <envar>NIX_PAGER</envar>
src/libmain/shared.cc:    char * pager = getenv("NIX_PAGER");
```

**Comment by alexeymuranov** [comment]
IMHO, if `NIX_PAGER` is not set, there should be no paging.

**Comment by zimbatm** [comment]
The pager behaviour is consistent with other tools such as `journalctl` and `git log`

**Comment by evils** [comment]
> The pager behaviour is consistent with other tools such as `journalctl` and `git log`

i believe it is inconsistent with other package search tools such as `apt` and `pkg`

**Comment by edolstra** [comment]
Inconsistent in what way?

**Comment by evils** [comment]
> Inconsistent in what way?

Other package managers don't use a pager to display their results.
At least, the others i've used don't do so by default.

**Pull request closed without merging**
