### PR TITLE
Update flake to match removal of utillinuxminimal dependency

### PR DESCRIPTION
**Pull request by shadowrylander**
As per the change in https://github.com/NixOS/nixpkgs/pull/97294

### CODE REVIEW

**Comment by edolstra** [comment]
I may be missing something here but what does the kernel's util-linux dependency have to do with Nix? Nix depends on util-linux because it needs `unshare` in the tests  (https://github.com/NixOS/nix/pull/2211).

**Comment by shadowrylander** [comment]
Hmm... I think I'm missing something here as well... With `utillinuxminimal` in the flake I'm getting an error stating that said variable is undefined.

**Comment by edolstra** [comment]
IIRC `utillinux` was renamed to `util-linux` on nixpkgs master. However, Nix is pinned to 20.09 so it shouldn't be affected by that rename.

**Comment by shadowrylander** [comment]
Ah; my fault, then. I pinned its `nixpkgs` input to the master branch. Whoops. Sorry for wasting your time; I'll go ahead and close this! 😅

**Pull request closed without merging**
