### PR TITLE
parser rewrite

### PR DESCRIPTION
**Pull request by pennae**
# Motivation

the current parser is not really maintainable, slow, leaks memory all over the place, has very surprising short-range syntax interactions (as demonstrated by its large number of syntactic corner cases), uses a C skeleton and thus prohibits use of C++ features, the list just goes on and on. this exchanges the parser for one that is much faster, much more extensible, and **reusable**.

we have retrofitted some memory management into the old parser that is mostly (but not completely) correct since this was necessary to allow fuzzing of the old parser. we've run fuzzers over both parser for a couple thousands core hours to make sure that all valid inputs of the old parser are also valid inputs of the new one and produce the same AST, and that the new one doesn't accept anything the old one would reject (excluding bison implementation-defined errors like GLR stack exhaustion). unfortunately we can't share the test dataset because the fuzzers have managed to gobble up bits of private data and we will not be reviewing 50MB of junk to remove all of that again.

depends on #9874

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by thufschmitt** [comment]
Discussed during the Nix maintainers meeting on 2024-02-28.
This is a big change, will require some close coordination with the whole maintainer team.
@tomberek offered to act as a proxy to make sure the communication is happening.

**Comment by tomberek** [comment]
initial high-level look: 
- builds and runs as expected
- same evaluation results, nothing looks off
- nrExprs counts very different
- ~10% faster for something like a NixOS system
- similar memory usage
- not yet clear on how the new structure is more extensible or reusable
- can ExprConcatString improvements also be made to ExprOpUpdate? 

please rebase now that https://github.com/NixOS/nix/pull/9874 is merged, would make review easier.

**Comment by nyabinary** [comment]
I assume with https://github.com/NixOS/nixpkgs/pull/323845 someone else will have to pick up this right?

**Comment by aanderse** [comment]
i think this code was merged to lix

**Comment by roberth** [comment]
Nix hasn't stood still in the meanwhile.

> ~10% faster for something like a NixOS system

This would have to be measured again, since https://github.com/NixOS/nix/pull/11145 "improves parsing performance by ~6%, maybe more."

https://github.com/NixOS/nix/pull/11072 has also repaid at least [a bit of tech debt](https://github.com/NixOS/nix/pull/11072/files#diff-863c160dfa4d9ce5895d99a1aef48fb61c491d1ba594d555b818b70d7ba3c81fR25-R38).

I do like the idea of using a parser library instead, because it could indeed be a cleaner solution, but the impact is not as significant as it would have been around 2.20 or what the merge base of this is.

**Pull request closed without merging**
