### PR TITLE
Add builtin.breakpoint

### PR DESCRIPTION
**Pull request by junjihashimoto**
I'm trying to add a builtin.breakpoint to get it into repl everywhere.
This is the TODO of https://github.com/NixOS/nix/pull/3901.

Goal:
```
[nix-shell:~/git/nix]$ ./src/nix/nix repl
Welcome to Nix version 2.4. Type :? for help.

nix-repl> let a = 3; in builtins.breakpoint 2
Welcome to Nix version 2.4. Type :? for help.

nix-repl> a
3
```

Current result:
```
[nix-shell:~/git/nix]$ ./src/nix/nix repl
Welcome to Nix version 2.4. Type :? for help.

nix-repl> let a = 3; in builtins.breakpoint 2
Welcome to Nix version 2.4. Type :? for help.

nix-repl> a
error: --- UndefinedVarError ------------------------------------------------------------------------------------------------------------------------------ nix
at: (1:1) from string

     1| a
      | ^
     2| 

undefined variable 'a'
```

### CODE REVIEW

**Comment by edolstra** [comment]
Could you rebase this on top of #3901?  Then `breakpoint` can just call `debuggerHook` and do nothing if not running in `nix repl`. We don't want arbitrary Nix evaluations (e.g. `nix run`) starting a repl... Also, that way we don't have to put the repl in libexpr.

**Comment by junjihashimoto** [comment]
@edolstra I will try it. Thx!

**Comment by gytis-ivaskevicius** [comment]
This sounds awesome! Bump :eyes:

**Comment by junjihashimoto** [comment]
I should have to take out the attribute list of the environment created by let, then I have to add it to the staticEnv of NixRepl.
But I can't get the attribute list from EvalState.

**Comment by junjihashimoto** [comment]
I think that when I make let, a new Env is created and linked to the previous Env, but I don't know how to access the new Env from primop.

**Comment by tomberek** [comment]
similar: https://github.com/NixOS/nix/pull/5416

**Pull request closed without merging**
