### PR TITLE
installer: allow overriding nix user GID and UIDs

### PR DESCRIPTION
**Pull request by bjornfor**
Needed to resolve conflict in case the default GID and UIDs are in use.

### CODE REVIEW

**Comment by bjornfor** [comment]
Much better solution: https://github.com/NixOS/nix/pull/4346.

**Comment by bjornfor** [comment]
Closing in favor of https://github.com/NixOS/nix/pull/4346.

**Comment by bjornfor** [comment]
https://github.com/NixOS/nix/pull/4346 still isn't merged. I'm opening this again since it's a simple fix we can apply right now. (This UID/GID conflict issue came up again today, after having been hacked around with `sed` for over a year.)

**Comment by bjornfor** [comment]
macos CI seemed to have timed out after 60 minutes? And I don't know why the other checks were skipped. Will rebase to force another CI attempt.

**Comment by bjornfor** [comment]
All checks are green, please review (2 lines) and merge :-)

**Comment by bjornfor** [comment]
Thanks!

**Review by Veeezo — APPROVED** [review]

**Review by Veeezo — APPROVED** [review]

**Pull request merged**
