### PR TITLE
Expand nix serve manual

### PR DESCRIPTION
**Pull request by typetetris**
expand the manual a little bit around nix-serve, so others have an easier time setting up a binary cache with signatures and stuff.

Also removed mentions of some deprecated options in the manual as its bad style.

### CODE REVIEW

**Comment by typetetris** [comment]
Maybe that should also be merged into the 2.1 maintance branch, so it appears in the manual for 2.1.4 if there ever is such a version?

**Comment by typetetris** [comment]
@edolstra : Could you take a look or request another reviewer?

**Comment by typetetris** [comment]
Is there anything I can do to move that forward?
Maybe someone else can do a review?

**Comment by bhipple** [comment]
CC @edolstra @grahamc @shlevy this PR just has documentation and looks like an improvement over the status quo, since it removes references to deprecated arguments and explains the key signing more thoroughly.  Any chance it can be reviewed and merged?

**Comment by jakubgs** [comment]
I'm currently setting up a Nix cache and these instructions helped me. It would be nice if others didn't have to look for them in PRs.

**Comment by sheyll** [comment]
This was helpful for, could this be merged?

**Comment by jakubgs** [comment]
Why is this abandoned? This is clearly useful.

**Comment by zimbatm** [comment]
Mostly because Edolstra is overloaded and focused on flakes. All the legacy commands get less attention because of that.

**Comment by jakubgs** [comment]
No.

**Comment by jakubgs** [comment]
Still no.

**Comment by fricklerhandwerk** [comment]
@typetetris sorry for the enormous time your PR was stalled. Are you still interested in adding that information? It seems there is still some interest. I can help getting it merged.

**Comment by fricklerhandwerk** [comment]
The Nix team decided to close this PR since [`nix-serve` is a standalone tool](https://github.com/edolstra/nix-serve) with its own documentation. We will remove this part from the Nix reference manual.

**Comment by typetetris** [comment]
Ok with me. https://github.com/edolstra/nix-serve/blob/988014200965d96eda1285be2d2e4edd05bd3fe0/README.md already mentions `NIX_SECRET_KEY_FILE`. That seems sufficient.

**Pull request closed without merging**
