### PR TITLE
JSON: print paths as strings without copying them to the store

### PR DESCRIPTION
**Pull request by ncfavier**
Fixes https://github.com/NixOS/nix/issues/5612

### CODE REVIEW

**Comment by edolstra** [comment]
This breaks `builtins.toJSON`, e.g. in `builtins.toJSON { foo = ./file; }`, it's essential that `./file` is copied to the Nix store and added to the context of the resulting string. Maybe for `nix eval --json`, `printValueAsJSON()` could take a flag that controls whether paths are copied to the store.

**Comment by ncfavier** [comment]
Why should `toJSON` have this behaviour but not `toXML`?

**Comment by ncfavier** [comment]
I've added a flag `copyToStore` to `printValueToJSON`, set to false in `nix eval --json`, `nix-instantiate --eval --json` and `nix-env --json`.

**Comment by edolstra** [comment]
Not sure we should change `nix-env` / `nix-instantiate` behaviour. But it's fine to change `nix eval`.

**Comment by ncfavier** [comment]
Done

**Pull request merged**
