### PR TITLE
installables: Add --absolute

### LINKED ISSUE #8665: Nix installable resolution is actually impure for supposedly pure attributes like `nixosConfigurations`
**Describe the bug**

Let me be clear. We usually don't want to ignore the context of a Nix CLI invocation. `nix run` should not require users to specify their platform.

However, in some cases we do want to ignore the CLI context. For instance, `nixosConfigurations` is _not_ behind a system attribute set, because a machine configuration should be built in *one* way only. Reproducibly.

It would seem that the documented schema enforces this. No system attribute means one way to do it, but this is actually not the case, and users are finding out. I'll try not to proliferate the bad idea, but it involves installable resolution. So I'll jump to the solution instead.

**Steps To Reproduce**

Intentionally omitted.

**Expected behavior**

Nix implements a flag so that `currentSystem` is not used during installable resolution. I believe this comes down to treating the fragment as a literal attribute path without *any* lookup trickery.
`nixos-rebuild` passes this flag.

**`nix-env --version` output**

**Additional context**

Even `nixpkgs.buildPlatform` would be a massive impurity not to be overlooked by a flake's git history.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by roberth**
# Motivation

Closes #8665 

# Context

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [x] agreed on idea
 - [ ] agreed on implementation strategy
 - [x] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] documentation in the internal API docs
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Comment by edolstra** [comment]
"absolute" is a pretty vague term, could this be more descriptive? E.g. `--no-use-flake-attr-path-prefixes`.

**Comment by tomberek** [comment]
A syntax for this that has been handy is to use the following form:
```
flakeRef#.some-attr-path
```
The `.` prefix indicates no default prefixing. Patch: https://github.com/flox/flox/blob/main/pkgs/flox-bash/nix-patches/no-default-prefixes-hash.2.15.1.patch

**Comment by roberth** [comment]
> The `.` prefix indicates no default prefixing.

That's not searchable though.

**Comment by tomberek** [comment]
> That's not searchable though.

Possible, but there is precedence: [link](https://datatracker.ietf.org/doc/html/rfc1034) I can imagine that the "--absolute" documentation would mention this shorthand.
```
When a user needs to type a domain name, the length of each label is
omitted and the labels are separated by dots (".").  Since a complete
domain name ends with the root label, this leads to a printed form which
ends in a dot.  We use this property to distinguish between:

   - a character string which represents a complete domain name
     (often called "absolute").  For example, "poneria.ISI.EDU."

   - a character string that represents the starting labels of a
     domain name which is incomplete, and should be completed by
     local software using knowledge of the local domain (often
     called "relative").  For example, "poneria" used in the
     ISI.EDU domain.
```

**Comment by iFreilicht** [comment]
> "absolute" is a pretty vague term, could this be more descriptive? E.g. `--no-use-flake-attr-path-prefixes`.

That seems overly verbose. As this prevents searching the default prefixes, how about `--no-defaults`? Though I have to say, I'm fine with absolute, it's terse and to the point, and "absolute path" is already a well-known term, so the leap to "bsolute attribute path" isn't far.

> A syntax for this that has been handy is to use the following form:
> 
> ```
> flakeRef#.some-attr-path
> ```

That's very nice. It also has precedent in terms of paths generally; `relative/path` vs `/absolute/path`

**Comment by roberth** [comment]
I think we should at least have an option for setting the attribute search prefixes, which can be set to empty for achieving "absolute" behavior.
The prefix(es) would often be set by scripts and tools that call Nix for the user, and I think it would be nice for users to have a syntax for absolute attribute paths, so that those scripts and tools don't need to implement such logic themselves.

- [ ] `attribute-search-prefixes` option
- [ ] `.foo.bar` absolute attribute path notation

Either one can replace `--absolute`, so I don't think we should have that flag. Leaving this open because we don't have issues for these yet.

**Comment by roberth** [comment]
We have #8852 now.
Don't need this anymore.

- #8852

**Pull request closed without merging**
