### PR TITLE
nix-mode: pair antiquote delimiters correctly

### PR DESCRIPTION
**Pull request by ttuegel**
Ensure that opening and closing antiquote delimiters are paired
correctly regardless of context. When antiquotes appear outside of
strings, avoid creating extra string delimiters.

There are still some syntax highlighting issues with antiquotes; specifically, the contents of an antiquote inside `"` quotes are not highlighted. However, pairing the delimiters correctly is still a significant improvement.

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @peterhoeg @matthewbauer @rzetterberg @eqyiel @mikefaille @teh @Profpatsch of emacs users.

**Comment by teh** [comment]
I've moved to https://github.com/matthewbauer/nix-mode - but thanks for fixing this!

**Comment by matthewbauer** [comment]
So, I've found that the reason that antiquotes don't work in double quotes is because we try to close them with a "generic string delimiter" but the double quotes aren't a generic string.

```lisp
(put-text-property (+ start 1) (+ start 2) 'syntax-table (string-to-syntax "|"))
```

The fix I've come up with is to just set double quote to be a generic string delimiter. See commit 3136d1bdc98fb723d449a9536d5b5fba44600ed5.

**Comment by ttuegel** [comment]
> So, I've found that the reason that antiquotes don't work in double quotes is because we try to close them with a "generic string delimiter" but the double quotes aren't a generic string.

I was aware of this, but I hadn't gotten around to fixing it yet. Thanks! Did you find a simple way to avoid having double-quotes accidentally close two-single-quoted strings?

**Comment by Profpatsch** [comment]
Fun fact: nixexpr antiquotation is apparently context-sensitive.

**Comment by groxxda** [comment]
@Profpatsch I don't think so. Care to elaborate?

**Comment by matthewbauer** [comment]
@ttuegl I hadn't noticed that the quotes in the multiline quotes unescaped the string. Perhaps this isn't a good fix for that problem. It would be nice if we could arbitrarily find what kind of closing quote syntax the antiquote needs and set the syntax properties to that but I've not been able to get something like that to work.

**Comment by Profpatsch** [comment]
> I don't think so. Care to elaborate?

Only anecdotally. @Gabriel439 tried to implement a parser with parser combinators (which can do context-free grammars), but parsing multiline strings with antiquotation needed something more powerful.

**Comment by groxxda** [comment]
@profpatsch as far as I can tell, our bison code is context-free.
since I'm writing a peg parser atm, it would be good to know if this is a dead-end. ;-)

**Comment by ttuegel** [comment]
> as far as I can tell, our bison code is context-free.

If we have a perfectly good bison parser, could we use wisent to generate an Emacs parser?

**Comment by copumpkin** [comment]
It seems possible that we have a context-free parser built on top of a stream of tokens produced by a context-sensitive lexer, and that the lexer is what handles the scary multiline strings? I have no actual knowledge here, but that isn't particularly unusual.

**Comment by afrepues** [comment]
@copumpkin you are right, [context-sensitive lexing](https://en.wikipedia.org/wiki/Lexical_analysis#Context-sensitive_lexing) could be to blame here.

**Comment by layus** [comment]
Yes, our lexer is context sensitive. This is required to parse `''${ { a = "a${"lol"}";}.a }''` correclty, otherwise first mismatched closing brace would close the antiquotation.
See #573 where I removed a old hack to use a proper stack of start conditions (as described in https://ftp.gnu.org/old-gnu/Manuals/flex-2.5.4/html_mono/flex.html#SEC11).
With this method, the lexer returns proper string chunks and nix expression. This is quite clean an implementation for a recursive language :).

But yes, it's crappy to support correctly in editors. I think it is however acceptable to have the syntax highlighter *not* recognise `''${var /* } */}''` as a proper antiquotation, even if it is. Vim does not for example. However, we should be able to highlight `''${var /* { } */}''` correctly.

Anyway, in nixpkgs, we accept that our editors may be wrong: https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/development/interpreters/python/wrap-python.nix#L17 :-D

**Comment by matthewbauer** [comment]
So can we get this and #1120 merged in pretty soon?

**Comment by mikefaille** [comment]
I'll try hit as soon as I can. ty !

**Comment by domenkozar** [comment]
@matthewbauer what's the status of this and #1120?

**Comment by matthewbauer** [comment]
It's been a while, but I've rebased #1120 so it doesn't conflict with this. If @ttuegel is okay with it, I think this should be merged (#1120 can be merged as well but there are more changes and I have gotten as much feedback).

**Comment by ttuegel** [comment]
Yes, I think this is good to go. I have noticed a few places where it could be improved. For example, I didn't know Nix allows antiquotes outside strings entirely. It is uniformly an improvement over the existing highlighter, though.

**Comment by ljli** [comment]
This is indeed a vast improvement over the current state. It is not easy to trip up, but [here](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/display-managers/default.nix) or [here (only at the end)](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/generic-builder.nix) it is still mixed up.

Another thing I noticed is that there are temporary CPU spikes on opening large files like python-packages.nix, resulting in a blocked emacs for a few seconds. After the file is opened and fontified navigation and editing is mostly smooth, but occasionally emacs blocks up to 2 minutes (using one core at 100%) when jumping through a buffer (specifically python-packages.nix). I'm not sure what exactly triggers it, but without nix-mode the problem goes away.

I also took a stab at fontification (among other things) [here](https://github.com/ljli/nix-mode) building on [matthewbauer/nix-mode](https://github.com/matthewbauer/nix-mode). So far I wasn't able to break the latest iteration. If someone wants to give it a spin, I'm happy about feedback.

**Comment by matthewbauer** [comment]
@ljli That's useful to know! My bet is that the CPU spikes you are seeing are from running "nix-syntax-find-antiquote-open" every time fontification happens. "nix-syntax-find-antiquote-open" has to read through every char in the document and that could lead to locks if you're making lots of edits quickly.

Can you verify that the CPU spikes don't happen in the base nix-mode or my custom nix-mode?

**Comment by ljli** [comment]
That it blocks for several seconds (or minutes) is specific to this PR.

**Comment by ttuegel** [comment]
> My bet is that the CPU spikes you are seeing are from running "nix-syntax-find-antiquote-open" every time fontification happens. "nix-syntax-find-antiquote-open" has to read through every char in the document and that could lead to locks if you're making lots of edits quickly.

This is very inefficient, but a better approach was not forthcoming to me. I will check out your forks; if things are working better there, I suggest we make a separate `nix-mode` repository under the `NixOS` organization. Making releases through MELPA will allow us to iterate much more quickly.

**Comment by matthewbauer** [comment]
:+1: On separate repos. I don't think anyone has a better idea on antiquotes. I will need to dig into Emacs internals more to understand what's going on.

**Comment by ljli** [comment]
A nix-mode repo controlled by NixOS would be optimal. Maybe we could just transfer your repo if you are ok with that. And thanks for incorporating my changes so quickly, I will add a few remarks on the issue tracker. The added functionality is pretty bare bones so far.

Regarding the antiquote matching. The general strategy of the nix-mode (pre this PR) is sound. The key change to make it work for me (without scanning back arbitrarily far) was to keep the built-in bracket matching intact. Which means we can't set a string delimiter on an antiquote closing brace, but we can do it one character behind it. That requires a little bit of attention to what is behind the closing brace, though.

**Comment by Profpatsch** [comment]
Have you thought about building an [hnix](https://hackage.haskell.org/package/hnix) binary to implement the Language Server Protocol for nix?

That would solve the problem once and for all for editors me thinks.

**Comment by matthewbauer** [comment]
@Profpatsch It's definitely something to look into. Syntax highlighting is not in LSP but some useful abstractions are included like "documentSymbol".

**Comment by matthewbauer** [comment]
cc @domenkozar @edolstra 
It seems like there is consensus (or at least indifference) to setting up a separate "nix-mode" repo outside of nix. Who is able to setup a repo on the NixOS org? You can use my [nix-mode](https://github.com/matthewbauer/nix-mode) repo as a base. We can then move remaining issues, prs, and discussions there and make things easier on Nix maintainers.

**Comment by domenkozar** [comment]
I can do that if it's reasonable for @edolstra

**Pull request closed without merging**
