### PR TITLE
Test and document `builtins.baseNameOf`, improve internal `baseNameOf()`

### PR DESCRIPTION
**Pull request by roberth**
# Motivation

`baseNameOf` is weird. Deal with it.

# Context

Found while at code related to #10303 

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
FWIW programming language standard libraries tend not to remove any slashes:

 - https://hackage.haskell.org/package/filepath-1.5.2.0/docs/System-FilePath.html#v:takeBaseName
 - https://docs.python.org/3/library/os.path.html
 - https://en.cppreference.com/w/cpp/filesystem/path/filename

Perhaps we will eventually (not now!) migrate our *internal* `baseName` to work that way too, e.g. as part of #9205. But totally that agreed removing all trailing slashes is more consistent that removing just one.

**Comment by flokli** [comment]
This changed hashing behaviour, see https://cl.snix.dev/c/snix/+/31164

**Comment by xokdvium** [comment]
~~It does not, there was a subsequent regression.~~

**Comment by xokdvium** [comment]
Ah sorry, thinking of unrelated fuckup of dirOf https://github.com/NixOS/nix/pull/14515

**Pull request merged**
