### PR TITLE
Accept multiple inputs in `nix flake update`

### LINKED ISSUE #9764: `nix flake update` doesn't seem to work with multiple inputs
**Describe the bug**

The [`nix flake update` docs](https://github.com/NixOS/nix/blob/cbd5553d57ebf5d0532047165a2d81825424bd76/src/nix/flake-update.md?plain=1#L50C1-L52C76) specify
> Unlike other `nix flake` commands, `nix flake update` takes a list of names of inputs
to update as its positional arguments and operates on the flake in the current directory.
You can pass a different flake-url with `--flake` to override that default.

but this doesn't seem to work.

**Steps To Reproduce**

```console
$ nix flake update nixpkgs-stable
warning: updating lock file '/Users/n8henrie/git/nixos/flake.lock':
• Updated input 'modules':
    'path:/nix/store/k89kr521x8cd49lkn68by7sxfgcy2kwj-source/modules?lastModified=1&narHash=sha256-UAaa9Fyj2JAbHGj7MoBMBv7Ym4aESGcTFeVEpm44QEA%3D' (1970-01-01)
  → 'path:/nix/store/k7ysr5jlwfv2gkqymlb3z9mdvi972ici-source/modules?lastModified=1&narHash=sha256-UAaa9Fyj2JAbHGj7MoBMBv7Ym4aESGcTFeVEpm44QEA%3D' (1970-01-01)
• Updated input 'overlays':
    'path:/nix/store/k89kr521x8cd49lkn68by7sxfgcy2kwj-source/overlays?lastModified=1&narHash=sha256-/7vpfCda1hJZ07BMdZhosGKYeHULvvhb2z7ZtEsA4SI%3D' (1970-01-01)
  → 'path:/nix/store/k7ysr5jlwfv2gkqymlb3z9mdvi972ici-source/overlays?lastModified=1&narHash=sha256-/7vpfCda1hJZ07BMdZhosGKYeHULvvhb2z7ZtEsA4SI%3D' (1970-01-01)
$ nix flake update home-manager
warning: updating lock file '/Users/n8henrie/git/nixos/flake.lock':
• Updated input 'modules':
    'path:/nix/store/k7ysr5jlwfv2gkqymlb3z9mdvi972ici-source/modules?lastModified=1&narHash=sha256-UAaa9Fyj2JAbHGj7MoBMBv7Ym4aESGcTFeVEpm44QEA%3D' (1970-01-01)
  → 'path:/nix/store/zwmfmxpysz7d84qr35rpnfl3h49v2g07-source/modules?lastModified=1&narHash=sha256-UAaa9Fyj2JAbHGj7MoBMBv7Ym4aESGcTFeVEpm44QEA%3D' (1970-01-01)
• Updated input 'overlays':
    'path:/nix/store/k7ysr5jlwfv2gkqymlb3z9mdvi972ici-source/overlays?lastModified=1&narHash=sha256-/7vpfCda1hJZ07BMdZhosGKYeHULvvhb2z7ZtEsA4SI%3D' (1970-01-01)
  → 'path:/nix/store/zwmfmxpysz7d84qr35rpnfl3h49v2g07-source/overlays?lastModified=1&narHash=sha256-/7vpfCda1hJZ07BMdZhosGKYeHULvvhb2z7ZtEsA4SI%3D' (1970-01-01)
$
$ nix flake update nixpkgs-stable home-manager
error: unexpected argument 'home-manager'
Try 'nix --help' for more information.
$ nix flake update nixpkgs-stable,home-manager
warning: Invalid flake input 'nixpkgs-stable,home-manager'. To update a specific flake, use 'nix flake update --flake nixpkgs-stable,home-manager' instead.
error: invalid flake input path element 'nixpkgs-stable,home-manager'
$ nix flake update 'nixpkgs-stable home-manager'
warning: Invalid flake input 'nixpkgs-stable home-manager'. To update a specific flake, use 'nix flake update --flake nixpkgs-stable home-manager' instead.
error: invalid flake input path element 'nixpkgs-stable home-manager'
$ nix flake update '["nixpkgs-stable" "home-manager"]'
warning: Invalid flake input '["nixpkgs-stable" "home-manager"]'. To update a specific flake, use 'nix flake update --flake ["nixpkgs-stable" "home-manager"]' instead.
error: invalid flake input path element '["nixpkgs-stable" "home-manager"]'
```
Am I holding it wrong?

**Expected behavior**

```console
$ nix flake update nixpkgs-stable home-manager
... works ...
```

**`nix-env --version` output**

```console
$ nix-env --version
nix-env (Nix) 2.19.2
```

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by olmokramer**
# Motivation

Fixes #9764 

# Context

As described in the linked issue, `nix flake update <input1> <input2>` would error with

```
$ nix flake update input1 input2
error: unexpected argument 'input2'
```

This happened because the `handler` of `CmdFlakeUpdate` only accepted a single `std::string` argument. This changes the handler to accept a `std::vector<std::string>` and loop over all the inputs to update.

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by olmokramer** [comment]
I've kept this PR in draft mode for now because I haven't added any tests yet. Would be happy to add some but I'm not entirely clear on where this should be tested.

**Review by thufschmitt — COMMENTED** [review]
Thanks!

For the tests, the simplest is to add it to `tests/functional/flakes/flakes.sh`.
https://github.com/NixOS/nix/blob/21282c3c204597641402c6bcff8fc9ee7bc31fa1/tests/functional/flakes/flakes.sh#L564-L565 could be a good place.

**Comment by olmokramer** [comment]
Thanks again for your input @thufschmitt! I've added a test in the location you pointed out now.

**Review by thufschmitt — APPROVED** [review]
Thanks!

Set on auto-merge, should go as soon as the CI is happy

**Comment by Aleksanaa** [comment]
Will this be backported to 2.19 and 2.20 since the documentation describing such behaivor is there?

**Comment by thufschmitt** [comment]
> Will this be backported to 2.19 and 2.20 since the documentation describing such behaivor is there?

Oh, thanks for the reminder. Triggered the backports

**Pull request merged**
