### PR TITLE
Fix spec file

### PR DESCRIPTION
**Pull request by OptiverTimAll**
This fixes the issues I reported in #926.

I used the resulting `nix.spec` to build an RPM, installed it on a fresh CentOS 7 host and tried to install `tmux`, but Nix decided it needed to rebuild the world and exploded with `mbtowc()` problems while trying to build GNU M4... I'm *pretty* sure that's unrelated to these changes, though.

### CODE REVIEW

**Comment by OptiverTimAll** [comment]
(cc: @edolstra, who seems to have done most of the work on `nix.spec.in` so far, and @goodtune, who asked nicely)

**Comment by goodtune** [comment]
+1

**Comment by domenkozar** [comment]
Just a note, one commit was reverted: https://github.com/NixOS/nix/commit/d1a5c28a465dfaf2601ec20f43566d6bfd6ab87d

**Comment by OptiverTimAll** [comment]
Hmm, that doesn't seem like a good move:

- nixos.org only offers `.tar.xz` downloads, and I expect people who want to build RPMs are going to want to build them from the official source tarball.
- The d1a5c28 commit message says "Nixpkgs's rpmBuild function only copies
in the .tar.gz file."
- After the revert, the `.spec` file now looks for the archive in `.tar.bz2` format.

It seems to me that Nix needs to anoint one "official" tarball format and use that for all these various automated systems. Who should I approach, and what can I contribute, to help that decision get made?

**Pull request merged**
