### PR TITLE
autoCallFunction: Auto-call functors

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by shlevy** [comment]
Refs NixOS/nixpkgs#11233

**Comment by lethalman** [comment]
Use case: I have a `buildImage = args: somedrv;`.

Without functor, to make it overridable I'd need:

```
buildImage = args: (somedrv // { overrideImage = newargs: buildImage (args // newargs); });
image1 = buildImage {...};
image2 = image1.overrideImage { overrides... };
```

With functor it *could* be (but it's not because nix-build does not auto call the functor):

```
buildImage = args: args // { __functor = self: _: somedrv; };
image1 = buildImage {...};
image2 = image1 // { overrides... };
realdrv = image1 {};
```

Simply put, nix-build currently auto calls functions. Just make it auto call functors too :) Would that be hard?

**Comment by shlevy** [comment]
Let me know if this works as you want and I'll merge it in.

**Comment by lethalman** [comment]
@shlevy I wonder if we can be more conservative. What if we find a derivation with `__functor` inside?  Maybe it's better to evaluate the derivation instead of calling the functor?

**Comment by shlevy** [comment]
@edolstra Any thoughts on preferred semantics there? I can see arguments for both cases...

**Comment by lethalman** [comment]
Ah wait, problem solved. A derivation can only contained serializable thing, and a function like `__functor` isn't, it's an error.

**Comment by vcunat** [comment]
> A derivation can only contained serializable thing

Are you sure? I thought we often use `somePackage // { foo = bar; }`.

**Comment by shlevy** [comment]
Yeah, with passthru or // outside of the call to `derivation` you can have a derivation that's a functor

**Comment by lethalman** [comment]
@vcunat you are right, that's after the `derivation {}` call has been done...

**Comment by lethalman** [comment]
Tested it and works fine :+1: except now `nix-build` does not auto calls functors if they are in sets.

```
{
  a = drv;
  b = { __functor: self: {}: drv; };
}
```

`nix-build` will only build `a`, and skips `b`.
```

**Comment by lethalman** [comment]
Btw the other controversy I can find is about abusing it, making it necessary to nest multiple levels.

E.g. currently we can have: `pkg.override` and `pkg.overrideDerivation`. One overrides the function arguments, the second the derivation.

If we made this by means of functors, we cannot decide which level to override, without expliciting the level:

```
mkDerivation' = args: args // { __functor = self: {}: mkDerivation self; };
pkg = args: args // { __functor = { inputs, ... }: {}: mkDerivation' { ... }; };
```

Now to override a package inputs: `pkg // { .. };`. To override the derivation: `(pkg {}) // { ... }`.

It will lead to new cases for sure if abused...

**Comment by edolstra** [comment]
Except for the indentation this looks good to me.

**Comment by roberth** [comment]
- Regression: #13674

**Pull request merged**
