### PR TITLE
Turn keep-going on by default, add --fail-early flag

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by shlevy** [comment]
Refs #1084

**Comment by FRidh** [comment]
I've experienced as well plenty of times that I would have wanted `--keep-going` but I forgot it. At the same time, it also happened that because a build failed early, I detected the mistake early and was able to fix it right away, instead of letting it compute for a long time working on items that would fail as well.

I'm against changing the default. If I rebuild my system and a dependency fails, then what's the point in continuing? It won't work anyway without patching. 

Adding a configuration option instead makes a lot more sense to me.

**Comment by FRidh** [comment]
Which I now saw is done in https://github.com/NixOS/nix/pull/1111, that's great.

**Comment by vcunat** [comment]
What's the point? For example, my typical situation is that only the failing stuff needs to be fixed and rebuilt, and others tend to remain the same. In that case I `--keep-going` and fix the failures while the build continues... but the approach is really only well usable together with `-Q`.

Still, I'm not certain whether to change this default.

**Comment by edolstra** [comment]
Not convinced that either default is better than the other, so we may as well stick with the current one...

**Pull request closed without merging**
