### PR TITLE
adding $HOME/.nix-channels to $NIX_PATH

### LINKED ISSUE #1123: Add more than one channel to NIX_PATH
My ```$HOME/.nix-channels``` currently has two entries

```
$  cat ~/.nix-channels
https://nixos.org/channels/nixos-16.09 nixos-16.09
https://nixos.org/channels/nixpkgs-unstable nixpkgs
```

As one mightuse more than one channel on a regular basis, it'd be convenient to have all subscribed channels as part of NIX_PATH like
```
NIX_PATH=nixos-16.09=/Users/plumps/.nix-defexpr/channels/nixos-16.09:nixpkgs=/Users/plumps/.nix-defexpr/channels/nixpkgs
```

What do you think?

### PR DESCRIPTION
**Pull request by plumps**
fixes #1123

### CODE REVIEW

**Comment by edolstra** [comment]
Some issues with this:

* Channels and ~/.nix-defexpr will probably be deprecated in the next Nix release (in favor of setting $NIX_PATH directly).
* Channel names don't necessarily correspond to the expected $NIX_PATH prefix, e.g. a NixOS channel is called `nixos-16.09-small` while the $NIX_PATH entry should be `<nixpkgs>`.
* This would require you to log in again to make channel changes reflected in $NIX_PATH.
* I'd prefer not to call awk from every login shell.

**Comment by copumpkin** [comment]
@edolstra do you have writing somewhere on how you plan on replicating the "update channel when you see fit" behavior we have today with channels in the `NIX_PATH` world? I'd like some amount of control over when my system changes out from under me (perhaps even causing an evaluation error while I'm trying to do something else), and the timed re-downloading of a tarball  we have today doesn't really cut it.

**Comment by danbst** [comment]
I think @edolstra just says that nix-channel can be separated to separate project, it is easy reimplementable and doesn't belong to core Nix

**Comment by edolstra** [comment]
My thinking was more that you can use `NIX_PATH` for most nix-channel use cases, including pinning a specific version of Nixpkgs, e.g. `NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/63def04891a0abc328b1b0b3a78ec02c58f48583.tar.gz`. However, this doesn't address @copumpkin's use case (not updating unless explicitly asked for). This could be done using an infinite TTL on downloaded files, so `NIX_PATH=nixpkgs=channel:nixos-16.09` would cause the channel to be fetched only the first time. Not sure what the best UI for that is, though.

**Comment by copumpkin** [comment]
@edolstra part of the reason I'm so interested in #520 is that I think that could be a cool model for channels as well as packages. The main properties I want out of a nondeterministic derivation are the ability to (somehow, programmatically) define how often I want it to update, and (most of the time) give myself a way of pinning to a particular version. Think of Ruby's Gemfile and Gemfile.lock distinction: Gemfile (on some level) defines an update policy (via bounds on package versions), and Gemfile.lock is an instantiation of that policy to exact versions that will be reproducible.

Think of what we want from channels:
1. I want to point to e.g., github.com/nixos/nixpkgs-channels/tree/nixpkgs-unstable (basically an update policy; I want to update at most as often as the branch updates)
2. The branch can be resolved to an exact hash for later reproducibility
3. I want to know explicitly that somewhere in my (otherwise highly deterministic) Nix evaluation, a possibly nondeterministic "moving target" is involved, and be given the opportunity to lock it down to something that point 2 produces

I don't know of a great UI for this, but here's one not-so-great one that might inspire other ideas:

1. When you write a nondeterministic derivation, you generate a UUID and paste it into the expression source
2. Any evaluation of that nondeterministic derivation will get added to a top-level list of sources of nondeterminism in your expression, indexed by the associated UUID, and it's very clear when you evaluate an expression that your nondeterminism is included (so like when the top-level list of things to build and things to download from cache is printed, it could include a third category for these)
3. Any build of a nondeterministic derivation gets a sandbox that allows network access
4. The interface could (at first at least) basically be one that gives you a little "shim" to decide what to feed into a fixed-output derivation. That is, nondeterministic derivation = deterministic FO derivation + "decide (and record) which version to download". That would accommodate many common cases of git hashes and the like.
5. Nix maintains a central registry on your machine of current resolved UUIDs, and lets you request that a particular UUID be updated (this is the equivalent of `nix-channel --update`)

Then this mechanism can be used for channels, Hydra sources (don't have to make VCS into a first-class notion in Hydra anymore), packages that have sensible update semantics, and so on.

I realize this is still pretty sketchy and probably doesn't belong in this ticket, but I do think something in this direction would be a killer feature, allowing us to unify the deterministic Nix world with changing surroundings in a relatively painless manner.

**Comment by Gabriel439** [comment]
I also want to point out that whether or not channels are deprecated there is a simpler way to do what this pull request intends, which is to set the `NIX_PATH` to:

```
NIX_PATH=$HOME/.nix-defexpr/channels/
```

That way any time you add a channel named `foo`, you will automatically be able to reference it using `<foo>` with the above `NIX_PATH`

From the `man` page:

```
       NIX_PATH
           A colon-separated list of directories used to look up Nix
           expressions enclosed in angle brackets (i.e., <path>). For
           instance, the value

               /home/eelco/Dev:/etc/nixos

           will cause Nix to look for paths relative to /home/eelco/Dev and
           /etc/nixos, in that order. It is also possible to match paths
           against a prefix. For example, the value

               nixpkgs=/home/eelco/Dev/nixpkgs-branch:/etc/nixos

           will cause Nix to search for <nixpkgs/path> in
           /home/eelco/Dev/nixpkgs-branch/path and /etc/nixos/nixpkgs/path.
```

Besides being simpler, this would ensure that you don't have to re-run your `~/.profile` script whenever you add or remove a channel

I still agree with the general sentiment of using the `NIX_PATH` directly instead of channels, just to have one less moving part.  However, until that switchover is complete we should continue to support the channel-based mechanism.

**Pull request closed without merging**
