### PR TITLE
builtins.readDir: fix nix error trace on filesystem errors (backport #11378 to 2.24)

### PR DESCRIPTION
**Pull request by Mic92**
# Motivation

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Review by fricklerhandwerk — APPROVED** [review]

**Comment by Mic92** [comment]
@fricklerhandwerk can we get a minor release for this?

**Comment by fricklerhandwerk** [comment]
@edolstra needs to cut the release, we didn't automate the process yet.

**Comment by Mic92** [comment]
Provide me the manual steps and I write a github action for this.

**Comment by fricklerhandwerk** [comment]
This is as far as we have it documented: https://github.com/NixOS/nix/blob/master/maintainers/release-process.md

**Comment by Mic92** [comment]
Ok. The point releases look like low-hanging fruit.

**Pull request merged**
