### PR TITLE
downloader: when retry but can't resume, retry the whole file

### PR DESCRIPTION
**Pull request by domenkozar**
I'm not sure I fully understand how code works, but I assume `init` is called for each retry and this is the correct way to sync up `warn` and the actual behavior of resuming.

Fixes https://github.com/NixOS/nix/issues/3278

I'd appreciate a maintenance release since a lot of users of Cachix are hitting this occasionally.

### CODE REVIEW

**Comment by edolstra** [comment]
I'm not sure this is correct. If we've already written to a sink, then we *can't* do a retry because we would end up writing the same data twice. Otherwise we get errors like "error 9 while decompressing xz file". (See 53247d6b116905e7233b1efd6c14845e20d27442.)

**Comment by domenkozar** [comment]
Seems like CI fails due to https://github.com/NixOS/nix/commit/e322a16523c3c0644a900453abbe32bd0fd982e3

**Comment by domenkozar** [comment]
@edolstra is there any way to reset the sink?

**Comment by edolstra** [comment]
No. But if ranged requests are unavailable, we could discard the first `n` bytes (where `n` is the number of bytes previously written to the sink).

**Comment by domenkozar** [comment]
Couldn't `download` raise an exception so that the caller would setup the sink again?

**Comment by edolstra** [comment]
That was what 78fa47a7f08a4cb6ee7061bf0bd86a40e1d6dc91 tried to do but it was a lot more complicated.

**Comment by domenkozar** [comment]
Actually, we should prevent from connecting the sink until we assert response status code is 2xx

**Comment by edolstra** [comment]
@domenkozar But the status code already *is* 2xx. The problem is that the transmission of the body gets interrupted.

**Comment by domenkozar** [comment]
I'm not so sure, https://github.com/NixOS/nix/issues/3278 is 504 and I've seen reports with `526 Invalid SSL Certificate`, so I'm a bit puzzled why those are not retried if the body wasn't consumed (and if it was 200, status code wouldn't be able to change?).

**Comment by edolstra** [comment]
Hm, it's possible `writeCallback` is called with the 5xx body.

**Comment by domenkozar** [comment]
Going to continue in https://github.com/NixOS/nix/issues/3278

**Pull request closed without merging**
