### PR TITLE
Improve install script

### PR DESCRIPTION
**Pull request by bjornfor**
See commit messages for details.

### CODE REVIEW

**Comment by bjornfor** [comment]
Linking to https://github.com/NixOS/nix/issues/1283, because I stumbled across it when testing this code.

**Comment by domenkozar** [comment]
lgtm @edolstra

**Comment by bjornfor** [comment]
Ping.

**Comment by bjornfor** [comment]
Ping.

I'd like to be able to install Nix on offline network. This PR achieves that (plus some small improvements). I don't mind if an alternative approach is implemented, I just want to be able to (easily) install Nix on a PC that doesn't have access to nixos.org.

Any comments?

**Comment by copumpkin** [comment]
Looks good to me! @edolstra? Doesn't seem controversial so maybe one of the other committers could merge it?

**Comment by edolstra** [comment]
I'm not too keen on adding features to `scripts/install-nix-from-closure.sh`, to prevent having two different installers with divergent feature sets.

**Comment by bjornfor** [comment]
@edolstra: Would it be better if I implement the same options in the other installer? Or do you have another idea how to allow installing Nix on offline PC?

**Comment by bjornfor** [comment]
I'll try a different approach.

**Pull request closed without merging**
