### PR TITLE
Print the value in `value is X while a Y is expected` error

### PR DESCRIPTION
**Pull request by 9999years**
# Motivation

Adds the failing value to `value is <TYPE> while a <TYPE> is expected` error messages.

# Context
Partial fix for #561, in particular https://github.com/NixOS/nix/issues/561#issuecomment-1518408458.

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Comment by roberth** [comment]
We have to be careful not to print too much. For instance, `pkgs` isn't just cyclic but diverging, and `printValue` doesn't have a mitigation for that.
We don't want to fail before printing the actual message!
`Value::print` has a depth limit, but isn't quite safe.

To make this work well, I we should have a safe and brief printing method that
- only prints one level deep (maybe two levels for lists, after making sure not to print too many items)
- only returns a string up to a certain length, perhaps 120?
- does not evaluate values that haven't been forced yet
- prints the most useful attributes first: `_type`, `name` and `type` (but only if their values have already been forced)
- can print a package `name` without instantiating the derivation (`outPath`, `drvPath`)

**Comment by 9999years** [comment]
@roberth I double-checked this and it doesn't force values, so it's OK:

```
$ cat bad.nix -p
let
  pkgs = import <nixpkgs> {};
in
  pkgs ++ 1

$ nix-instantiate --eval bad.nix
error:
       … while evaluating one of the elements to concatenate

         at /Users/wiggles/nix/bad.nix:4:8:

            3| in
            4|   pkgs ++ 1
             |        ^
            5|

       error: value is a set while a list was expected: { AAAAAASomeThingsFailToEvaluate = <CODE>; AMB-plugins = <CODE>; ArchiSteamFarm = <CODE>; AusweisApp2 = <CODE>; CHOWTapeModel = <CODE>; ... }
```

Printing all of `pkgs` attribute names like this adds about 20ms to the command. Limiting the attributes printed is a good idea -- I'd also like if this code printed lambda locations and derivation paths like `nix repl` does.

Maybe I'll take a shot at unifying the printing code (it's duplicated in a few places), but even with very large output (like "all of nixpkgs") it's much more helpful than not having anything (IMO).

**Comment by edolstra** [comment]
Our error messages are already way too verbose, e.g. a typical NixOS evaluation error dumps thousands of lines of stacktrace info on the screen. Printing giant values (like `pkgs` or `config`) is only going to make it harder to see the actual error.

**Comment by Qyriad** [comment]
Your error messages aren't too verbose; they have too much noise and not enough signal. Nix's call traces being difficult to visually parse is arguably *helped* by this change because in a sea of "while calling …" lines the one that contains a big value is probably at least slightly more important than all the other myriad lines.

This at *least* puts visual emphasis on *something* that at least probably gives *some* helpful information.

Yeah, some smart heuristics for large values would be nice, but this is still better than the status quo.

**Pull request closed without merging**
