### PR TITLE
Remove unused `operator<=>`'s that darwin can't generate

### PR DESCRIPTION
**Pull request by roberth**
# Motivation

It was complaining *a lot*, with dozens of MB of logs.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Review by Ericson2314 — CHANGES_REQUESTED** [review]
Can we make Darwin generate them instead somehow? Because https://github.com/NixOS/nix/pull/10838 needs a fix for that, and if we can solve it for this, then we might as well keep these for testing.

(I thought they were already needed for testing!)

**Comment by roberth** [comment]
> Can we make Darwin generate them instead somehow?

It doesn't have a `<=>` for `std::map`. I don't see how we could affect that, except requiring newer dependencies, if they even implement that.

This is easy enough to revert, or re-add, and makes the build log usable again.

I was unable to find the build problem with https://github.com/NixOS/nix/pull/11021 without this.

**Review by edolstra — APPROVED** [review]

**Review by Ericson2314 — APPROVED** [review]
OK fair enough, I'm convinced. It is an easy revert.

**Comment by Ericson2314** [comment]
I learned the problem is libc++ 16 is just too old. So yeah, we can't do this until Nixpkgs updates to a newer LLVM.

**Pull request merged**
