### PR TITLE
libstore: consider a resolution error as a NotFound

### PR DESCRIPTION
**Pull request by grahamc**
> My biggest problem with flights: figuring out how to make nix stop trying to fetch from cache when there is no network.  
>
> Would love it to not even try if no network interfaces are up, instead of figuring out what flag to use. 
>
> Maybe hack on that?
-- https://twitter.com/ProgrammerDude/status/1138090058727264256

### CODE REVIEW

**Comment by roberth** [comment]
This may not always be a desirable behavior, for use cases where detecting errors early is desirable, such as in build farms. The expected symptom is a slowdown, the size of which is hard to estimate without real world testing.
Yet, lacking this information, I do expect that this PR is a net improvement.

**Comment by grahamc** [comment]
For build farms: do they substitute? I'm not sure builders in a build farm do substitute.

**Comment by grahamc** [comment]
ie: I think the controlling system does the substitution on their behalf.

**Comment by cleverca22** [comment]
https://github.com/NixOS/hydra/blob/5dd4736aedc1d1356c54bd737db813e25192a885/src/hydra-queue-runner/build-remote.cc#L92-L98
https://github.com/NixOS/nix/blob/7cc1a2593ebece4df28abc86c8b83f5d14dc23a0/src/libstore/legacy-ssh-store.cc#L258-L271

when asking a build slave what it has, you give it a boolean, saying if you will allow it to check the cache

so the `queryValidPaths` function may infact trigger large amounts of network traffic

**Comment by grahamc** [comment]
Nix has a `--no-net` flag in `master`, so closing.

**Pull request closed without merging**
