### PR TITLE
Fix PID namespace support check

### LINKED ISSUE #7783: this system does not support the kernel namespaces that are required for sandboxing
# Description

Between 8ab9fda and c192151 my ability to upgrade my system and use my `direnv` flakes has been broken with the following
```bash
$ direnv allow
direnv: loading ~/code/repos/others/some-org/frontend/.envrc                                                                                                                
direnv: using flake
warning: Git tree '/home/john/code/repos/others/some-org/frontend' is dirty
error: this system does not support the kernel namespaces that are required for sandboxing; use '--no-sandbox' to disable sandboxing
warning: Git tree '/home/john/code/repos/others/some-org/frontend' is dirty
direnv: nix-direnv: renewed cache
```

Looking at the commit history between these two commits it's clear that this is somewhat intentional/expected: Additional checks are being added to ensure that a `linux` host has cgroup namespace support enable in their kernel. But, is it expected that this should, by default, break existing environments?

If there is already a discussion or documentation about this intended breaking change and how to fix it then I'd be happy to be provided a URL and I'll go RTFM. I wanted to create this issue since I couldn't find any other place online, yet, where anyone has discussed this problem and it's solution. In the interim I've `nixos-rebuild switch --rollback`ed.

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

Fixes #7783 by actually checking whether /proc can be remounted in a mount+PID namespace.

Includes some refactoring to add `clone()` support to `startProcess()`.

# Context

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

### CODE REVIEW

**Comment by roberth** [comment]
Did you try to write a NixOS test for this?

**Comment by edolstra** [comment]
Yeah I've repurposed the remote-build test for this.

**Comment by useranon350** [comment]
This seems to cause issues when following https://nixos.wiki/wiki/Installing_from_Linux. I am getting "error: this system does not support the kernel namespaces that are required for sandboxing; use '--no-sandbox' to disable sandboxing" when running ```NIX_PATH="nixpkgs=channel:nixos-23.11" nixos-install``` from within a chroot or unshare -R session. I can use pid namespaces outside of a chroot. I have confirmed that ```unshare -fp --keep-caps --mount-proc=proc``` works, and allows further ``mount -t proc none proc``` calls.

**Comment by useranon350** [comment]
I was able to solve the problem by using the pivot_root method with an additional step of ```unshare -m --propagation unchanged``` and ```mount --bind . .``` prior to starting the pivot. chroot and unshare -R both caused spurious issues with remounting /proc and legitimate issues with mount namespaces, although I think the latter were a result of my / not being a mountpoint. (Specifically, they wouldn't allow setting the mount propagation to rprivate on the new /.)

I think this could be resolved with a documentation update.

**Pull request merged**
