### PR TITLE
Fix flake profile use of originalUrl vs. originalUri

### LINKED ISSUE #5872: flakes: consistency with URL/URI
Some JSON outputs refer to things as uri vs url
```
src/nix/flake-metadata.md:* `original` and `originalUrl`: The flake reference specified by the
src/nix/flake.cc:            j["originalUrl"] = flake.originalRef.to_string();
src/nix/profile.cc:                        parseFlakeRef(e["originalUri"]),
src/nix/profile.cc:                obj["originalUri"] = element.source->originalRef.to_string();
src/nix/profile.md:      "originalUri": "flake:nixpkgs",
src/nix/profile.md:* `originalUri`: The [flake reference](./nix3-flake.md) specified by
src/nix/profile.md:* `uri`: The immutable flake reference to which `originalUri`
```

This was noticed when trying to use the same logic with a manifest.json and `nix flake metadata`

I have no strong opinion at the moment exactly which way to go, but would prefer to have consistency. I started to turn things into URI (https://github.com/tomberek/nix/commit/c59cac1261ceb551e553aab69d950d2688955d24), but thought it might be better to bring this up as an issue instead a PR.

### PR DESCRIPTION
**Pull request by garbas**
Fixes #5872

### CODE REVIEW

**Comment by dtzWill** [comment]
FWIW profiles created with this change cannot be read by versions of nix before this change.

Noticed testing recent nix and suddenly my system nix's `nix profile list` and friends don't work, simply producing this:

```
error: [json.exception.type_error.302] type must be string, but is null
```

With no traceback or additional messages with `--debug` and `--show-trace`.

`nix profile history` actually makes it up through my profile history until the first manifest with the new key, which is what led me to coming here ...

Maybe backport the read-compatibility portion of this change to release versions? (OTOH it's experimental after all...)

**Comment by tomberek** [comment]
there is also a mismatch of uri/url:
```
{
  "elements": [
    {
      "active": true,
      "attrPath": "defaultPackage.x86_64-linux",
      "originalUrl": "flake:nix",
      "storePaths": [
        "/nix/store/gyg1l3750rd0r9ydfy7jg9yp1ryjvxm3-nix-2.8.0pre20220330_2252272"
      ],
      "uri": "github:NixOS/nix/22522722a6e62d723a8da4d3a0c0b7c6af09c05f"
    },
```

**Comment by garbas** [comment]
@dtzWill Sorry for the breakage and thank you for the report. I'll work on this on Friday (if nobody else does is before me until then)

**Comment by tomberek** [comment]
Was thinking of something like this: https://github.com/flox/nix/commit/50f9f335c92a88e8c9bd3421e6befbcd06cac4ec

**Pull request merged**
