### PR TITLE
fix kill(-1, signo) fail on FreeBSD

### PR DESCRIPTION
**Pull request by shen390s**
In freebsd, if there is no other processes for current user kill(-1, signo) will fail with error "permission denied"

### CODE REVIEW

**Comment by shen390s** [comment]
I have checked this in FreeBSD 9.1, it seems that there is no this problem.

It seems better to treat this as the problem of FreeBSD

**Comment by shen390s** [comment]
this is problem of freebsd

**Comment by ysangkok** [comment]
@shen390s when you say "problem of FreeBSD", what do you mean by that?

**Comment by shen390s** [comment]
I means that the behavior of syscall kill() in FreeBSD for the case:

if there is no other processes for current user kill(-1, signo) will fail with error "permission denied"

is incorrect. The newer version of FreeBSD has fixed this problem.

**Pull request closed without merging**
