### PR TITLE
replaced uncaught_exception with uncaught_exceptions

### PR DESCRIPTION
**Pull request by p01arst0rm**
small fix, uncaught_exception is deprecated in favour of uncaught_exceptions.
nothing huge.

### CODE REVIEW

**Comment by Ericson2314** [comment]
https://en.cppreference.com/w/cpp/error/uncaught_exception It's removed in C++20, in fact.

**Comment by edolstra** [comment]
We had to revert this a couple of months ago because it didn't work on macOS yet: 93b1ce1ac522ff92626da5cdd689008063935844. Maybe it works now.

**Comment by Ericson2314** [comment]
Looks like it is passing CI? Maybe switch to 20.03 did the trick.

**Comment by edolstra** [comment]
Could be, but the Hydra builders are not running Catalina yet.

**Comment by Ericson2314** [comment]
The error message says "introduced in macOS 10.12", so I think just sierra is sufficient? I have no idea what our support window is, however.

**Comment by edolstra** [comment]
I think the problem is that the headers are too old, or something.

**Comment by Ericson2314** [comment]
In that case, since we are using a nixpkg-provided headers, the builder OS version shouldn't matter so much?

**Comment by edolstra** [comment]
Probably, but I don't know how pure the stdenv on darwin is these days.

**Comment by Ericson2314** [comment]
I'll go check.

**Comment by matthewbauer** [comment]
It might help to add `-mmacosx-version-min=10.12` to CFLAGS. I didn't think it was necessary since we set MACOSX_DEPLOYMENT_TARGET elsewhere.

**Comment by Ericson2314** [comment]
Hmm, we have been setting `MACOSX_DEPLOYMENT_TARGET` to something new enough since github.com/nixos/nixpkgs/commit/f1070eec27e889566d441d90d54dc3619ce6c91e . Maybe it was the headers version.

In any event, I think we should set up a hydra job for just this branch, or just merge it and one of us can monitor hydra to see what happens.

**Comment by edolstra** [comment]
Okay, we'll see what happens :-)

**Comment by p01arst0rm** [comment]
#WorksForMe

**Pull request merged**
