### PR TITLE
fetchgit: Comprehensive valid reference check.

### PR DESCRIPTION
**Pull request by shlevy**
This ensures we're matching git's definition of a valid reference.

### CODE REVIEW

**Comment by edolstra** [comment]
:-1: on doing an uncached call to an external program.

Also, why not just call `runProgram`?

**Comment by shlevy** [comment]
Is caching in memory OK?

I didnt use runProgram vecau

**Comment by shlevy** [comment]
@edolstra updated with caching and using runProgram

**Comment by shlevy** [comment]
Hmm, not sure why PR isn't updating, maybe because I accidentally closed it earlier? Will open a new one.

**Pull request closed without merging**
