### PR TITLE
fix passing CA files into builtins:fetchurl sandbox

### PR DESCRIPTION
**Pull request by Mic92**
# Motivation

# Context

CA as in Certificate Authority

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Review by tomberek — APPROVED** [review]

**Comment by edolstra** [comment]
Not sure this is the right solution. We're already bind-mounting the CA file into the sandbox (see `LocalDerivationGoal::runChild()`). Doesn't that work for `builtin:fetchurl`?

Alternatively, if we're passing `caData` into the sandbox, then we can get rid of the bind-mounting.

**Comment by Mic92** [comment]
So:

```
pathsInChroot.try_emplace("/etc/ssl/certs/ca-certificates.crt", canonPath(caFile, true), true)
```

Works on platforms that have the certificate in this location.
However this won't work on some linux distributions such as openSUSE, which use a different location. Could we potentially use `NIX_SSL_CERT_FILE` here? Than users can also override this in case they cannot modify /etc.

**Comment by edolstra** [comment]
@Mic92 `/etc/ssl/certs/ca-certificates.crt` is the location used inside the sandbox. The location outside the sandbox is `caFile`, which should be `NIX_SSL_CERT_FILE`.

**Comment by Mic92** [comment]
Ok. I have to check why it fails than anyway.

**Comment by puckipedia** [comment]
> @Mic92 `/etc/ssl/certs/ca-certificates.crt` is the location used inside the sandbox. The location outside the sandbox is `caFile`, which should be `NIX_SSL_CERT_FILE`.

This is not true in a very important cases: the macOS sandbox. It cannot bind-mount, and thus the location of the certificate may not be found. (Though, due to [other circumstances](https://github.com/NixOS/nix/security/advisories/GHSA-wf4c-57rh-9pjg), the macOS sandbox doesn't work on `builtin:fetchurl`.)

Alongside that, the other issue is that on Linux, `builtin:fetchurl` will use the `caFile` option from outside the sandbox, causing it to ignore `/etc/ssl/certs/ca-certificates.crt` if it doesn't exist outside the sandbox. I decided to go for an approach that'd work on macOS always, without special-casing a single file outside the normal sandboxed paths, that might conflict with paths inside the sandbox (e.g. if the certificate file exists *inside* the Nix store.)

**Pull request merged**
