### PR TITLE
Enable secret content in the nix-store.

### PR DESCRIPTION
**Pull request by nbp**
This set of patches add a SecretMode class.  This class is used to prevent doing permissive chmod on the content of the nix-store.  The instances of this class are initialized with a few functions which are used to collect the name of the user which will own the file.

In order to test this features, these patches are adding builtins.toSecretFile primitive, and a special attribute named "secret" to the attribute set argument of derivations.  The "secret" attribute expect a boolean value.  Both the "secret" attribute and the "toSecretFile" primitives make the derivation/output only readable by the owner of the nix-store.

### CODE REVIEW

**Comment by wmertens** [comment]
See also #8 which has a patch that does what I describe in https://github.com/NixOS/nix/pull/329#issuecomment-58824084

**Comment by copumpkin** [comment]
How's this going?

**Comment by nbp** [comment]
This was waiting on @edolstra review, but I am no longer sure I should expect any reviews now.

I can only guess that this solution is not perfect enough to be commented on and that we prefer to have no solution than a root-only solution.

I am probably not going to work on this pull-request again, unless I got more feedback.  This is the second pull request I do on the Nix project and I think this project lacks responsive maintainers.

If I keep having no response, I guess I should fork the Nix project and start maintaining my own fork of it.

**Comment by copumpkin** [comment]
I think it might make sense to spread out the responsibility a bit on this repo (and other non-nixpkgs repos). I get that not many people outside of @edolstra are "experts" on this codebase, but what's the worst that can happen if we add a handful more core Nix people to the repo? If nothing else, it'll spread the sense of ownership over the project and encourage people to give more feedback and learn more about it.

**Comment by nmikhailov** [comment]
>  I think this project lacks responsive maintainers

This.
My impression is that everything except for new packages/updates is destined to stale for years. From time to time I come to check NixOS's status and the progress is not impressive. And this is understandable when project lacks manpower, but when there are people who are willing to work on complex core issues and they don't get comments and reviews it is rather questionable.

This is indeed management problem. I think if core devs lack time it should be their No1 priority to review, guide and encourage new development to further offload it to new devs who are willing to work on the project. Today it is rather frustrating.

**Comment by gador** [comment]
This is kinda sad that all that work that went into this PR didn't even get a comment from @edolstra. Maybe the new "Teams" will help with the large amount of PR's and issues so effort like this isn't wasted

**Pull request closed without merging**
