### PR TITLE
Replace unicode apostrophes with ascii

### PR DESCRIPTION
**Pull request by charles-cooper**
Dropped down to src and executed

```
find . -type f -exec sed -i "s/‘/'/g" {} +
find . -type f -exec sed -i "s/’/'/g" {} +
```

Fixes https://github.com/NixOS/nix/issues/532

### CODE REVIEW

**Comment by domenkozar** [comment]
Could you do it again? Codebase changed meanwhile :)

**Comment by charles-cooper** [comment]
whoops, this fell off my radar. should be good to go!

**Comment by danbst** [comment]
Here is the new reincarnation https://github.com/NixOS/nix/pull/1377

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/rfcs/commit/690b7ca81e22513ec6a80e402928badd4a856c71

**Pull request closed without merging**
