### PR TITLE
ci: split of eval and build into two jobs

### PR DESCRIPTION
**Pull request by Mic92**
nix flake show will go over the whole flake but than only build a subset. It does this also for both macOS and Linux, however we only need this to be done once.
For the actually builds, this commit switches to nix-fast-build. Since there are a fair amount of nixos tests in .#checks this will speed up the run by having both evaluation and build in parallel, furthermore nix-fast-build will skip any packages already present in cachix. Also it will try to build all flake outputs and than report the failed one at the end. This has the advantage that successful ones will be skipped on the next run and we get a list of all failed attributes.

Depends on https://github.com/NixOS/nix/pull/11581 + a nix patch release.

# Motivation

# Context

- Works around https://github.com/NixOS/nix/issues/5200

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by Mic92** [comment]
Mhm looks like our flake does import-from-derivation?

```
nix --experimental-features 'nix-command flakes' flake check -L --no-build
```

fails

**Comment by Mic92** [comment]
I fixed the CI error that we see here in: https://github.com/NixOS/nix/pull/11581

**Review by roberth — CHANGES_REQUESTED** [review]
Could we run 

```
nix --experimental-features 'nix-command flakes' flake check -L --no-build
```

in addition in a concurrent job?

**Comment by Mic92** [comment]
@edolstra promised to make this fast in his own way.

**Pull request closed without merging**
