### PR TITLE
Feature: Indent multiline antiquotations (v2).

### LINKED ISSUE #543: Proper indentation of string interpolation
I have recently looked into https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/hardware/synaptics.nix whose interesting content is essentially :

``` nix
let tapConfig = ''
      Option "MaxTapTime" "180"
      Option "MaxTapMove" "220"
    '';
in {
    services.xserver.config =
      ''
      ...
        # Automatically enable the synaptics driver for all touchpads.
          Section "InputClass"
            Identifier "synaptics touchpad catchall"
            MatchIsTouchpad "on"
            Driver "synaptics"
            ${tapConfig}
            Option "ClickFinger1" "1"
          EndSection
      '';
}
```

This piece of code results into 

``` text
...
  # Automatically enable the synaptics driver for all touchpads.
  Section "InputClass"
    Identifier "synaptics touchpad catchall"
    MatchIsTouchpad "on"
    Driver "synaptics"
    Option "MaxTapTime" "180"
Option "MaxTapMove" "220"

    Option "ClickFinger1" "1"
  EndSection
```

instead of the expected

``` text
...
  # Automatically enable the synaptics driver for all touchpads.
  Section "InputClass"
    Identifier "synaptics touchpad catchall"
    MatchIsTouchpad "on"
    Driver "synaptics"
    Option "MaxTapTime" "180"
    Option "MaxTapMove" "220"
    Option "ClickFinger1" "1"
  EndSection
```

Is my interpretation a desirable behaviour ?
Stated differently : Would a patch fixing indentation of embedded indented strings be accepted ?

### PR DESCRIPTION
**Pull request by layus**
Antiquotations in indented strings will have their last empty line removed
(when applicable) and an indented antiquotation will see all its lines
correctly re-indented.

:exclamation: This features changes the semantics of indented strings and therefore triggers a mass rebuild of (nearly) all the derivations.
I still believe it is worth it, but we should obviously gather all such changes in one step.

As a small example is better than a long description, the following expression

``` nix
let 
  abc = ''
    A
      ${""}
    B
  '';
  context = body: ''
    BEGIN
      ${body}
    END
  '';
in context (context abc)
```

results in 

``` nix
''
BEGIN
  BEGIN
    A
    B
  END
END
''
```

instead of the old

```
BEGIN
  BEGIN
  A

B

END

END
```

Re-indent only applies to antiquotations alone on one line, surrounded only by spaces.

This pull requests is a rewrite of #549 on top of #573.
It fixes #543.

### CODE REVIEW

**Comment by vcunat** [comment]
- I agree with this change of semantics (note: I don't have push access in this repo). Mass rebuilds happen almost every week on nixpkgs/staging, so I don't see a significant problem if e.g. nix-1.9 <-> 1.10 switch causes another rebuild.
- Do these changes really depend on #573? If not, why not keep them as independent PRs?
- I haven't looked closely into the diffs (yet).

**Comment by edolstra** [comment]
@vcunat It's actually a big problem to change the semantics. For instance, it means you cannot check out an old version of Nixpkgs and still get binaries. It also means that Hydra will have to build two sets of binaries, one for Nix <= 1.9 and one for >= 1.10.

**Comment by vcunat** [comment]
I was aware of some of the problems, but not all, actually. I just thought we'd say that on month X we change the default binaries from 1.9 to 1.10. Now I see it would be a problem to switch among branches if they defaulted to different nix versions.

But let's start optimistically &ndash; I think it's possible that this semantics change wouldn't actually cause a mass rebuild in our nixpkgs. If that is (still) the case on all active branches, it seems better to do the change now before it starts making a difference.

**Comment by edolstra** [comment]
No, it does cause a mass rebuild (as @layus indicated), e.g. because of this code in the stdenv-linux bootstrap:
```
        preHook =
          ''
            # Don't patch #!/interpreter because it leads to retained
            # dependencies on the bootstrapTools in the final stdenv.
            dontPatchShebangs=1
            ${commonPreHook}
          '';
```

**Comment by vcunat** [comment]
Ah, unlucky. A more elaborate transition would be to fixup these mass-rebuild cases beforehand (by a mass rebuild) so that this PR wouldn't have a mass-rebuild impact, and then merge this PR after 14.12 is killed.

I know it's getting far-fetched, but I really don't like the current semantics and if we leave it for some more years, it's only likely to get more painflu to change.

**Comment by layus** [comment]
For what it's worth, I agree with @vcunat. We should deal with painful changes sooner than later. 

It seems that we understand the full problem, and that the final decision is up to @edolstra.
As far as I understand, we can
1. Drop this semantics change (sad, but easy to do :smile:)
2. Provide binaries for *both* semantics for some time (say, one year)
3. Apply the change and cope with the disrupted binary compatibility as soon as possible.

I really cannot say which is best, but 3. is my favorite.

**Comment by wmertens** [comment]
Why not have a slightly different syntax for the new semantics? e.g.
`${>foo}`?

On Sat, Jul 11, 2015, 20:33 Guillaume Maudoux <notifications@github.com>
wrote:

> For what it's worth, I agree with @vcunat <https://github.com/vcunat>. We
> should deal with painful changes sooner than later.
>
> It seems that we understand the full problem, and that the final decision
> is up to @edolstra <https://github.com/edolstra>.
> As far as I understand, we can
> 1. Drop this semantics change (sad, but easy to do [image: :smile:])
> 2. Provide binaries for *both* semantics for some time (say, one year)
> 3. Apply the change and cope with the disrupted binary compatibility as
> soon as possible.
>
> I really cannot say which is best, but 3. is my favorite.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nix/pull/580#issuecomment-120651606>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by vcunat** [comment]
@wmertens, to me that doesn't feel like a good long-term solution.

**Comment by layus** [comment]
I just got another hacky idea:
We could temporarily fixup the code to ensure that both semantics coincide, like so:
```diff
        preHook =
          ''
            # Don't patch #!/interpreter because it leads to retained
            # dependencies on the bootstrapTools in the final stdenv.
            dontPatchShebangs=1
-           ${commonPreHook}
+           ${commonPreHook}${# This is a transient hack. See GitHub issue 580}
          '';
```

These patches should remain for some time (one year ?) and then we could commit the semantics change to nix. At that point, nothing should change because the new semantics coincides with the old one.
After another year we could start removing the hacks. At that point, the old version of nix should have disappeared, and hydra can build all the derivations with the new semantics.

This transition would ensure that 
1. New versions of Nix can built and find binaries on hydra for nixpkgs derivations up to one year old.
2. Old nix versions can benefit from hydra for new derivations up to one year more recent.

This solves the problem of having two hydra branches at the same time and postpones the mass-rebuild to the moment where we will remove the hack on stdenv.

Would that be enough ?

**Comment by layus** [comment]
I have tested on the nixpkgs tree to see if a hack such as described in my previous comment is doable.

So, the modification done here is to precede every antiquotation starting a line by a second empty antiquotation :
```
$ cd ~/projects/nixpkgs
$ cat sedscript
s/^ *${/&""}${/
$ find -name '*.nix' -print0 | parallel --xargs -0 sed -i -f sedscript
$ git diff --shortstat
 596 files changed, 2250 insertions(+), 2250 deletions(-)
```

So this gives 2250 modifications, which is an over-approximation because not every antiquotation starting a line is alone on its line (quite the contrary in fact...)
To give an idea of the difference here is the head of the diff :
```diff
diff --git a/doc/default.nix b/doc/default.nix
index b8dac00..0c6b829 100644
--- a/doc/default.nix
+++ b/doc/default.nix
@@ -50 +50 @@ stdenv.mkDerivation {
-      ${docbook5_xsl}/xml/xsl/docbook/xhtml/docbook.xsl \
+      ${""}${docbook5_xsl}/xml/xsl/docbook/xhtml/docbook.xsl \
diff --git a/nixos/doc/manual/default.nix b/nixos/doc/manual/default.nix
index 87964e2..fd86c9b 100644
--- a/nixos/doc/manual/default.nix
+++ b/nixos/doc/manual/default.nix
@@ -46 +46 @@ let
-    ${libxslt}/bin/xsltproc \
+    ${""}${libxslt}/bin/xsltproc \
@@ -103 +103 @@ in rec {
-      ${copySources}
+      ${""}${copySources}
@@ -127 +127 @@ in rec {
-        ${docbook5_xsl}/xml/xsl/docbook/xhtml/chunktoc.xsl ./manual.xml
+        ${""}${docbook5_xsl}/xml/xsl/docbook/xhtml/chunktoc.xsl ./manual.xml
@@ -152 +152 @@ in rec {
-      ${copySources}
+      ${""}${copySources}
[...]
```

Ok, so lets see which derivations have been modified by this hack :

```
$ ../nix/inst/bin/nix-instantiate pkgs/top-level/release.nix -A unstable
/nix/store/q2349mymbaf6l6bx0f1j7ls8aq7yk328-nixpkgs-16.03pre1234.abcdef.drv
$ nix-instantiate pkgs/top-level/release.nix -A unstable                
/nix/store/q2349mymbaf6l6bx0f1j7ls8aq7yk328-nixpkgs-16.03pre1234.abcdef.drv
$ git stash
[...] # removed effect of sedscript
$ nix-instantiate pkgs/top-level/release.nix -A unstable
/nix/store/bd1y29d75hid8vsylndfxlcydzqdkw6c-nixpkgs-16.03pre1234.abcdef.drv
```
This means that with the hack, the two nix semantics produce exactly the same derivations on the unstable tree.
However, the hack changes some derivations when applied.
Lets see what exactly is impacted :

```
$ ../nixos-scripts/nix-script-diff-generations.sh /nix/store/q2349mymbaf6l6bx0f1j7ls8aq7yk328-nixpkgs-16.03pre1234.abcdef.drv /nix/store/bd1y29d75hid8vsylndfxlcydzqdkw6c-nixpkgs-16.03pre1234.abcdef.drv
/nix/store/q2349mymbaf6l6bx0f1j7ls8aq7yk328-nixpkgs-16.03pre1234.abcdef.drv /nix/store/bd1y29d75hid8vsylndfxlcydzqdkw6c-nixpkgs-16.03pre1234.abcdef.drv
+ nixpkgs
- nixpkgs
+ nixpkgs-16.03pre1234.abcdef.drv
- nixpkgs-16.03pre1234.abcdef.drv
+ nixpkgs-lib-tests.drv
- nixpkgs-lib-tests.drv
+ nixpkgs-tarball-16.03pre1234.abcdef.drv
- nixpkgs-tarball-16.03pre1234.abcdef.drv
```

This shows that the change in the hash come from the `nixpkgs` derivation.
This means that all the derivations are the same, except for the one embedding the source code of the nixpkgs (which obviously changed because we applied the hack).

With a simple (and improvable) hack, it is possible to make the two semantics produce the same nixpkgs derivations. This means that we could safely introduce the new semantics as described above.

I will therefore update my PR with tools easing this migration.
What do you think of this idea ?

**Comment by layus** [comment]
I have added a new commit that makes this feature optional and disabled by default.
Merging this pull request as is *does not change anything*, `--option smart-antiquotations true` enables the new behaviour.

This way we could turn in on by default in some Nix version (say 1.12) and add a warning in nixpkgs in the fashion of https://github.com/NixOS/nixpkgs/blob/master/default.nix .
This is not as smooth a transition as described above, but it is simple (trivial ?) to setup, and should minimize issues.

@edolstra, @vcunat : Does this patch have any chance to be merged, or should I stop insisting ? I have done my best to provide smooth migration paths.
Is @wmertens's https://github.com/NixOS/nix/pull/580#issuecomment-120660477 the way to go ?
Should I come to NixCon to discuss it :smiley: ?

PS: The name "Smart antiquotations" may not be the wisest. I will update if you find something more expressive.

**Comment by layus** [comment]
@nbp had the nice idea to add requirements for nix options in nixkgs.
This way, new nixpkgs can require the `smart-antiquotations` option.
The default remains to disable the option, and old nipkgs still have binary cache support.

This is a perfect transition in the sense that it does not disrupt binary support, and is only minimally intrusive for nixpkgs.

In the lon term, we might even turn this option on by default.

**Comment by layus** [comment]
I have updated the patch to implement the proposal from @nbp.
Now multiline antiquotations are optional and disabled by default.

A builtin has been added to *require* them, and could be used in nixpkgs/default.nix like so:

```diff
-let requiredVersion = import ./lib/minver.nix; in
+let
+  requiredVersion = import ./lib/minver.nix;
+  forcedAntiquotations = builtins ? forceSmartAntiquotations && ! (builtins.forceSmartAntiquotations true);
+
+in
 
 if ! builtins ? nixVersion || builtins.compareVersions requiredVersion builtins.nixVersion == 1 then
 
   abort "This version of Nixpkgs requires Nix >= ${requiredVersion}, please upgrade! See https://nixos.org/wiki/How_to_update_when_Nix_is_too_old_to_evaluate_Nixpkgs"
 
 else
 
-  import ./pkgs/top-level
+  builtins.deepSeq forcedAntiquotations (import ./pkgs/top-level)
```

This way new versions of nix will still compile old nixpkgs with binary cache support, and old nix versions will be detected by the nix version check.

The only drawback is that standalone derivations will observe the old behavior until we make this option enabled by default, but they can still set the option themselves like any other option.

Would this be acceptable?

PS: The current hook syntax may need to be changed and generalized. Maybe `require "smart-antiquotations" "true"` ?

**Comment by edolstra** [comment]
Having a primop that causes a global variable to be set as a side-effect is a bad idea, because it makes the evaluation result depend on the evaluation order. For example, in
```
let 
  x = import <nixpkgs> {};
  y = import ./foo.nix
in ... x ... y ...
```
where `./foo.nix` contains a multi-line string, that string might or might not be interpreted using the new rules.

You also have to ensure that every entry point into Nixpkgs calls `forcedSmartAntiquations`. For example, https://github.com/NixOS/nixpkgs/pull/16598 covers `nixpkgs/default.nix` but not `nixpkgs/nixos/default.nix`, so during NixOS evaluation, it's possible some files get evaluated before `forcedSmartAntiquotations` is called.

Maybe we should just introduce a new type of string literal? Just pick any of https://en.wikipedia.org/wiki/Quotation_mark#Unicode_code_point_table as a delimiter...

**Comment by layus** [comment]
Okay, this *is* a dirty hack. But note however that the evaluation is deterministic/reproducible. You cannot tell what semantic will be used to parse ./foo.nix, but it will be the same on each evaluation of the same file.

The other option is to fail if the option is not present, which will force the users to provide it manually or enable it in nix.conf. This means no dirty hack, but more hassle on the users.
Good old declarative thechnique: Make the impurity explicit.
I like this idea, but I wonder if nixers would accept this? Maybe I should ask on the ML?

Regarding the new string literal, this is no better than having another antiquotation mark like @wmertens suggested in https://github.com/NixOS/nix/pull/580#issuecomment-120660477; add `${> ... }` besides `${ ... }`.
Between the two proposals, I prefer a new antiquotation mark than a new string literal.

However, I am in line with @vcunat (https://github.com/NixOS/nix/pull/580#issuecomment-120693002)
> , to me that doesn't feel like a good long-term solution.

The new semantics is an improvement and should replace the old one, not a new feature to be added beside it.
I however acknowledge that we must take the past into account, and breaking everything is not the way to go.
I am really looking at a way to make the transition smooth.

**Comment by copumpkin** [comment]
Sorry, I'm jumping in late here, but could the new-style antiquotations be scoped per-file, and we introduce a notion of "pragma comments" like many other languages have? Something like

```
/*(option smart-antiquotations true)*/
```

at the top of the file would apply the new-style antiquotations to just that file. It thus wouldn't be "global" and would be scoped sensibly. I don't care about the actual syntax, TBC. The same option could be applied more broadly on the command line.

I find:

> You cannot tell what semantic will be used to parse ./foo.nix, but it will be the same on each evaluation of the same file.

pretty unappealing 😄

**Comment by layus** [comment]
@copumpkin This is like the `forceSmartAntiquations` builtin, but scoped to a file, right ? This should be feasible, and if applied to *every* entry point, should also be seamless to the users of hydra.

Seems like the right way to go if we keep in this direction. I will try to implement this.

**Comment by copumpkin** [comment]
@layus yes, exactly. The code should be similar, but the "mysterious action at a distance" behavior that makes us uneasy about `forceSmartAntiquotations` goes away once it's reasonably scoped.

**Comment by danbst** [comment]
Also, current semantics is nice for heredocs (it places EOF handles at column 1), but with this change some of Bash scripts that use heredocs may start to fail.

**Pull request closed without merging**
