### PR TITLE
fix: `nlohmann::adl_serializer` for `std::optional`

### PR DESCRIPTION
**Pull request by aakropotkin**
# Motivation
This allows templates such as `NLOHMANN_DEFINE_TYPE_*` templates and other generators with things like `std::vector<std::optional<T>>`.

# Context
This template definition conflicts with my own definition used in a `nix` plugin.
I can use y'alls copy but since I nest `std::optional` inside of other STL containers.

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Comment by Ericson2314** [comment]
@aakropotkin Can you test that your way works for deserializing types that do not have a default constructor? It looks like it would, but nlohmann/json is very finicky about this (it has some bad old stuff for backwards compat that instead mutates a default-constructed value).

**Comment by aakropotkin** [comment]
> @aakropotkin Can you test that your way works for deserializing types that do not have a default constructor? It looks like it would, but nlohmann/json is very finicky about this (it has some bad old stuff for backwards compat that instead mutates a default-constructed value).

Yeah I have a test case in my repo I can migrate over here.

**Comment by Ericson2314** [comment]
Great, feel free to undraft once you have the tests.

**Comment by aakropotkin** [comment]
Aight - we ready

**Review by tomberek — APPROVED** [review]

**Pull request merged**
