### PR TITLE
Add aws-region param to S3 store URLs

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by shlevy** [comment]
@edolstra

**Comment by grahamc** [comment]
Usage example:

```
shlevy | gchristensen: just add ?aws-region=us-west-2 or whatever to your s3
       | store uri
shlevy | (or &aws-region= if you already have params)
```

**Comment by shlevy** [comment]
@edolstra  ping

**Comment by copumpkin** [comment]
A possible alternative to this approach: buckets almost never change region (you'd have to delete and recreate in a different region), so just have a cached `get-bucket-location` API call that we use once per bucket and expire periodically. A lot of the standard SDKs do this behind the scenes for you too; not sure if the C++ one does or has the option to.

**Pull request merged**
