### PR TITLE
Move `/src` to `/subprojects`

### PR DESCRIPTION
**Pull request by Ericson2314**
# Motivation

Get rid of the current symlink soup we have, as part of switching to Meson only.

The plan is to backport these reorgs just to 2.24, so backports of actual changes to the Nix release in Nixpkgs until 25.05 will be easy.
 
# Context

In c7ec33605e8c2dff0ebe40e4a1beba7a98530432 I had to stop using `src` as a custom subproject dir, because Meson was getting confused with `src` being a subdir of the docs dir.

This is a bug on Meson's part, but I think the simplest fix is just for us to do the rename; hence I am reopening this PR.

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by edolstra** [comment]
Why not just use "src" as the subprojects directory? Way less churn that way.

**Review by inclyc — CHANGES_REQUESTED** [review]
> (They are very opinionated about this, 

I don't think we should follow meson's opinion because semantically our `/src` directory is not "subprojects" at all.

**Comment by Ericson2314** [comment]
> I don't think we should follow meson's opinion because semantically our `/src` directory is not "subprojects" at all.

But I want to *make* it be that. It also gives us a way to port things over little by little and have smaller derivations from the get-go, which makes the conversion more productive.

**Comment by inclyc** [comment]
> But I want to make it be that. It also gives us a way to port things over little by little and have smaller derivations from the get-go, which makes the conversion more productive.

Breaking a project into multiple projects with meson does not require moving all stuff into "subprojects". Instead, there is an alternative to achieve this:

Firstly, suppose there are some source files under `projA/src/a.cpp`, `projB/src/b.cpp`, and we want to build them separately. And also it may be formed as a monorepo.

Things to do:

1. create a `meson.build` under `projA/src` and `projB/src`. Then write build scripts for it, but do not invoke `project()`
2. For separated builds, create `meson.build` files under `projA`, and `projB`.
3. For monorepo (development) builds, create a `meson.build` under top-level directory. 

> the directory must be named subprojects. Sorry.

After all I think *hardcoded* `subprojects` is a funny bad design in meson and we should *NOT* follow that.

**Comment by p01arst0rm** [comment]
> > But I want to make it be that. It also gives us a way to port things over little by little and have smaller derivations from the get-go, which makes the conversion more productive.
> 
> Breaking a project into multiple projects with meson does not require moving all stuff into "subprojects". Instead, there is an alternative to achieve this:

The motive behind this is to allow out of order includes that are required currently under the Nix code docgen process.

> Firstly, suppose there are some source files under `projA/src/a.cpp`, `projB/src/b.cpp`, and we want to build them separately. And also it may be formed as a monorepo.
> 
> Things to do:
> 
>     1. create a `meson.build` under `projA/src` and `projB/src`. Then write build scripts for it, but do not invoke `project()`
> 
>     2. For separated builds, create `meson.build` files under `projA`, and `projB`, with `project()` invoked.
> 
>     3. For monorepo (development) builds, create a `meson.build` under top-level directory + monorepo `project()` and invoke `subdir('projA/src')`, `subdir('projB/src')`.

This breaks the meson spec.

> > the directory must be named subprojects. Sorry.
> After all I think _hardcoded_ `subprojects` is a funny bad design in meson and we should _NOT_ follow that.

The subprojects directory is created for a reason to force meson code to not index or modify data inside it with subdir()

> As per my understanding, [meson documentation](https://mesonbuild.com/Subprojects) says
> 
> > Some platforms do not provide a native packaging system. In these cases it is common to bundle all third party libraries in your source tree. This is usually frowned upon because it makes it hard to add these kinds of projects into e.g. those Linux distributions that forbid bundled libraries.
> 
> Frankly this project is a "packaging system". Meson authors may designed to use `subprojects` as an ungly workaround to bundle all dependencies. I think things under `/src` is not our _dependencies_, right? IMHO, we are nix, the most advanced package manager, we should handle things elegantly.

`/src` currently includes vendored code, which breaks the spec. it also references files outside of itself out of order, which also breaks the spec.

**Comment by p01arst0rm** [comment]
@inclyc see https://github.com/mesonbuild/meson/issues/6404

@eli-schwartz may also be able to weigh in

**Comment by eli-schwartz** [comment]
Meson explicitly allows you to use whatever subprojects directory you wish. 

Doing so requires defining the subprojects_dir in your project declaration, and also means you cannot use that directory for non subprojects.

Subprojects aren't just directories of source code. They are sandboxed from each other, and accessing the contents of a subproject needs to be done via the subproject exporting an interface (override find_program, override dependency). Subprojects have their own names. They have their own version numbers. You can build them standalone. You can release them separately and upload release tarballs of just the subproject.

In short, subprojects are in fact their own derivations.

Meson isn't opinionated about whether they are their own derivations because you vendored a third-party project or because you develop both of them in one repository. It is simply opinionated about the fact that if you want to treat them as their own derivations, then they are in fact separate derivations and need to e.g. be sandboxed that way.

> This will facilitate breaking up Nix into multiple packages for each component with Meson.

It is a project specific decision whether that project wishes to be able to release its code as multiple derivations.

> I don't think we should follow meson's opinion because semantically our `/src` directory is not "subprojects" at all.

... then you are at odds with the motivation of this PR, which was to make your src directory into multiple derivations.

If parts of nix are split out into their own derivations then they are, per definition, a subproject.

**Comment by p01arst0rm** [comment]
even if we didnt call it `subprojects`, it would still be more semantically accurate to call the folder `Nix` or `cppnix`, because the directory does not contain only source filles. having directory structes such as `/src/libutil/tests/..` `/src/libutil/src/..` isnt very clear and leaves the door open to a confusing codebase

**Comment by Ericson2314** [comment]
Thanks @eli-schwartz, that matches my understanding, except I didn't know about `subprojects_dir`!

**Comment by eli-schwartz** [comment]
Overriding the name of the subprojects directory was in fact added as a feature specifically because it allows people with existing code in e.g. a third-party/ directory to avoid the churn of moving files around. :D

This does assume that your choice of subprojects directory does itself consist of e.g. third-party/zlib/ rather than yeeting all your source files directly into third-party/*.c

Or as noted, 

> Why not just use "src" as the subprojects directory? Way less churn that way.

**Comment by Ericson2314** [comment]
Closed because #10855 uses `src` as the subproject directory now, and so this is not needed :).

**Comment by eli-schwartz** [comment]
The good news is if you ever decide to rename it to cppnix/ after all, you can just move it and all the work you're about to do, just magically still works. :)

Since it's a subproject and looked up by name, you don't even need to update file contents to match the rename (other than changing the subprojects_dir at the top level).

**Comment by inclyc** [comment]
I thinthis.'s definitely acceptable to have #10855, just kindly ask @eli-schwartz 


>Meson isn't opinionated about whether they are their own derivations because you vendored a third-party project or because you develop both of them in one repository. It is simply opinionated about the fact that if you want to treat them as their own derivations, then they are in fact separate derivations and need to e.g. be sandboxed that way.

Does this mean vendored third-party projects vendored code and 'our own codes' but separated derivations, these two kinds of code directory, should be treated as the same thing in meson?

I'm a little confused about this because they are actually different. For the second case (separated derivations), we may have some unstable API/ABI in the project thus it must be built in a monorepo.

But for the first case, (vendored 3rd-party codes) we do expect it have some stable interface (right?)

Is there some approach to clearly keep the semantics? Not just specifying one `subproject_dir`?

**Comment by eli-schwartz** [comment]
- a subproject can also have its own subprojects (meson will process the subprojects on a first-come first-served basis to avoid diamond dependencies)
- a subproject can be a small INI file called zlib.wrap, which means the zlib source code isn't actually checked into your codebase but is downloaded on the fly, on demand, when zlib isn't available as a system package (or derivation, if you like). (The environment `$MESON_PACKAGE_CACHE_DIR` can be used to provide offline tarball sources, to avoid breaking a network sandbox.) This means it doesn't clutter things up by default.

**Comment by fricklerhandwerk** [comment]
Tracking https://github.com/NixOS/nix/issues/2503

**Comment by p01arst0rm** [comment]
> > This means it doesn't clutter things up by default.
> 
> Could you elaborate how to handle llvm structure(https://github.com/llvm/llvm-project) i.e.
> 
> clang, llvm, as subprojects and llvm depedency, zlib?
> 
> As per my understanding currently we must move all sources into `subproject_dir`, right?
> 
> > Is there some approach to clearly keep the semantics?
> 
> To clarify, my question is how to put **things we want to build separately + with a monorepo style for ABI reason** and **things vendored from 3rd party** in different dirs.

no, we technically dont *have* to  put *all* code into the subproject dir, but we should put code relating to each library into the subdir related to that library. the end goal is to remove all vendored code anyway :),

**Comment by Ericson2314** [comment]
In c7ec33605e8c2dff0ebe40e4a1beba7a98530432 I had to stop using `src` as a custom subproject dir, because Meson was getting confused with `src` being a subdir of the docs dir.

This is kinda of a bug on Meson's part, but I think the simplest fix is just for us to do the rename; hence I am reopening this PR.

**Review by fricklerhandwerk — APPROVED** [review]

**Review by edolstra — CHANGES_REQUESTED** [review]
I really don't want to move *everything* around just to placate the build system.

Apart from invalidating 20 years of muscle memory about where files reside, this makes every patch/backport harder, probably causes issues for numerous existing PRs, etc. Let's just not.

**Comment by Ericson2314** [comment]
https://github.com/mesonbuild/meson/issues/13774 is the meson bug btw

**Pull request closed without merging**
