### PR TITLE
[backport 2.18-maintenance] AttrCursor: Remove forceErrors

### LINKED ISSUE #3872: Nix flakes should not cache evaluation errors
**Describe the bug**

Currently error messages are only showed the first time they appear.
After that the error message looks like this:

```
$ sudo nixos-rebuild switch
building the system configuration...
error: --- EvalError -------------------------------------------------------------------------- nix
cached failure of attribute 'nixosConfigurations.turingmachine.config.system.build.toplevel.drvPath'
````

The problem is that the error message of the first time might be no longer visible,
so users would get stuck not knowing what its going on. 

**Steps To Reproduce**

1. Create an invalid nixos configuration i.e. add two conflicting options (but valid nix syntax)
2. Run `nixos-rebuild switch`:

```
error: --- ThrownError --------------------------------------------------------------------------- nix
The option `system.nixos.versionSuffix' has conflicting definitions, in `<unknown-file>' and `<unknown-file>'.
(use '--show-trace' to show detailed location information)
```

2. Run `nixos-rebuild switch` again:

```
building the system configuration...
error: --- EvalError -------------------------------------------------------------------------- nix
cached failure of attribute 'nixosConfigurations.turingmachine.config.system.build.toplevel.drvPath'
```

**Expected behavior**

It should not cache evaluation failures and show me the message agin

**`nix-env --version` output**

```console
$ nix-env --version
nix-env (Nix) 2.4pre20200721_ff314f1
```

### PR DESCRIPTION
**Pull request by eclairevoyant**
# Motivation

backport of #10564

# Context

fixes #3872 for those on nix 2.18

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by eclairevoyant** [comment]
`state` is defined in `eval-cache.hh` but not visible in `eval-cache.cc`, idk what do

**Review by edolstra — APPROVED** [review]

**Comment by roberth** [comment]
**CI / installer (push)** failure can be ignored. I'll try to backport its fix, but it's not a blocker afaic.

**Comment by eclairevoyant** [comment]
Tested locally as well, seems to avoid the cached failure as expected.

**Comment by roberth** [comment]
Thanks!

**Pull request merged**
