### PR TITLE
remove builtins.exec

### PR DESCRIPTION
**Pull request by andir**
IMO that feature is very dangerous to have in Nix and probably doesn't fit the entire model at all.

It currently isn't documented so there shouldn't be many users. Those that need it can probably add this via a plugin. The plugin example (`tests/plugins/plugintest.c`) already shows how to add such a plugin and the removed code can probably just pasted into that file to get started.

### CODE REVIEW

**Comment by shlevy** [comment]
builtins.exec is already hidden behind a very verbose flag, and allows for a much nicer extension experience without any native code. What is the concern?

**Comment by grahamc** [comment]
People see `builtins.exec` and think "ooooh!", and then nearly nothing persuades them against it.

**Comment by shlevy** [comment]
Are there real examples of people shooting themselves in the foot or failing to do things the right way due to this?

**Comment by flokli** [comment]
It's a massive opportunity to shoot yourself in the foot.

It's undocumented, https://github.com/NixOS/nix/commit/0bb8db257d98a32abde759f4d07d28b5178bd3bf mentioned it was meant as an intermediate thing, so I think if people want it, moving it to an optional plugin would be the right move.

**Comment by zimbatm** [comment]
Would removing it solve a actual current problem? This provides an escape hatch to do funny and crazy things. It's properly protected behind a scary flag.

**Comment by edolstra** [comment]
Closing since it doesn't really harm anybody as it's hidden behind a flag.

**Comment by Ericson2314** [comment]
I would put this behind an experimental feature.

**Pull request closed without merging**
