### PR TITLE
istringstream_nocopy: Implement in a standards-compliant way.

### PR DESCRIPTION
**Pull request by shlevy**
Fixes the problem mentioned in e6a61b8da788efbbbb0eb690c49434b6b5fc9741

See #1135

### CODE REVIEW

**Comment by shlevy** [comment]
s3 access doesn't seem to completely work on darwin yet, but this gets further...

**Comment by shlevy** [comment]
And anyway on linux the current code is broken against libc++

**Comment by shlevy** [comment]
@edolstra @copumpkin

**Comment by edolstra** [comment]
That's a lot of code for a little performance optimization :-(

**Comment by shlevy** [comment]
C++ streams considered verbose :frowning:

**Comment by copumpkin** [comment]
Do we really need the full stream interface? Agree that it's awkwardly verbose but if we're using them in a non-standards compliant manner, they kind of work "by accident" and could break with future updates.

**Comment by shlevy** [comment]
If it helps, a lot of the verbosity is just boilerplate :tongue:

**Comment by shlevy** [comment]
@edolstra ping

**Comment by shlevy** [comment]
@edolstra Do we want to merge this, drop the optimization all together, or drop S3 support on libc++ based builds?

**Pull request merged**
