### PR TITLE
Revert "Add support for building JARs from Java sources"

### PR DESCRIPTION
**Pull request by puckipedia**
The code has been here since 2013, but seems to have gone unused all this time.

### CODE REVIEW

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
The makefile support used to be shared with other projects. I suspect that's how it got in here.

**Comment by puckipedia** [comment]
Interesting. I looked around a bit and all I could find were forks of Nix sharing the same approximate makefile structure.

**Comment by Ericson2314** [comment]
Perhaps this was just internally at LogicBox. Any any event I was just repeating @edolstra told me.

**Comment by edolstra** [comment]
Yes, it was used internally at LogicBlox. The `mk` directory was included (with history) from https://github.com/edolstra/make-rules/. But since that's archived we can get rid of the unnecessary stuff.

**Pull request merged**
