### PR TITLE
Allow throwing and catching arbitrary (string-coercible) values

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by domenkozar** [comment]
@shlevy can you show an example how this works?

**Comment by shlevy** [comment]
@domenkozar See the updated test

**Comment by edolstra** [comment]
This is problematic in a purely functional language because it makes the evaluation result dependent on the evaluation order (e.g. `tryEval ... (throw "foo" + throw "bar")` would produce a different result depending on whether the left-hand or right-hand argument to `+` is evaluated first).

Also, blackholing will prevent a second evaluation from throwing the same value.

**Comment by shlevy** [comment]
@edolstra Can you propose an alternative solution to #7830 then?

**Comment by shlevy** [comment]
erm, NixOS/nixpkgs#7830

**Comment by copumpkin** [comment]
Why not take the usual Haskell approach and create a primop called `reallyUnsafeTryEval` to scare people away from using it? That one can have the semantics @shlevy is introducing here, whereas the normal `tryEval` retains the old semantics.

**Comment by domenkozar** [comment]
We really need this in nixpkgs, so if it's unsafe to be used, it better not exists for that matter.

**Comment by shlevy** [comment]
@domenkozar I don't understand your comment.

**Comment by shlevy** [comment]
Note that hydra already prints thrown messages, which have the same issue @edolstra mentioned. At least this way hydra can make decisions about classes of errors to ignore.

**Comment by copumpkin** [comment]
It's only unsafe in that it's leaks information about evaluation order and could lead to unexpected evaluation behavior. It seems fine to me to put it into Nix and let it be used by people who know what they're doing.

**Comment by domenkozar** [comment]
@shlevy calling it `reallyUnsafeTryEval` won't help, since then we should discourage use in `nixpkgs`, but that's the whole purpose of this feature.

**Comment by copumpkin** [comment]
I thought the `reallyUnsafeTryEval` would be wrapping the entire evaluation, and only used in one or two places at most...

**Comment by shlevy** [comment]
Still don't see a better solution to NixOS/nixpkgs#7830 but closing this as it's not wanted.

**Comment by copumpkin** [comment]
@edolstra @shlevy I see very little downside in exposing this behind a scary-sounding primop. We already have things like `__unsafeGetAttrPos` and `__currentTime`, and this doesn't seem fundamentally less pure than those or other ones I didn't include.

If we just mark the use site in nixpkgs with a comment saying, "this is only safe in very limited situations. Please do not use it unless you talk to @edolstra or @shlevy", I don't see the problem.

**Pull request closed without merging**
