### PR TITLE
FreeBSD support with knowledge about Linux emulation

### PR DESCRIPTION
**Pull request by ysangkok**
This is just the build fixes of #657 with the additional canBuildLocally patch to ensure that Nix knows it can build i686 Linux binaries even if it is a FreeBSD machine. Linux emulation does not work for 64-bit binaries, so this is not enabled.

### CODE REVIEW

**Comment by Ericson2314** [comment]
Hmm, someone should try with with branded zones on Illumos.

**Comment by vizanto** [comment]
@Ericson2314 an `lx` branded zone presents itself as Linux :)
I have a SmartOS image 90% ready, just needs to be published to datasets.at

**Comment by Ericson2314** [comment]
@vizanto Sure one can do run everything on an lx branded zone (and good job doing that BTW!), but I meant have Nix running "natively" and build both illumos and Linux binaries (and spin up lx branded zones for building the latter I suppose).

That's more work than this patch alone of course.

**Comment by vizanto** [comment]
Yes, indeed is is @Ericson2314 https://github.com/NixOS/nixpkgs/pull/11067

**Comment by Ericson2314** [comment]
Oh wow, that's wonderful! Mmm I think one would use lx-branded zones. Now that our build-sandboxing support has been generalized to work for Linux and Darwin, hopefully it wouldn't be too hard to make it understand zones on Illumos.

**Comment by ysangkok** [comment]
@edolstra I believe we decided at the NixCon that this is ready to merge. [patchelf issue 36](https://github.com/NixOS/patchelf/issues/36) still applies though.

**Comment by edolstra** [comment]
Thanks, merged!

**Comment by vcunat** [comment]
Hey, FreeBSD users, does #55 still apply? (I unfortunately don't have elevated rights in this repo, so I would be unable to close it myself.)

**Pull request merged**
