### PR TITLE
pathExists: isDir when endswith /.

### LINKED ISSUE #8838: Regression in `builtins.pathExists`
**Describe the bug**

After Nix 2.13.3 something happened and broke `builtins.pathExists` behaviour.

**Steps To Reproduce**

1. `touch /tmp/test`
2. `nix repl`
4. `builtins.pathExists /tmp/test/.`
It will return `true`, should be `false`.

**Expected behavior**
It should return false.

**`nix-env --version` output**
nix-env (Nix) 2.17.0

**Additional context**
Nix 2.13.3 (tested on `/nix/store/nd8dpdgpjkh3g3vvcjx9qdw7mjzz0l90-nix-2.13.3/bin/nix`) doesn't have this issue.

This bug breaks impure overlays in nixpkgs. Relevant part of the code: https://github.com/NixOS/nixpkgs/blob/d28fdbe9742c680ec410bd70bf2962b90a374d36/pkgs/top-level/impure.nix#L40C1-L41C1

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by roberth**
# Motivation

- Fixes #8838

The more complicated cases with `..` and such were already handled correctly, so most of the extra test cases already worked.

# Context

- Supplements https://github.com/NixOS/nix/pull/8869

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Review by infinisil — APPROVED** [review]
:100:

**Comment by Ericson2314** [comment]
I might make the test case a list so we can see individual failures?

**Comment by roberth** [comment]
@Ericson2314 would be nice to have a standard solution for this, but did it by hand this time, as I was able to reproduce the problem locally.

Seems like either I messed up when I wrote this before NixCon or something happened in the meanwhile. Anyway, the problem is that Nix appears to canonicalize the path without checking that all components actually resolve to something that exists.

**Comment by roberth** [comment]
> canonicalize the path without checking that all components actually resolve to something that exists.

This is perhaps a better way to implement this function anyway. Check each path component, and check that it's a directory unless it's the last component.

**Comment by Ericson2314** [comment]
Not sure what you mean, but can do the list later.

**Pull request merged**
