### PR TITLE
Propagate path context via builtins.readFile

### PR DESCRIPTION
**Pull request by abbradar**
Fixes https://github.com/NixOS/nix/issues/833

### CODE REVIEW

**Comment by abbradar** [comment]
Any comments on this? This seems very nasty to me since it provides a way to bypass Nix context tracking, with a real-world example of breakage.

**Comment by copumpkin** [comment]
cc @edolstra @shlevy

**Comment by shlevy** [comment]
This seems wrong to me. Why should the contents of a file depend on the file itself?

**Comment by abbradar** [comment]
Hm, I don't understand a question, sorry. What happens is if we have a file which depends on some other things, reading it to a string would discard this information. See my example in #833. Notice again that I'm a complete novice in Nix codebase so there're pretty good chances I've understood and fixed it the wrong way!

**Comment by shlevy** [comment]
I guess my objection is that this is over-eager in keeping dependencies. But upon reflection this probably won't matter, as those dependencies won't be retained in any final form unless a derivation actually refers to them. So never mind, :+1: from me, I'll give @edolstra some time to double check but I think this should go in.

**Comment by abbradar** [comment]
Oh, I got your earlier question! Sorry, language problems. Yes, I think they wouldn't be retained. On the other hand this might introduce some slowdowns, but I don't think we use `readFile` extensively.

**Pull request merged**
