### PR TITLE
Link to `builders-use-substitutes` in chapter on distributed builds

### LINKED ISSUE #2730: Mention builders-use-substitutes in Chapter “Remote Builds”
I was setting up a builder according to https://nixos.org/nix/manual/#chap-distributed-builds  and it would have been very useful to learn about the `builders-use-substitutes` setting here.

### PR DESCRIPTION
**Pull request by nomeata**
fixes #2730.

### CODE REVIEW

**Comment by srhb** [comment]
Maybe also describe that without this setting, the master will push substitutes to the builder instead?

**Comment by nomeata** [comment]
Well, I did not want to duplicate information from the referenced section of the manual, and hence I just link to it.

**Comment by srhb** [comment]
OK! :)

**Comment by edolstra** [comment]
Thanks!

**Pull request merged**
