### PR TITLE
Norc for pure env

### PR DESCRIPTION
**Pull request by zimbatm**
What would you think of these changes ?

Just looking for feedback at this stage as I haven't figured-out how to test these changes yet.

### CODE REVIEW

**Comment by rrnewton** [comment]
+1

**Comment by danbst** [comment]
+1. My current workaround is

```
# .bashrc
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
if [[ -z "$IN_NIX_SHELL" ]]; then
    cd /usr/local/ec2
    ... other logic
fi
```

**Comment by zimbatm** [comment]
My workaround is the reverse, my .bashrc looks like:
```
# If not running interactively, don't do anything
if [[ -z "$PS1" ]]; then return; fi
if [[ -n $IN_NIX_SHELL ]]; then return; fi

# usual code here
#...
```

**Comment by deepfire** [comment]
+1

**Comment by deepfire** [comment]
@zimbatm, should the list be pinged about this? AIUI, the issue is as live as ever..

**Comment by zimbatm** [comment]
Oops, I removed the branch by mistake and it auto-closed the associated PR.

**Comment by zimbatm** [comment]
Yes I would still like this to be implemented but don't know what the next steps are.

**Comment by deepfire** [comment]
@zimbatm, discussion, discussion, discussion!  Ping the list, if the set of people participating here is insufficient -- and it seems that it isn't.

**Comment by zimbatm** [comment]
Feel free to take that over. I'm already juggling with too many things at the moment.

**Comment by zimbatm** [comment]
Once https://github.com/NixOS/nix/pull/1152 goes through it will also make it easier to validate PR functionalities

**Comment by danbst** [comment]
Actually, what is the state of issue in Nix 1.12? The current Perl script won't be used in future I guess

**Comment by zimbatm** [comment]
Closing as the PR is out of date

**Pull request closed without merging**
