### PR TITLE
Add another missing #include

### PR DESCRIPTION
**Pull request by Ericson2314**
Waiting for CI to make sure I catch everything.

### CODE REVIEW

**Comment by edolstra** [comment]
Note that the Hydra `coverage` job builds with precompiled headers disabled, so it should catch this.

**Comment by Ericson2314** [comment]
I think the GitHub CI does too, in which case the issue must be something like master changing from when the CI was run.

**Comment by Ericson2314** [comment]
I removed the WIP from this in any case, now that I verified the coverage job myself.

**Comment by edolstra** [comment]
Maybe it would be better to just disable precompiled headers in the regular job. Running coverage just for that would be a bit expensive.

**Comment by Ericson2314** [comment]
I'll look into that, then.

**Pull request merged**
