### PR TITLE
Replace src/libutil/json.cc with nlohmann

### PR DESCRIPTION
**Pull request by yorickvP**
Spinoff from https://github.com/NixOS/nix/pull/7249

Currently, nix uses two different ways to generate json strings. They collide at one point in `ParsedDerivation::prepareStructuredAttrs`. This PR removes the old code and changes everything to use nlohmann.

A side effect of this is that objects keys are now ordered alphabetically everywhere and that `NIX_SHOW_SYMBOLS` no longer prints a duplicate "symbols" key. It is possible to keep the original ordering where this is desired, but I'm not sure where that's the case.

### CODE REVIEW

**Comment by yorickvP** [comment]
cc @edolstra

**Comment by edolstra** [comment]
This makes the output of commands like `nix-env -qa --json` non-streaming right? I.e. it builds the entire `nlohmann::json` tree in memory before writing it to stdout. Not sure if anybody cares about the streaming behaviour though...

**Comment by thufschmitt** [comment]
> Not sure if anybody cares about the streaming behaviour though...

I would say that it's OK to drop it since:
- In the very worst case it's “only” a performance regression for the consumers and doesn't really change the behaviour;
- If it happens to really be a blocker for someone, we can always restore it by manually writing the top-level JSON structure and letting `nlohmann-json` handle the formatting of the inner objects;
- I find that streaming JSON is always a bit clunky because the format isn't really designed for that. So if we need that in the long term we could gain from switching to something like [jsonlines](https://jsonlines.org/) (just a fancy name for a stream of newline-delimited JSON objects) or similar.

The only worry I have regarding the loss of the streaming behaviour is that building the entire object in memory could be expensive. But I expect that's generally not meaningful compared to the memory used for the evaluation.

**Comment by srhb** [comment]
This changed the representation of `builtins.toJSON 1.000001` from `"1"` to `"1.000001"` -- was that intentional? I couldn't find anything in the changelog while debugging some scary changes locally, though I might be missing something.

**Pull request merged**
