### PR TITLE
libfetchers/github: allow slashes in refs

### PR DESCRIPTION
**Pull request by Ma27**
Refs #4061

### CODE REVIEW

**Comment by Ma27** [comment]
@edolstra in #4061 you stated that this is probably not a good idea due to its ambiguity. As an alternative to this patch, would it make sense to improve the error to explicitly mention the workaround? Just having an `invalid URL`-error in that case is probably kinda confusing.

**Comment by Ma27** [comment]
@edolstra may I ask what's your opinion re my previous comment?

**Comment by AluisioASG** [comment]
If you keep only the regex change, does it work for the `?ref=` case? That doesn't seem as ambiguous to me.

**Comment by Ma27** [comment]
Seems fine as well. @edolstra wdyt?

**Comment by Ma27** [comment]
cc @edolstra how shall we proceed here?

**Comment by edolstra** [comment]
Thanks. I was worried that it might introduce ambiguities in the other fetchers but that appears not to be the case.

**Pull request merged**
