### PR TITLE
Add Store nesting to fix import-from-derivation within filterSource

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by edolstra** [comment]
Isn't it easier to add the `inc/decCapacity` call to `RemoteStore::addToStore()`? That would remove the need for the `Nest` class and changes to the `Store` API.

**Comment by shlevy** [comment]
If we're sure we're not going to need to do this elsewhere, sure.

**Comment by shlevy** [comment]
@edolstra updated

**Comment by copumpkin** [comment]
@shlevy out of curiosity, how else might it be used? This feels vaguely in the direction of the stratification/recursive Nix stuff, so if we can enable that sort of thing little by little, it feels nice.

**Comment by shlevy** [comment]
Nah, it wouldn't really be useful toward that case. It's really just about working around protocols that don't naturally nest.

**Pull request merged**
