### PR TITLE
[bugfix] lib.concatMap and lib.mapAttrs to be builtins

### PR DESCRIPTION
**Pull request by volth**
#2273 has been accepted too quickly even before 2 bugs have been found
This is the fix

### CODE REVIEW

**Comment by volth** [comment]
#### Memory saving is approx 10% on Nix ```2.0.4``` with https://github.com/NixOS/nix/pull/2273 https://github.com/NixOS/nix/pull/2275  https://github.com/NixOS/nixpkgs/pull/43064:

###### One system closure

| Before | After |
| --- | --- |
|  time elapsed: 15.9831                              | time elapsed: 16.0895                             | 
|  size of a value: 24                                | size of a value: 24                               | 
|  size of an attr: 24                                | size of an attr: 24                               | 
|  environments allocated count: 18,459,190           | environments allocated count: 17,490,166          | 
|  environments allocated bytes: 466,858,472          | environments allocated bytes: 443,746,520         | 
|  list elements count: 13,972,844                    | list elements count: 9,243,013                    | 
|  list elements bytes: 111,782,752                   | list elements bytes: 73,944,104                   |   
|  list concatenations: 327,640                       | list concatenations: 122,363                      | 
|  values allocated count: 34,910,620                 | values allocated count: 30,236,233                | 
|  values allocated bytes: 837,854,880                | values allocated bytes: 725,669,592               |   
|  sets allocated: 5,377,043 (692,049,136 bytes)      | sets allocated: 4,839,804 (663,237,072 bytes)     | 
|  right-biased unions: 420,688                       | right-biased unions: 425,404                      | 
|  values copied in right-biased unions: 13,971,699   | values copied in right-biased unions: 14,024,754  | 
|  symbols in symbol table: 86,559                    | symbols in symbol table: 86,570                   | 
|  size of symbol table: 2,919,945                    | size of symbol table: 2,923,641                   | 
|  number of thunks: 19,898,177                       | number of thunks: 18,377,462                      | 
|  number of thunks avoided: 13,940,941               | number of thunks avoided: 12,665,810              | 
|  number of attr lookups: 12,438,010                 | number of attr lookups: 12,332,589                | 
|  number of primop calls: 7,204,662                  | number of primop calls: 6,555,888                 | 
|  number of function calls: 17,210,147               | number of function calls: 16,238,372              |   
|  total allocations: 2,108,545,240 bytes             | total allocations: 1,906,597,288 bytes            | 
|  current Boehm heap size: 1,543,766,016 bytes       | current Boehm heap size: 1,518,600,192 bytes      | 
|  total Boehm heap allocations: 2,607,315,312 bytes  | total Boehm heap allocations: 2,361,426,752 bytes | 

###### nixops setup of 12 system closures 

| Before | After |
| --- | --- |
|  time elapsed: 74.7571                              | time elapsed: 64.5362                             | 
|  size of a value: 24                                | size of a value: 24                               | 
|  size of an attr: 24                                | size of an attr: 24                               | 
|  environments allocated count: 64,641,227           | environments allocated count: 61,843,063          | 
|  environments allocated bytes: 1,666,749,352        | environments allocated bytes: 1,599,742,088       | 
|  list elements count: 43,111,482                    | list elements count: 21,787,256                   | 
|  list elements bytes: 344,891,856                   | list elements bytes: 174,298,048                  | 
|  list concatenations: 1,641,185                     | list concatenations: 792,607                      | 
|  values allocated count: 109,189,364                | values allocated count: 87,237,875                | 
|  values allocated bytes: 2,620,544,736              | values allocated bytes: 2,093,709,000             | 
|  sets allocated: 13,099,161 (3,344,256,456 bytes)   | sets allocated: 11,960,852 (3,281,820,112 bytes)  | 
|  right-biased unions: 2,343,608                     | right-biased unions: 2,348,456                    | 
|  values copied in right-biased unions: 99,586,284   | values copied in right-biased unions: 99,640,824  | 
|  symbols in symbol table: 86,587                    | symbols in symbol table: 86,598                   | 
|  size of symbol table: 2,921,166                    | size of symbol table: 2,924,862                   | 
|  number of thunks: 61,496,455                       | number of thunks: 58,072,316                      | 
|  number of thunks avoided: 47,738,650               | number of thunks avoided: 44,149,857              | 
|  number of attr lookups: 48,875,080                 | number of attr lookups: 48,531,709                | 
|  number of primop calls: 21,716,529                 | number of primop calls: 20,191,611                | 
|  number of function calls: 60,023,419               | number of function calls: 57,222,427              | 
|  total allocations: 7,976,442,400 bytes             | total allocations: 7,149,569,248 bytes            | 
|  current Boehm heap size: 5,765,070,848 bytes       | current Boehm heap size: 5,789,188,096 bytes      | 
|  total Boehm heap allocations: 9,633,403,856 bytes  | total Boehm heap allocations: 8,605,267,024 bytes |

**Comment by dtzWill** [comment]
FWIW even with these fixes I'm seeing "infinite recursion" (which doesn't appear otherwise):

This is using latest (hydra-built Nix](https://hydra.nixos.org/build/77047317#tabs-details):
```console
$ nix run /nix/store/kvh6dclvwxlx255kavd0by5ygfxqrrvn-nix-2.1pre6317_f1f4c257 -c time -v nix-instantiate --eval --strict --show-trace '<testpkgs/maintainers/scripts/eval-release.nix>' -I testpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz -vv
```

Last big of output is this:
```plain
evaluating file '/nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/pkgs/development/idris-modules/default.nix'
error: while evaluating the attribute 'idrisPackages' at undefined position:
while evaluating anonymous function at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/maintainers/scripts/eval-release.nix:21:25, called from undefined position:
while evaluating anonymous function at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/maintainers/scripts/eval-release.nix:7:76, called from /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/maintainers/scripts/eval-release.nix:21:56:
while evaluating 'recurse' at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/maintainers/scripts/eval-release.nix:13:19, called from /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/maintainers/scripts/eval-release.nix:21:69:
while evaluating 'g' at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/lib/attrsets.nix:267:19, called from undefined position:
while evaluating anonymous function at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/pkgs/top-level/release-lib.nix:121:38, called from undefined position:
while evaluating 'isDerivation' at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/lib/attrsets.nix:296:18, called from /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/pkgs/top-level/release-lib.nix:123:10:
while evaluating 'callPackageWith' at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/lib/customisation.nix:113:35, called from /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/pkgs/top-level/all-packages.nix:6618:19:
while evaluating 'makeOverridable' at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/lib/customisation.nix:72:24, called from /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/lib/customisation.nix:117:8:
while evaluating anonymous function at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/pkgs/development/idris-modules/default.nix:1:1, called from /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/lib/customisation.nix:74:12:
while evaluating 'fix'' at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/lib/fixed-points.nix:25:10, called from /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/pkgs/development/idris-modules/default.nix:213:4:
while evaluating 'extends' at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/lib/fixed-points.nix:44:24, called from /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/lib/fixed-points.nix:25:21:
while evaluating 'idrisPackages' at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/pkgs/development/idris-modules/default.nix:11:19, called from /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/lib/fixed-points.nix:44:42:
infinite recursion encountered, at /nix/store/qrwzd9l4zw0809mjymd45mmdah92m9zr-master.tar.gz/pkgs/development/idris-modules/default.nix:16:35
Command exited with non-zero status 1
```

Are you/others seeing this/able to reproduce?

**Comment by volth** [comment]
@dtzWill problem confirmed, will fix soon

**Comment by volth** [comment]
@dtzWill fixed. BTW, ```<testpkgs/maintainers/scripts/eval-release.nix>``` is very nice for benchmarks, [memory saving](https://github.com/NixOS/nix/pull/2278#issuecomment-403159778) is even more impressive than with a single system closure :)

**Comment by dtzWill** [comment]
Haha yeah it's the underlying expression used by the tarball job (https://github.com/NixOS/nixpkgs/issues/43015) which is why I had it handy for testing such things :D.

Thanks for the quick fix, and glad it helps bechmarking! :)

**Pull request merged**
