### PR TITLE
distributed-builds: add link to source

### PR DESCRIPTION
**Pull request by asymmetric**
To point to additional arguments that can be passed as part of the store URI.

### CODE REVIEW

**Comment by edolstra** [comment]
Hm, I feel that telling people to read the source code is far from ideal...

**Comment by thufschmitt** [comment]
There’s actually a `nix describe-stores` command that shows these arguments in a (very marginally atm, but it coud be greatly improved) nicer way, maybe you could suggest that instead

**Comment by thufschmitt** [comment]
> Can the manual link to experimental commands though?

That's a good point, it wouldn't be wise indeed :)

> @thufschmitt the output of that command is.. interesting :)

The initial intent for that command was to use it in the build process to generate part of the documentation (like `__dump_builtins`). It never made it to that point – hence the half-baked markdown output and the fact that it's not documented – but if you feel like completing it that would be ideal

**Comment by asymmetric** [comment]
@thufschmitt 

> but if you feel like completing it that would be ideal

I will look into that :) 

But that won't be a solution for the issue in this PR, so what should we do about that? Is a link to the source sufficient for now?

**Comment by fricklerhandwerk** [comment]
@asymmetric here is an apt [comment on the subject of linking to source code by @roberth](https://github.com/NixOS/nixpkgs/issues/184982#issuecomment-1203718560). In this case I agree with @roberth that we should instead write down what there is instead of linking to the source.

**Comment by asymmetric** [comment]
> we should instead write down what there is instead of linking to the source.

@fricklerhandwerk sure, that would be better. But in the meantime, doesn't this improve the status quo?

There's no harm in merging this and then replacing it with proper documentation IMO.

**Comment by fricklerhandwerk** [comment]
I think writing down even part of those options should not take more time than discussing, and would prefer to set better examples instead of creating precedent.

**Comment by asymmetric** [comment]
OK, closing this then :)

**Pull request closed without merging**
