### PR TITLE
build: add nsswitch.conf chroot

### PR DESCRIPTION
**Pull request by disassembler**
This adds nsswitch to chroot with only hosts mapping to files.

### CODE REVIEW

**Comment by edolstra** [comment]
Seems fine, but what is the motivation/effect? Will looking up `localhost` still work?

**Comment by cleverca22** [comment]
also, other tests fail due to a missing `/etc/protocols` leading to them not knowing what tcp is, so they cant create a tcp socket

**Comment by cleverca22** [comment]
i also just had a thought, nix.conf can inject paths like /bin/sh into the sandbox, maybe it can get these files also?

**Comment by cleverca22** [comment]
i can confirm that `nix.sandboxPaths = [ "/etc/nsswitch.conf" "/etc/protocols" ];` fixes both issues, the PR is no longer required

**Comment by disassembler** [comment]
Should I close this since `nix.sandboxPaths` solves the issue? The initial reason was running a multi-node cluster integration test, in which the application was dependent on nsswitch.conf to lookup localhost properly so the nodes would trust each other.

**Comment by domenkozar** [comment]
see https://github.com/NixOS/nix/issues/1238

**Pull request closed without merging**
