### PR TITLE
nix copy: Add --profile and --out-link flags

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

This allows `nix copy` to atomically copy a store path and point a profile to it, without the risk that the store path might be GC'ed in between. This is useful for instance when deploying a new NixOS system profile from a remote store.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Review by fricklerhandwerk — COMMENTED** [review]
Needs release notes and some way to document *in the command reference* that this will exhibit the behavior outlined in the PR description. Right now `--profile` just says "The profile to operate on", and that will show on every command that uses the mixin - not very informative.

The cheap way to add the relevant docs for this command is adding an appropriate blurb to the new example. Ideally though we'd have a way to annotate what a flag, which enabled by a mixin, *means* for each command that uses it. Probably overkill, but mixins seem to add a set of possible behaviors, so we'd need to describe which behaviors are used how.

**Comment by edolstra** [comment]
@fricklerhandwerk I agree, but that's a bit of a general problem beyond the scope of this PR, since currently every `MixProfile` command has this issue.

What do you mean with "appropriate blurb"?

**Comment by edolstra** [comment]
https://github.com/NixOS/nix/issues/11659

**Comment by arianvp** [comment]
Fixes https://github.com/NixOS/nix/issues/11790

**Review by tomberek — APPROVED** [review]
Looks like there are some formatting things. Otherwise it looks like it works as expected. (x86-64_linux)

**Pull request merged**
