### PR TITLE
Add nix processes command

### PR DESCRIPTION
**Pull request by matthewbauer**
adds a processes command for #3751

some thing still missing:

- mostly relies on procfs for cmdline info
- no phase reporting

output looks like:

```
Build User: nixbld1
Build Process: nix-daemon 3535     
Child Process: /nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/libexec/gcc/x86_64-unknown-linux-gnu/9.2.0/cc1 -quiet -D _FORTIFY_SOURCE=2 -idirafter /nix/store/fwpn2f7a4iqszyydw7ag61zlnp6xk5d3-glibc-2.30-dev/include -idirafter /nix/store/b3zsk4ihlpiimv3vff86bb5bxghgdzb9-gcc-9.2.0/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/include-fixed conftest.c -quiet -dumpbase conftest.c -mtune=generic -march=x86-64 -auxbase conftest -g -O2 -O2 -Wformat=1 -Wformat-security -Werror=format-security -fstack-protector-strong -fno-strict-overflow -fPIC --param ssp-buffer-size=4 -o /build/cceFfp2A.s 
File Lock: /nix/store/l285fr6qxcf0v0iaphs38lcghv206zar-hello-2.10.lock
```

### CODE REVIEW

**Comment by matthewbauer** [comment]
Ok - this actually doesn't quite work. The userpool locks are always owned by the same process in the nix-daemon. We'll need to filter by uid to determine what the actual pid is.

**Comment by matthewbauer** [comment]
Updated to show the correct pid based on uid of the owning process.

**Comment by edolstra** [comment]
Not sure this is the best approach. 1) It's Linux specific, so at least there should be a big `#if __linux__` around it.  2) It only works when using build users. 3) It make the Nix CLI depend on the internals of `LocalStore`. For instance, it will break once #3600 gets merged. 4) The name `nix processes` is a bit vague. (What processes?) Maybe something like `nix debug show-daemon-status` is better.

**Comment by Atemu** [comment]
Status makes me think more of "how's the daemon doing, is it still up?" (though that also sounds useful), how about `nix daemon monitor`?

You'd use the command to monitor what the daemon is up to atm afterall.

**Comment by matthewbauer** [comment]
> Not sure this is the best approach. 1) It's Linux specific, so at least there should be a big `#if __linux__` around it.

That sounds alright. Some non-Linux systems have procfs, but I have no idea whether it looks the same.

> 3) It make the Nix CLI depend on the internals of `LocalStore`. For instance, it will break once #3600 gets merged.

Right - this is just using the locks in the filesystem. These don't end up being as clear as I originally hoped.

---

What approach would be better? We could keep track of it in nix-daemon - which right now doesn't really know about what builds are happening.
What

**Comment by Atemu** [comment]
Still important to me.

**Pull request closed without merging**
