### PR TITLE
Introduce NIX_INSTALLER_NO_CHANNEL_ADD which skips nix-channel --add

### PR DESCRIPTION
**Pull request by prusnak**
Fixes https://github.com/NixOS/nix/issues/3575

### CODE REVIEW

**Comment by edolstra** [comment]
Why an environment variable rather than a command line flag? Such variables are pretty undiscoverable.

**Comment by prusnak** [comment]
In order to add a new command-line flag I'd need to rework the current naive flag handling. Is that desired within the same PR?

**Comment by domenkozar** [comment]
@prusnak I think it's fine to do it as part of the same PR.

**Comment by prusnak** [comment]
Added commit 9e12b2f5b86963bc6d3a4ee37cc759357fb62263 which exposes installer config env vars via command line flags.

**Comment by prusnak** [comment]
Thanks!

**Comment by LnL7** [comment]
FYI this doesn't seem to work in combination with `--daemon`, that's still updating a channel for me.

**Comment by domenkozar** [comment]
Weird, the code seems to be correct to me.

**Pull request merged**
