### PR TITLE
libexpr: add position to builtins.trace

### PR DESCRIPTION
**Pull request by zimbatm**
Let the user know where the trace was produced by adding the filename
and lineno from where that function was called.

/cc happy birthday @domenkozar :p

### CODE REVIEW

**Comment by edolstra** [comment]
Don't think this is a good idea because it changes the meaning of the trace message, possibly in a confusing way. E.g.
```
trace: warning: types.string is deprecated because it quietly concatenates strings
```
becomes
```
trace: warning: types.string is deprecated because it quietly concatenates strings at /some/file/name.nix:1234
```
but that's not where `types.string` is called. Or what about
```
trace: warning: `stdenv.isArm` is deprecated after 18.03. Please use `stdenv.isAarch32` instead at /some/file/name.nix:1234
```
which tells you to use something in the wrong file.

**Comment by domenkozar** [comment]
What about `trace:/some/file/name.nix:1234: warning: types.string is deprecated because it quietly concatenates strings`

Ideally, there would be an optional way to print the traceback for traces, but at least this makes tracing more useful.

**Comment by zimbatm** [comment]
Fundamentally the issue with `builtins.trace` not reporting the location is a valid usability issue. Currently the way to find the call location can be done but is cumbersome as it involves using `grep` on the nix code.

There are two issues with the current implementation:
* It changes the output. Some tools (like lorri) have started depending on the output.
* The reported position is not always useful as it reports calls to `builtins.trace`, which might be wrapped in a function, like in `lib.traceVal`

What if there was a new trace builtin to which the caller position could be passed?

**Comment by domenkozar** [comment]
@edolstra what if `--show-trace` would show full stack of `trace`? 

We are importing like 10 different github repositories with Nix, and going around each and grep for usage is quite cumbersome.

**Comment by zimbatm** [comment]
I don't know if nix can produce a readable stacktrace in the imperative sense. When the thunk gets evaluated it already lost most of its context.

**Comment by edolstra** [comment]
@domenkozar What do you mean with "full stack of trace"?

**Comment by domenkozar** [comment]
Seems like I'm asking for https://github.com/NixOS/nix/issues/1610

**Comment by zimbatm** [comment]
Closing since a lot of improvements have been added to Nix's error reporting since then.

**Pull request closed without merging**
