### PR TITLE
dirOf: allow use on non-absolute paths

### LINKED ISSUE #2251: dirOf should work with relative paths
Cross-posting from NixOS/nixpkgs#42340.

## Issue description

nix's built-in function `dirOf` only works for strings which are absolute paths, for some reason. This looks like a completely arbitrary (and quite unfortunate) restriction, and the documentation doesn't mention it.

The related function `baseNameOf` does work for all kinds of strings.

### Steps to reproduce

```
nix-instantiate --eval --expr 'dirOf "dir/abc.txt"'                                                        ~
error: string 'dir/abc.txt' doesn't represent an absolute path, at (string):1:1
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.49, NixOS, 18.03.132687.14c248a4ab7 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(paul): `""`
 - channels(root): `"nixos-18.03.132687.14c248a4ab7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### PR DESCRIPTION
**Pull request by lheckemann**
Fixes #2251

### CODE REVIEW

**Comment by lheckemann** [comment]
@edolstra any objection to this?

**Comment by grahamc** [comment]
He objected here: https://github.com/NixOS/nix/issues/2251#issuecomment-399844871

**Comment by lheckemann** [comment]
No, that's an objection to resolving paths relative to the cwd. However, as implemented here, it's completely pure as discussed later in that issue.

**Comment by edolstra** [comment]
Thanks, merged!

**Pull request merged**
