### PR TITLE
Preserve file context across readFile, second take

### PR DESCRIPTION
**Pull request by abbradar**
This rebases old patches to fix https://github.com/NixOS/nix/issues/833 and fixes Hydra test failure too. Closes https://github.com/NixOS/nix/issues/833.

cc @shlevy

### CODE REVIEW

**Comment by shlevy** [comment]
LGTM. I'll set up a hydra jobset

**Comment by shlevy** [comment]
https://hydra.nixos.org/jobset/nix/PR-1643

**Comment by domenkozar** [comment]
Could we have a test? :)

**Comment by abbradar** [comment]
@domenkozar Sorry for taking a long time, I've added a test!

**Comment by abbradar** [comment]
I've rebased the patches but for some reason `nix-copy-closure` test [fails](https://hydra.nixos.org/build/63104473). Any ideas why? I'd very much like to see this fixed in Nix 2.0.

**Comment by shlevy** [comment]
@abbradar That's a bug in the test that I thought @edolstra had fixed... @edolstra should that block merging this?

**Comment by edolstra** [comment]
@abbradar You need the `nix-2.0` branch of Nixpkgs.

Don't know if changing the behaviour of `readFile` just before release is a good idea though.

**Comment by abbradar** [comment]
@edolstra I see this as a bug because it can silently break users' systems after `nix-collect-garbage` is they have fancy enough configuration ([example](https://github.com/NixOS/nix/issues/833#issuecomment-305802085)). If I understand correctly this fix (in theory) just adds more paths into closure of some outputs so it should be fairly harmless. However I don't feel qualified to say this after I have already broken things with an older fix ;)

**Comment by shlevy** [comment]
@edolstra I'd really prefer we branch off 2.0 if we're going to start delaying PRs because they shouldn't be in 2.0... That way we can keep moving despite being feature frozen (or perhaps feature chilled)

**Comment by abbradar** [comment]
Can we proceed with this now that 2.0 release has been branched?

**Comment by abbradar** [comment]
So, any movement here? I've run into this bug yet again, it's pretty annoying.

**Comment by abbradar** [comment]
I have rebased this and resolved conflicts. Not sure if using `printStorePathSet` [here](https://github.com/NixOS/nix/pull/1643/commits/c66865dff1747ecd55915ef8c549dc1a088ff168#diff-0f59bb6f197822ef9f19ceae9624989499d170c84dfdc1f486a8959bb4588cafR1476) is a good idea.

I understand that life and other priorities can get in the way, but it still feels frustrating to keep rebasing this patchset for so many years without any movement. Maybe now that 2.0 is released long time ago we can move forward with this?

**Comment by edolstra** [comment]
The risk with this PR is that it can cause evaluation to produce a different result depending on whether the input is in the Nix store (where it could have references). In the past we had issues like that with Hydra (which copies sources to the Nix store). However, it should be okay so long as the source tree has no references.

**Comment by abbradar** [comment]
Thanks! Let's hope this won't break corner cases for people like it did before @shlevy helped fix it. If anything arises, ping me.

**Pull request merged**
