### PR TITLE
Auto uid allocation -- update with latest master

### PR DESCRIPTION
**Pull request by Ericson2314**

### CODE REVIEW

**Comment by edolstra** [comment]
Maybe better to update #3600 rather than have multiple open PRs for the same thing?

**Comment by thufschmitt** [comment]
> Maybe better to update #3600 rather than have multiple open PRs for the same thing?

I think that’s intent of this PR − it’s opened against the `auto-uid-allocation` branch which @Ericson2314 doesn’t have write access to

**Comment by edolstra** [comment]
Ah thanks, I didn't see that.

**Comment by Ericson2314** [comment]
Thanks! Yeah I can't push there directly so I did this instead. The last few merges were also done this way.

**Pull request merged**
