### PR TITLE
primops: disallow readFile /dev/stdin

### LINKED ISSUE #2716: builtins.getFile /dev/stdin doesn't work on linux
This might be another inconsistency between libstdc++ and libc++.

```bash
darwin $ echo foo | nix-instantiate --eval -E 'builtins.readFile /dev/stdin'
"foo"
```
```bash
linux $ echo foo | nix-instantiate --eval -E 'builtins.readFile /dev/stdin'
""
```

### PR DESCRIPTION
**Pull request by LnL7**
Fixes #2716

### CODE REVIEW

**Comment by grahamc** [comment]
I wonder if this should be restricted somehow so it doesn’t end up in the middle of nixpkgs. For example what happens if it is used twice?

**Comment by LnL7** [comment]
If stdin is read more then once subsequent calls will return an empty string since it's consumed already.

**Comment by shlevy** [comment]
@LnL7 The kosher thing to do here would be to have some state in the eval state to determine if stdin has been read and if so what its contents were.

**Comment by edolstra** [comment]
IMHO this is a really bad idea, reading stdin is very impure and very non-compositional (for example, consider programs like `nixos-rebuild` or NixOps where an expression might be evaluated multiple times).

**Comment by edolstra** [comment]
If the goal is to pass large strings, it might be better to add some flag for this, e.g. `nix-instantiate --arg-from-file foobar /dev/stdin`.

**Comment by LnL7** [comment]
I like the idea of `--arg-from-file`, do I change this to throw an error so it fails everywhere then?

**Comment by edolstra** [comment]
@LnL7 Hm, I don't understand the question, what should throw an error?

**Comment by LnL7** [comment]
I made this to make the behaviour between darwin and linux consistent, so if we don't want this I would prefer to also disable the current behaviour on darwin.

**Comment by lheckemann** [comment]
I'm not sure this would be sufficient, e.g. `builtins.readFile /dev/fd/0` will still behave the same I presume. Perhaps checking the file type using `fstat(0, &st)` and only allowing regular files would be more appropriate.

**Comment by LnL7** [comment]
Hmm guess I didn't push my second commit, that's almost what I did :smile.

**Comment by lheckemann** [comment]
Maybe it should use `S_ISREG` instead — I don't think we want to allow FIFOs either?

**Comment by LnL7** [comment]
Using `S_ISREG` doesn't work for symlinks without resolving them first so I extended the blacklist instead.

**Comment by lheckemann** [comment]
Yes it does, as long as you use `stat` and not `lstat`.

**Pull request closed without merging**
