### PR TITLE
Add missing eval-okay-regex-split.exp test file

### PR DESCRIPTION
**Pull request by mightybyte**
I noticed that this file was absent for some reason.

### CODE REVIEW

**Comment by shlevy** [comment]
I think the way the tests work is that if there's no `.exp` it just checks that the evaluation succeeds?

**Comment by mightybyte** [comment]
Well, this test case has one: https://github.com/NixOS/nix/blob/master/tests/lang/eval-okay-regex-match.exp

**Comment by shlevy** [comment]
Is this causing any issues? Test suite seems to run fine here.

**Comment by mightybyte** [comment]
I'm working on tools that import and run these tests automatically, so it would be nice to have uniformity.

**Pull request merged**
