### PR TITLE
Support building the manual without `make install`

### LINKED ISSUE #7360: Build fails with stage directory: error: cannot open output file /usr/local/lib/libnixutil.so: Permission denied
**Describe the bug**

It can't write into ```$PREFIX```.
It should write into ```$DESTDIR$PREFIX```.

**Steps To Reproduce**
regular build

**Additional context**

Version: 2.11.1
clang-14
FreeBSD 13.1

### PR DESCRIPTION
**Pull request by jhgit**
This changes make target pre-requisites to point to build products within the working area instead the installed location.

Without this, 'gmake all' will hit a dependency on $(bindir)/nix and try to install it (which will normally fail if building as a regular user).

Fixes #7360 (Build fails ... /usr/local/lib/libnixutil.so: Permission denied)

# Motivation
Allow full build as regular user.  Avoid requiring install when just doing 'gmake all'

# Context
Fixes #7360

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

### CODE REVIEW

**Comment by jhgit** [comment]
I should add there was a change here that helps support different sed(1) implementations (for the non-portable -i feature).
`sed -i` is not defined by POSIX, and BSD sed's implementation of -i is parsed differently than GNU sed.  Using '-i.ext' works with both GNU & BSD sed, whereas '-i' by itself or '-i ""' does not.

**Comment by jhgit** [comment]
While this is waiting for a review, it would be helpful for someone with triage access to add the 'build problem' label.

**Comment by Ericson2314** [comment]
@jhgit I recommend pulling the path to the Nix binary to be used into a make variable.

While this better for this PR, something @roberth at least has been pursuing is fine-grained derivations, for sake of quicker rebuilds etc. That would require changing that path to neither it's old or new value, but an external pre-built Nix in the Nix store.

The only way we can support both use-cases with some more indirection in the form of a variable. So let's start there.

**Comment by Ericson2314** [comment]
The build failure looks unrelated: it would appear that `handleSQLiteBusy`'s `logWarning call is still doing too much `error:` and not enough `warning:` and so the `grep` is not properly filtering it out.  I suspect #7865 will help with this.

For now, just ignore it, hopefully it goes away next time.

**Comment by roberth** [comment]
`handleSQLiteBusy` is just silly.

 - #7998
 
 Indeed @Ericson2314's explanation seems sufficient and this does not seem like a relevant error.

**Comment by Ericson2314** [comment]
Triaged in the Nix team meeting:

- build manual w/o Nix
- assigned to @ericson2314

**Comment by Ericson2314** [comment]
@jhgit Please use the factored-out variable. When you rebase and push again the error will probably go away.

**Comment by Ericson2314** [comment]
Closing as duplicate of https://github.com/NixOS/nix/pull/5145

**Pull request closed without merging**
