### PR TITLE
Allow the leading component of a path to be a ~

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by edolstra** [comment]
Something not quite right:
```
$ nix-instantiate --eval -E '~/foo'
//home/eelco/foo
```
(Note the double slash.)

**Comment by shlevy** [comment]
That'll be taken care of by canonicalization right? Given that `builtins.toPath` is broken I don't know of any other way to create a path that uses syntax sugar.

**Comment by shlevy** [comment]
Perhaps we should canonicalize before printing paths? e.g. this works as expected:

> $ nix-instantiate --eval -E 'toString ~/foo'
> "/home/shlevy/foo"

**Comment by shlevy** [comment]
Testing a fix one sec.

**Comment by shlevy** [comment]
@edolstra ^ fixes it.

**Comment by edolstra** [comment]
Actually, why use builtins.getEnv? Seems easier to just construct the path in `parser.y` directly.

**Comment by edolstra** [comment]
BTW, I've been thinking about adding a pure/secure evaluation mode where you can't use `getEnv` or access files outside of certain locations (like the Nix search path). This would be useful for Hydra. What should ~ paths do in that mode?

**Comment by shlevy** [comment]
OK, now we construct the path at parse time. Probably ~ paths should either throw an eval error in 'pure' mode I think.

**Comment by shlevy** [comment]
(if forced, of course, not at parse time)

**Comment by edolstra** [comment]
Thanks, merged!

**Pull request merged**
