### PR TITLE
search.cc: sort attribute names with `std::map`

### PR DESCRIPTION
**Pull request by Ma27**

### CODE REVIEW

**Comment by edolstra** [comment]
Maybe they should be sorted by relevance, e.g. matches in the attribute name having a greater weight than matches in the description.

**Comment by Ma27** [comment]
@edolstra so you mean we should put it all into some kind of `std::vector<SearchResult>` and build a custom sort behavior which weights descriptions **and** attribute names (I only care about attribute names at the moment)?

**Comment by Ma27** [comment]
@edolstra I should've some time in the next days, do you agree with the approach I described in https://github.com/NixOS/nix/pull/1649#issuecomment-340811054 for would you suggest something else? :)

**Comment by Ma27** [comment]
@edolstra I'll resolve the merge conflict tonight.

However it would be cool if you could describe what exactly you would change in the sort behavior before merging it as I'd really like to get it ready for Nix 1.12 :)

**Comment by shlevy** [comment]
@NixOS/nix-core (doesn't exist yet, but a man can dream) @edolstra this looks reasonable to me, can we get this in and think about better sorting algorithms separately?

**Comment by edolstra** [comment]
Yup.

**Comment by Ma27** [comment]
@edolstra @shlevy do you agree with @lheckemann regarding the sort by attribute path thing? In that case I'd submit another PR :)

**Pull request merged**
