### PR TITLE
build: meson for libfetchers

### PR DESCRIPTION
**Pull request by tomberek**
# Motivation
build libfetchers with meson

# Context
builds upon branch [NixOS/nix/meson-libutil](https://github.com/NixOS/nix/tree/meson-libutil)

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Review by fricklerhandwerk — APPROVED** [review]

**Comment by fricklerhandwerk** [comment]
Tracking https://github.com/NixOS/nix/issues/2503

**Comment by fricklerhandwerk** [comment]
Code looks very good, successfully built and did a bunch of cross-compilations locally.

**Comment by edolstra** [comment]
I'm not really in favor of this. It adds a significant amount of code (260 lines between the Meson and Nix expressions), while I'm not convinced that `libfetchers` is something that makes sense to build independently. I mean, who is going to use the `nix-fetchers` derivation?

**Comment by fricklerhandwerk** [comment]
> I mean, who is going to use the `nix-fetchers` derivation?

Separating derivations allows for more incremental builds. Developing Nix without a beefy remote builder is currently very annoying: each time you pull from master, you have to rebuild the entire thing. If component-derivations are cached, and one is only working on the top layers, you save a lot of recompilation time and thus improve the overall feedback cycle.

**Pull request closed without merging**
