### PR TITLE
install-nix: Advancement of destination folder creation means

### PR DESCRIPTION
**Pull request by Anton-Latukha**
This commit concentrates on streamlining `/nix` folder creation.

As Nix installation can be launched from any user, on any distro, with `sudo` or not - here is universal code.

1. At first it tries to create folder from current user. If it is root, or user can create directory - no need to use sudo or su or disturb user with additional messages.
2. Detects does `sudo` installed. Before this we could not distinct when `sudo` access failed itself and when `sudo` is not installed. And now we can say that we looked and `sudo` is not installed, and it is understandable why we ask him root password itself.
3. Looks does `sudo` access is passwordless, or not.
3a. Passwordless: we can inform user that we used `sudo`.
3b. With password: we explain to user why we need sudo access, and ask to enter password for that.
4. If `sudo` fails, we mention that it also can be due to user has no sudoers access. Nowadays `sudo` pretends that password do not match, while in reality user has no sudoers access. The One `sudo` developer, - millert - made that change years ago to not inform hackers that user has no `sudo` access, but those reports is written to logs. But admins/users also can be puzzled by that, especially if passwords/infrastructure is complex.
5. If folder still not created - use `su`.
5a.And big volume of clean distributions (minimalist ones) doesn't have `sudo` supplied with a distro (Alpine, Arch, even Debian I think).
5a. And we explain why installer asks for root password itself.
6. Without informing user when root access closed - he doesn't sure how many operations was under root after he gave access, and what Nix beast will do with his system. We now inform user, in both sudo and su, when we closed root assess, that he kindly entrusted to us.
7. Script errors only when all merits was used - only then. So user has less hassle, we are trying in his benefit.
8. More vocal installation process overall. Which is important for smooth experience and good impression.
9. Yes, I also changed:
```sh
if ! [ -e $dest ]; then # it can also be file or link to file.
# to
if ! [ -d $dest ]; then # it can be only directory/link to directory
```

And, yes; solves #539. Now script not falls because `sudo` is not present, - it uses root, user rights or `su`.
I looked though all 'install' bugs and that's all I found related, but I by the way triaged a handful for people bugs, old ones also.

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
There are 555 open issues.
My PR is 1555.

Thug Life!

**Comment by danbst** [comment]
I think, every case when `$cmd` fails, should end with

`You can skip this check by manually running '$cmd' as root to create $dest`

Also, I don't think that script that writes WHY does it need sudo-permissions will be more trusted then current one (I'm speaking for myself here). I don't trust random curl|sh scripts, even if they post to `/dev/stderr` they do only good.

Triying `su` when `sudo` not found may be a good change though

**Comment by Anton-Latukha** [comment]
When you run remotely on deployment:
`curl https://nixos.org/nix/install | sh`
You don't wait on message:
```shell
You can skip this check by manually running '$cmd' as root to create $dest
```
That shows that install is not production ready.

Run:
`curl -L https://get.docker.com/ | sh`
`curl -L https://bootstrap.saltstack.com | sudo sh`

Does they ask to do something manually before install?

They created to be automatic.

**Comment by danbst** [comment]
> This is our worm welcome to world of Nix.
This is great, but let me repeat my point again, in detail:

I'm talking about situation, when actual install script failed. Don't know why, probably user chose not to enter sudo password (`hey man, you're a script from internet that wants root access, why would I trust you? no-no ^C`). They've already read that Nix doesn't need root in single-user usage, but why the hell does it need root for install?

In that case, when actual install failure happened, it is good to explain user that if he can create and own `/nix`, then script will run without `sudo`, `su` or any other access to root.

I'm also 👍 on using su when sudo not found.

**Comment by Anton-Latukha** [comment]
1. If user runs install script on Linux, - user expects that superuser can be used.
    Doesn't he?
    On what occasions you was installing applications on Linux without superuser access?
    When he installed on Linux something, that was not requiring superuser access, especially package manager.

    It it really astonishing and not expected for user that `hey man, you're a script from internet that wants root access, why would I trust you?`

2. Once more best production oneliners that I mentioned above - expect user is knows when he runs it. They are unattended.

3. If user runs `curl https://nixos.org/nix/install | sh` directly, - that means he trust in script or don't bother.

4. User will look at `https://nixos.org/nix/install`, or download it and check-out.

    For me - this is defence from the fool. People are decide for them-self to look at it and launch it.

    That can be mentioned in official installation. It is not role of the script. To do the job, and not do the job, - it is not realistic.

5. User can just not enter password.
When `sudo` or `su` access asked, user can do ctlr-c, to exit, it is no biggy.

6. Script tells why it needs superuser access.

7. My pull request does not changed point you object to. It existed before me.
Currently main way code runs on master - it runs `sudo` directly. So your note must be pointed at master code.

6. In fact I even work in favour of your objection here.
Before using `sudo` or `su,- my code tries to use user rights itself.
So if we can do it from user, and not use `sudo` or `su` - it does it without them.

**Comment by Anton-Latukha** [comment]
Ok. I close this.

**Pull request closed without merging**
