### PR TITLE
add input scheme for forgejo

### PR DESCRIPTION
**Pull request by getchoo**
# Motivation
recently, codeberg has become a more popular alternative to git hosting services such as github and gitlab. as people choose to move over and more projects are started there, it would be nice to have an easier way to declare repositories hosted there as inputs - similar to other services.

# Context

no issues mentioning this exist as far as i can tell, but this idea was mentioned [here](https://github.com/NixOS/nix/pull/5342#issuecomment-1071237514) (i hope you're a fan @NomisIV 👍🏻)

the implementation of this is similar to other input schemes, with the exception of manually fetching the default branch of the repository. this is due to the forgejo api not accepting `HEAD` as a parameter for [listing refs](https://codeberg.org/api/swagger#/repository/repoListGitRefs), [commits](https://codeberg.org/api/swagger#/repository/repoGetCombinedStatusByRef), or [branches](https://codeberg.org/api/swagger#/repository/repoGetBranch). instead, the default branch (found from the [main repository endpoint](https://codeberg.org/api/swagger#/repository/repoGetBranch)) is used in place of `HEAD` when no ref is specified

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Comment by aidalgol** [comment]
Since [Codeberg is an instance of Forgejo](https://docs.codeberg.org/getting-started/what-is-codeberg/#codeberg-vs.-forgejo%2Fgitea), I think the input scheme should be named after Forgejo, and then mention Codeberg compatibility in the documentation for users who are not aware of Codeberg's underlying forge engine.  I see it already takes a host argument, so it is already a generic Forgejo fetcher, which is great. :+1:

Since Forejo is a fork of Gitea, does this fetcher work with Gitea instances as well, or do the two have incompatible interfaces?

**Comment by getchoo** [comment]
> Since [Codeberg is an instance of Forgejo](https://docs.codeberg.org/getting-started/what-is-codeberg/#codeberg-vs.-forgejo%2Fgitea), I think the input scheme should be named after Forgejo, and then mention Codeberg compatibility in the documentation for users who are not aware of Codeberg's underlying forge engine

that's a good point..i'm not sure why i didn't do that in the first place lol

> Since Forejo is a fork of Gitea, does this fetcher work with Gitea instances as well, or do the two have incompatible interfaces?

currently yes, but as far as i know there are no promises of api compatibility in the future -- so i would be a bit hesistant to do something like the change the name of the fetcher itself. a note in the docs might be good though

**Comment by getchoo** [comment]
made the change, as well as added the note in the docs about gitea being compatible for now

**Comment by fricklerhandwerk** [comment]
Discussed in the Nix team meeting 2023-05-12:

We're not sure if we want this as a special case, and will have to discuss it before moving forward.

<details><summary>Complete discussion</summary>

- @thufschmitt: not sure if we should add more special cases or just stick to Git
    - in this case one can indeed just use Git
    - not really in favor because there is no real justification
    - while it may not be straightforward or as efficient, it's probably less maintenance in the long run 
- @ericson2314: agreed, we have to take care with adding more code that looks very similar needs to be maintained
    - probably having the GitHub special case already in there sends the wrong message
- @roberth: we should wait, since there are interesting developments in that area, such as lazy trees
- @edolstra: it's also about convenience. if it makes user experience smoother we should add it.
    - @roberth: if that's our priority we should stop calling URIs universal
- to discuss, with timebox

</details>

**Comment by aidalgol** [comment]
> probably having the GitHub special case already in there sends the wrong message
Yes, that seems wrong if there is opposition to supporting other code forges in the same way.

**Comment by SuperSandro2000** [comment]
Shouldn't this be ``codeberg:`` regardless if it is gitea or forgejo in the background?

**Comment by Scrumplex** [comment]
I think on a technical level, this *should* be `forgejo:`, as this interfaces with the Forgejo API.

Maybe we can have an alias for codeberg for convenience?

I would expect `nix flake show codeberg:Scrumplex/flake` to pull `https://codeberg.org/Scrumplex/flake.git` and `nix flake show forgejo:Scrumplex/flake` to throw an error, as no host was specified. So `codeberg:<ref>` should just be an alias for `forgejo:<ref>?host=codeberg.org`. Any thoughts?

**Comment by thufschmitt** [comment]
Re-discussed during the Nix team meeting. We confirm the original decision of blocking PRs like this one for the time being as we don't want to have to support too many different input types forever.

A better possible solution would be to have a mechanism to make this pluggable (by e.g. having a special flake output that could be called to update parts of the lockfile), proposals welcome here :)

**Pull request closed without merging**
