### PR TITLE
`TERM=dumb` fixes

### PR DESCRIPTION
**Pull request by intelfx**
- **libmain/progress-bar: try harder to avoid escape sequences if !isTTY**
- **treewide: replace usages of isatty(STDERR_FILENO) with shouldANSI()**
- **treewide: shouldANSI() -> isTTY()**
- **libutil/terminal: cache isTTY()**

# Motivation

Currently, progress bar code emits control sequences (at least `\r` and CSI K)
regardless of whether nix allows other escape sequences in its output (as
determined by `nix::shouldANSI()` function.

Rework progress bar code such that !isTTY disables emission of _all_ control
sequences, including `\r`.

Additionally, rename `nix::shouldANSI()` into `nix::isTTY()` to better reflect
the semantics of this function.

# Context

Running `nix copy` with `TERM=dumb` and/or standard streams redirected into
a pipe still causes nix to emit several control sequences, interfering with
programmatic parsing of its output:

```
    "msg": [
        "",
        "\u001b[KWarning: Permanently added '<redacted>' (ED25519) to the list of known hosts.",
        "",
        "\u001b[Kcopying path '/nix/store/xdrsf841kdlf95rxd3qy6yhi57s25krr-dns-root-data-2023-11-27' from 'https://cache.nixos.org'...",
        "copying path '/nix/store/l3lhzwrfgzncjj1z4wyq6kkrp6czx5qp-gcc-12.3.0-libgcc' from 'https://cache.nixos.org'...",
        <...>
```

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Review by thufschmitt — CHANGES_REQUESTED** [review]
Thanks!

- d9fc4bf5c5a2ad075d4500b005abc839eb98e581, 950b6401f98d1a56fefb2d6101e0513cc601824c and c6f0407103ff64e86b5cc340980c010d49b31e8a look good.
- I don't think 8c1eeb4681dc2acc60f23341d79470a0340ccdf5 is worthwhile (`shouldANSI` feels like a better name to me)

**Comment by intelfx** [comment]
> * I don't think [8c1eeb4](https://github.com/NixOS/nix/commit/8c1eeb4681dc2acc60f23341d79470a0340ccdf5) is worthwhile (`shouldANSI` feels like a better name to me)

It's just a bit of a misnomer, because semantically it also controls whether to emit things like `\r` which are not "ANSI control codes" (thus it does not answer the question of "whether the terminal is ANSI X3.64 capable", but rather the question of "is the thing attached to our stderr _a terminal_ at all").

But I do not feel strongly about it, if you think it's not worthwhile, I'll drop it :)

**Comment by intelfx** [comment]
@thufschmitt gentle ping — does the reasoning above make any additional sense for you, or should I drop the rename?

**Review by thufschmitt — APPROVED** [review]
Sorry for the delay @intelfx 

Nah, let's keep it like that. Will merge as soon as the CI is OK

**Pull request merged**
