### PR TITLE
`nix eval`: Add option `--read-only`

### PR DESCRIPTION
**Pull request by erikarvstedt**
This option sets `Settings::readOnlyMode = true`.
Previously, eval'ing with `readOnlyMode` was only possible through `nix-instantiate --eval`. `readOnlyMode` is now also accessible to the `nix` command.

(Quick reminder: With `readOnlyMode = false` (the current default in `nix eval`), Nix instantiates each derivation whose output or drv path is referenced in the evaluation output; i.e. its `.drv` closure is copied to the store. This is required to support [Import From Derivation](https://nixos.wiki/wiki/Import_From_Derivation).)

`readOnlyMode` has the following advantages:

- Preventing unneeded writes to the store.

- Most importantly: Eval performance.
  Evaluation speed is a major bottleneck when developing or debugging NixOS system configurations.
  `nix eval`'ing a basic system takes ~40% more time [^1] compared to `nix eval --read-only` or `nix-instantiate --eval` (with warm caches).
  This issue has so far prevented me from moving my systems to flakes.
  (Using the much faster `nix-instantiate --eval` with flakes requires flake-compat and doesn't support pure evaluations.)

#### Todo
An optimized `nix eval` implementation would instantiate derivations only when they are accessed during evaluation (Import From Derivation).
In this case, `--read-only` would be obsolete and it could be removed.
Currently, `nix eval` serves as the `nix` CLI equivalent to `nix-instantiate` due to its implicit instantiation behavior.
To allow switching `nix eval` to a non-instantiating, optimized implementation in the future, this PR should also add explicit support for instantiating drvs to the `nix` CLI.
A possible choice is `nix build --derivation`. `--derivation` is currently a no-op when passed to `nix build` (`SourceExprCommand::operateOn` is unused).

#### Appendix

`nix eval nixpkgs#hello.outPath --apply builtins.unsafeDiscardStringContext` doesn't prevent the `hello` derivation from being instantiated, so this is no feasible workaround.

[^1]: You can verify this by running `./benchmark.sh nix_eval_vs_instantiate_eval` ([nix-benchmark](https://github.com/erikarvstedt/nix-benchmark)).
See also: #6309.

cc: @edolstra

### CODE REVIEW

**Review by thufschmitt — COMMENTED** [review]
Thanks, I like the big picture :)

I wonder whether `supportReadOnlyMode` is really needed: `nix build --read-only` isn’t something I would run every day, but it doesn’t seem to hurt either.

Actually we could even make `readOnlyMode` a proper setting − which would implicitly make it a cli flag

**Comment by erikarvstedt** [comment]
`supportReadOnlyMode` is only true (and thus activated) for command `eval`.
(`nix build --read-only` makes no sense because building requires instantiation.)

What do you think about using `nix build --derivation` for explicit instantiation?

**Comment by thufschmitt** [comment]
Yes, `nix build` is probably a very bad example because `--read-only` doesn’t make a lot of sense here (although it’s always possible to come-up with some contrived examples where it would be useful). But my point was that it’s not a big deal to have it, while the `supportReadOnlyMode` parameter is imho adding some complexity to the code in a way that doesn’t feel right.

Just for completeness, an extra advantage of `--read-only` that I think you didn’t mention but is somewhat important (at least to me :wink: ) is that it allows working with stores that are actually read-only (as long as you don’t really need to write to it). For example `nix why-depends nixpkgs#hello nixpkgs#glibc --store https://cache.nixos.org` doesn’t work atm, but it could work in read-only mode

**Comment by edolstra** [comment]
> An optimized nix eval implementation would instantiate derivations only when they are accessed during evaluation (Import From Derivation).

Yes, that's exactly the reason why I didn't add a `--read-only` flag to the new CLI. I didn't want to carry over technical debt from the old CLI. Ideally, in the future, we wouldn't materialize `.drv` files at all (since we can use `buildDerivation()` to send an in-memory representation of the derivation to the daemon).

**Comment by thufschmitt** [comment]
> Ideally, in the future, we wouldn't materialize .drv files at all (since we can use buildDerivation() to send an in-memory representation of the derivation to the daemon).

That would be great, but that’s not gonna happen any time soon, is it?

**Comment by erikarvstedt** [comment]
The new CLI is already exposing the concecpt of `.drv` files, e.g. in `nix copy --derivation`.
Note that `--read-only` can be removed in a fully backwards-compatible way by making it a no-op and hiding it from the documentation.

**Comment by edolstra** [comment]
Should there also be a `--no-read-only` for `nix eval`? If I understand it correctly, `nix eval` will now always be be in read-only mode, so IFD won't work anymore without a way to turn it back on.

**Comment by erikarvstedt** [comment]
This PR doesn't change the default behavior. `readOnlyMode` is still [off by default](https://github.com/NixOS/nix/blob/16860a0328094c04c3e877089119a56f9ddfbcd6/src/libcmd/command.hh#L88).

**Pull request merged**
