### PR TITLE
Fix `boost::bad_format_string` exception in `builtins.addErrorContext`

### PR DESCRIPTION
**Pull request by bacchanalia**
# Motivation
The message passed to addTrace was incorrectly being used as a format string and this this would cause an exception when the string contained a '%', which can be hit in places where arbitrary file paths are interpolated.

# Context
You can trigger the bug by running
```bash
nix eval --expr 'builtins.addErrorContext "%" (throw "ack")'
```
which produces
```
error: boost::bad_format_string: format-string is ill-formed
```

The underlying reason that this bug existed is that the two prototypes for for `addTrace` are compatible in a sneaky way
```cpp
void addTrace(std::shared_ptr<AbstractPos> && e, std::string_view fs, const Args & ... args);
void addTrace(std::shared_ptr<AbstractPos> && e, hintformat hint, bool frame = false);
```
A call with `addTrace(pos, string_view, true)`, type checks and works 99% of the time because the the `true` gets stuck in `args` and the formatter is happy to ignore extra arguments.

### CODE REVIEW

**Comment by bacchanalia** [comment]
Should I submit an issue for this to refer to?

**Comment by edolstra** [comment]
Looks good to me. Could you add a test to `tests/functional/lang.sh` (which already has a few tests of `builtins.addErrorContext`)?

**Comment by bacchanalia** [comment]
will do

**Comment by bacchanalia** [comment]
test added 😎

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ericson2314** [comment]
Thank you!

**Pull request merged**
