### PR TITLE
Allow overlay arguments to be called previous as well as prev

### PR DESCRIPTION
**Pull request by NorfairKing**
# Motivation

See #10516 

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by NorfairKing** [comment]
@edolstra I'd be happy to remove the check entirely, but if we have any enforcement of names, it should be an enforcement of _more_ readable names rather than less readable.

**Review by roberth — APPROVED** [review]
It's the same name, so it's according to convention, but it's a more readable "syntax" for that same name.

Also note that other names can not be completely prev-ented, due frameworks and simple indirections, and I don't mind if `prev` prev-ails, despite my preferences. (an "f", oh well ;) )

**Comment by edolstra** [comment]
The whole point of a convention is that it's consistent (e.g. it doesn't matter whether tabs are 2 or 4 spaces, as long as it's consistent). 

But yeah we can drop this check entirely.

**Comment by edolstra** [comment]
I guess we can close this since #10572 got merged.

**Pull request closed without merging**
