### PR TITLE
ExprApp::eval: A reference to the function might be held if it's a functor, so allocate vFun

### LINKED ISSUE #1045: A bug in __functor?
```
nix-repl> a = { __functor = self: x: builtins.genList self x;}

nix-repl> a
{ __functor = «lambda»; }

nix-repl> a 1
[ Aborted
```

cc @shlevy

### PR DESCRIPTION
**Pull request by shlevy**
Fixes #1045

### CODE REVIEW

**Comment by shlevy** [comment]
@domenkozar Please test with nix-repl, I don't use that.

**Comment by shlevy** [comment]
```shell
$ nix-instantiate --eval -E 'let a = {foo = "lala"; __functor = self: x: map (b: self) ((import <nixpkgs> {}).lib.range 1 x);}; in builtins.head (a 5)'
{ __functor = <LAMBDA>; foo = "lala"; }

$ nix-instantiate --eval -E 'let a = { __functor = self: x: builtins.genList self x;}; in a 1' --strict
[ [ ] ]

```

**Comment by domenkozar** [comment]
@shlevy how do I test this without Nix upgrading my system sqlite schema?

**Comment by edolstra** [comment]
Doesn't this lead to a significant increase in heap allocations?

**Comment by shlevy** [comment]
OK, will do that.

**Comment by shlevy** [comment]
@domenkozar If you run as non-root it will be fine. Going to push the next version to 1.11-maintenance as well though.

**Comment by shlevy** [comment]
Closed in favor of 9fa2176

**Pull request closed without merging**
