### PR TITLE
systemd,launchd match nixos open files limit

### PR DESCRIPTION
**Pull request by Artturin**
it was bumped in https://github.com/NixOS/nixpkgs/pull/176558

### CODE REVIEW

**Comment by edolstra** [comment]
1 million file descriptors sounds rather excessive. If Nix really needs that many, it's clearly a bug.

**Comment by roberth** [comment]
> 1 million file descriptors sounds rather excessive. If Nix really needs that many, it's clearly a bug.

Nix only needs like 3.
The question is what does a _user_'s derivation need? A million is only excessive until it is not, but _probably_ not enough to cause issues on the system.

> clearly a bug

Or a highly concurrent test suite that's heavy on fds.

**Comment by lovesegfault** [comment]
@edolstra Can you take another look at this?

I can't build many derivations on macOS without manually patching the plist like this; otherwise it complains about too many open files.

**Comment by mstone** [comment]
I also recently ran into (another) derivation that needed a higher limit than was provided by default [ IIRC, testing out a mass-rebuild-causing change that had been merged into staging ] and so would appreciate a fix along these lines ~regardless of what number is ultimately chosen.

**Comment by Artturin** [comment]
Thanks thufschmitt & edolstra

**Pull request merged**
