### PR TITLE
nix-daemon.sh profile script: operate under `set -u` in bash

### PR DESCRIPTION
**Pull request by mjgallag**
see https://github.com/NixOS/nix/commit/d459d3307c7b1b10f6489ed048fff192e7834928

# Motivation

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by roberth** [comment]
Could you add `set -u` to the test?

https://github.com/NixOS/nix/blob/de5050f73b3acda5a43926b6083235da161250fb/scripts/nix-profile-daemon.sh.in#L2

**Review by roberth — APPROVED** [review]

**Comment by roberth** [comment]
Thanks!

**Comment by mjgallag** [comment]
oh shoot, that was dumb of me, sorry

**Comment by mjgallag** [comment]
Apologies, I stupidly deleted my fork and couldn't re-open this so I re-created in https://github.com/NixOS/nix/pull/11346.

**Pull request closed without merging**
