### PR TITLE
only send overridden settings to the remote store

### PR DESCRIPTION
**Pull request by LnL7**
Sending all settings breaks builders with another platform,
since that includes 'system' and other local settings like
'sandbox-paths' that might be different.

Explicit overrides like `nix-build --store ssh-ng://foo --option build-use-sandbox true` still work.

### CODE REVIEW

**Comment by LnL7** [comment]
@edolstra ping

**Comment by edolstra** [comment]
Isn't the real issue here that we shouldn't send options to ssh-ng? Only sending overriden settings is a bit ambiguous, e.g. should settings in the user's `~/.config/nix/nix.conf` be respected?

**Comment by LnL7** [comment]
That's a very good point, however I must say that I've found the behaviour pretty useful. Let me check how this behaves with non trusted users.

If you think that's not a good idea I can close this and look at the other solution.

**Comment by LnL7** [comment]
I forgot that this doesn't go through the local daemon. Overriding options only works if the local user has direct ssh access to a trusted user, just like a local client.

**Comment by puffnfresh** [comment]
When I try to build using the ssh-ng remote builder, I get these errors:

```
warning: unknown setting 'allow-new-privileges'
warning: unknown setting 'filter-syscalls'
warning: unknown setting 'sandbox-build-dir'
warning: unknown setting 'sandbox-dev-shm-size'
```

Would this PR also fix these warnings?

**Comment by puffnfresh** [comment]
Yeah, it fixes the warnings and allows using ssh-ng as a remote builder. @edolstra what's the more appropriate fix to make ssh-ng work as a remote builder?

**Comment by LnL7** [comment]
Yeah, those are some platform specific settings.

This basically makes the client behave the same way with ssh-ng as with a local daemon, by only sending settings from the cli and the user’s nix.conf. Ignoring everything would also work but that kind of reverts the functionality from https://github.com/NixOS/nix/commit/37fbfffd8e23cf9ca4038e6c4145583a811e91aa, I’m not sure what implications that has.

**Comment by LnL7** [comment]
Perhaps I should clarify, the main reason for this pr was to get build-remote to work with ssh-ng.

**Comment by shlevy** [comment]
Copying comment from #nix-darwin:

> <shlevy> LnL: I feel like "overridden" is the wrong concept here  [09:05]
> <shlevy> Can you add an additional field to BaseSetting or similar to mark
> 	 whether it should be forwarded?

**Comment by shlevy** [comment]
Possible fix at https://github.com/shlevy/nix/tree/forwardable-settings . Testing now.

**Pull request closed without merging**
