### PR TITLE
Add support for plugins that provide a new subcommand

### PR DESCRIPTION
**Pull request by kirelagin**
This feature has been documented for quite some time but never really worked. Now it does.

The only visible change is that previously plugins were loaded after all of the command line was parsed (so, obviously, subcommands provided by plugins were ignored), now they are loaded after the subcommand name has been parsed and right before the subcommand is resolved. Therefore, the `plugin-files` option has no effect if it comes _after_ the subcommand name. Ideally, a warning should be issues in this case, but I have no idea how to do this.

See also #2597.

### CODE REVIEW

**Comment by kirelagin** [comment]
(cc @edolstra)

**Comment by edolstra** [comment]
Looks good to me, could you resolve the merge conflict?

BTW we could also get rid of libmain (i.e. merge it into src/nix) since it's not really useful anymore now that we have a single binary.

**Comment by 7c6f434c** [comment]
Do we already truly have a single binary? Isn't `nix-env` still separate (and without full replacement)? Even `nix-build` has functionality not conveniently available in `nix build`…

**Comment by kirelagin** [comment]
@7c6f434c Yep, all those are symlinks to `nix`.

**Comment by kirelagin** [comment]
Rebased.

**Comment by kirelagin** [comment]
@edolstra ping!

**Comment by kirelagin** [comment]
👋

**Comment by kirelagin** [comment]
:(

**Comment by edolstra** [comment]
Could this be done without moving `installables.{cc,hh}` to `libmain`?

BTW the flakes branch introduces a couple of nested subcommands (`nix flake <command>`, `nix profile <command>`). Maybe we want to make those extensible as well.

**Comment by kirelagin** [comment]
I think, it can be done, but why though? Many plugins will want to parse commands and, in particular, work with installables, so it makes sense to have this code in the library. `command.{cc,hh}` will definitely have to go there, and if you prefer to live `installables.cc` in `src/nix/` then it might be possible to extract the relevant declarations from `command.hh` into `installables.hh` (which doesn’t exist). But why exactly don’t you want to move them?

**Comment by edolstra** [comment]
`installables.{cc,hh}` and `command.{cc,hh}` contain a lot of stuff specific to the `nix` command (like the `Installable` class) which isn't relevant to other programs that use `libmain` (like Hydra). It might make sense to move `MultiCommand` and `RegisterCommand` to `libutil`.

**Pull request closed without merging**
