### PR TITLE
add documentation for substituter URL options

### PR DESCRIPTION
**Pull request by symphorien**
# Motivation

This functionality exists but is documented nowhere as far as I can tell.

# Context
Documentation is copied from the code:
https://github.com/NixOS/nix/blob/master/src/libstore/binary-cache-store.hh#L19-L30
https://github.com/NixOS/nix/blob/master/src/libstore/s3-binary-cache-store.cc#L194-L207
https://github.com/NixOS/nix/blob/master/src/libstore/ssh-store.cc#L15-L19

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
This is very good material, but it's the wrong place. It should go to the `substituters` section in `nix.conf` docs, that is `globals.hh`.

**Comment by symphorien** [comment]
Done. It seems that there are much more options that I initially thought. I am not 100% sure of some things, please review carefully.

**Comment by fricklerhandwerk** [comment]
@symphorien I'm so sorry for throwing you for a loop! I was not aware this was already so well-structured in the code. In fact, this is information already [rendered by `nix describe-stores`](https://github.com/NixOS/nix/blob/b5b6055bbf00fa809633e88dab1e8eaec3ae9f8d/src/nix/describe-stores.cc#L30-L37), and we should just include a nicer version of that directly in the manual. Otherwise we'd do double book-keeping.

Related:
- https://github.com/NixOS/nix/issues/5467
- https://github.com/NixOS/nix/issues/7672
- https://github.com/NixOS/nix/issues/6279

It requires digging more into the build setup of the manual. See [how documentation for `nix.conf` is built up](https://github.com/NixOS/nix/blob/master/doc/manual/local.mk#L67-L70) by [running an internal command to dump  some JSON](https://github.com/NixOS/nix/blob/master/doc/manual/local.mk#L76-L78) and then [formatting it using the Nix language](https://github.com/NixOS/nix/blob/master/doc/manual/generate-options.nix). 

Such a change will be prioritised by maintainers, since we just recently discussed this and clearly agreed on that being worthwhile.

**Comment by fricklerhandwerk** [comment]
Closing this, since it's superceded by #8084. @symphorien feel free to reopen or make a new PR if you want to add anything on top of that later.

**Pull request closed without merging**
