### PR TITLE
Dockerfile: 2.0.4

### PR DESCRIPTION
**Pull request by asymmetric**
Upgrade nix to 2.0.4.

### CODE REVIEW

**Comment by asymmetric** [comment]
Is a new Docker tag automatically pushed?

**Comment by edolstra** [comment]
No, we should probably integrate updating the Docker image into the Nix release script (`maintainers/upload-release.nix`).

**Comment by asymmetric** [comment]
Do you mean [`maintainers/upload-release.pl`](https://github.com/NixOS/nix/blob/master/maintainers/upload-release.pl`)?

**Comment by edolstra** [comment]
Yes, sorry.

**Comment by asymmetric** [comment]
Oh, seems there's already [an issue](https://github.com/NixOS/nix/issues/2083) for that.

**Pull request merged**
