### PR TITLE
Convert the README to markdown

### PR DESCRIPTION
**Pull request by zimbatm**
This should improve the rendering on github

/cc @edolstra 

If you don't like it, just close this PR.

Link to rendering: https://github.com/zimbatm/nix/blob/markdown-doc/README.md

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @shlevy

**Comment by shlevy** [comment]
I'd be more comfortable merging this if it didn't change the first paragraph's text so much. Otherwise I'll wait for @edolstra

**Comment by zimbatm** [comment]
I was trying to make it a bit more interesting so that people do go away. Usually github repos have a nice introduction on what the tool does, with an example usage and installation doc. Since we have the manual for those I just added a short intro :)

**Comment by zimbatm** [comment]
It will probably never get merged

**Comment by vcunat** [comment]
Well, PRs in this repository are reviewed rather slowly, as it's (almost) exclusively done/doable by Eelco who also does lots of other things.

Personally, I would hesitate to call nix's approach *a new take* nowadays, as it's over a decade old; even though rpm and dpkg can be considered about two decades old.

**Comment by zimbatm** [comment]
Yeah, the PR would probably have some back and forth on wording and it's probably not worth it. Since Eelco is the bottleneck I'm sure he has more important things to do.

It would be nice if responsibilities were distributed a bit more on this repo. It's important to get responsive reviews and quick merges to not discourage contribution. As it stands there is some valuable work (not this PR) that we are losing because of that.

**Comment by domenkozar** [comment]
Done, thanks!

**Pull request closed without merging**
