### PR TITLE
nix-shell: extend the meaning of $IN_NIX_SHELL

### PR DESCRIPTION
**Pull request by vcunat**
... to allow detecting --pure, e.g. in https://github.com/NixOS/nixpkgs/pull/15571#issuecomment-220691732

### CODE REVIEW

**Comment by vcunat** [comment]
I tested the variable really is defined. Someone skilled in perl would better read the change...

**Comment by solson** [comment]
I'd like to bump this to make sure it doesn't get missed. It seems like a quick thing for the right person to review.

I had to work around the `SSL_CERT_FILE` problem in multiple contexts and everyone I know who uses nix has had to deal with it, and the sooner this goes through, the sooner that gets solved, right?

The worst was the nixos-unstable install CD required setting `SSL_CERT_FILE` to use the binary cache.

**Comment by vcunat** [comment]
@edolstra: this PR is very simple.

**Comment by edolstra** [comment]
This breaks Nixpkgs, which has two checks for `$IN_NIX_SHELL` being equal to `1`:
```
lib/trivial.nix:  inNixShell = builtins.getEnv "IN_NIX_SHELL" == "1";
pkgs/development/tools/pypi2nix/default.nix:    if [ "$IN_NIX_SHELL" != "1" ]; then
```

**Comment by vcunat** [comment]
@edolstra: I fixed that up in nixpkgs master https://github.com/NixOS/nixpkgs/commit/d4de02c46. It was trivial; unfortunately the notification for your answer was missed by me somehow.

**Comment by domenkozar** [comment]
Note that `nix-shell` has been meanwhile rewritten to C++: https://github.com/NixOS/nix/pull/1018

**Comment by vcunat** [comment]
Still, this PR would be a trivial merge for the meantime before we get perl-free.

**Comment by domenkozar** [comment]
Pretty sure next Nix release will be perl free, all scripts have been ported ("just" need review): https://github.com/NixOS/nix/issues/341

**Comment by vcunat** [comment]
My experience with nix repo is that "just review and merge" takes significantly more real time than actual implementation.

**Comment by domenkozar** [comment]
@vcunat yes, that's because Eelco maintains software that a few thousand people use. 

It's also the reason I talked to Shea about the port, to get the bus factor down.

We'll improve this, but it's a slow process. I'll help when I can :)

**Comment by Ericson2314** [comment]
Only this PR, and not the perl-to-C++ one, has the documentation update.

**Comment by yurrriq** [comment]
I just came across this accidentally. Any chance we can get this updated and merged? Seems like a cool feature.

**Comment by vcunat** [comment]
The feature is present in nix >= 2.0 via 1bffd83e1.

**Pull request closed without merging**
