### PR TITLE
set up user namespace in builder, not in parent

### PR DESCRIPTION
**Pull request by catern**
This is a minor simplification; there's now slightly less handshaking
required between the builder and the parent, and we create one less
pipe when starting the builder.

As a niche benefit, this also replaces our access to /proc/builder_pid
in the parent with an access to /proc/self in the builder. The former
access could fail if /proc was mounted in a different pid namespace
from the one we are running in; now we will work even if there is such
a misconfiguration.

### CODE REVIEW

**Comment by catern** [comment]
@edolstra ping?

**Comment by catern** [comment]
Still important to me

**Comment by tomberek** [comment]
Does this potentially allow the child to make additional changes to its own namespace? I'm not super familiar with the origin of this, but I'd like to understand and it looks like it is intentional.

**Comment by Ericson2314** [comment]
@catern Are you still interested in this?

I am assigned to get it shepherded over the finish line if so, or closed otherwise.

**Comment by catern** [comment]
I regret to say that I'm no longer interested in this

**Comment by tomberek** [comment]
> I regret to say that I'm no longer interested in this

Can we ask for an explanation of the intent and intended benefit? As above, I’m not quite sure of what all the consequences would be.

**Comment by Ericson2314** [comment]
Yeah @catern if it is "just what it says on the tin" that is fine, but if there was a sharable use-case separate from the technical details that it isn't too much effort to remember on your part that would be good to know.

I might take a look at rebasing this anyways :).

**Comment by catern** [comment]
It's just what it says on the tin. I made this change after writing some container code which made a new pid namespace but didn't remount /proc (which is buggy behavior) and then running Nix inside it. This change made Nix work but also my container code was buggy in the first place.

There's no actual use case for this change, except that it slightly simplifies the code.

**Comment by Ericson2314** [comment]
After like 10 rebases :) I have https://github.com/NixOS/nix/compare/master...obsidiansystems:userns

**Comment by Ericson2314** [comment]
@edolstra Do you know why you had the parent not child set the user namespace originally? As @tomberek says, this is a good case of "Chesterton's Fence" --- we should ask that question before undoing this.

(Also, In the meeting I recall you saying you thought you had done this since, but the rebase I linked above demonstrates this is not the case.)

I had done a `git log -G userNamespaceSync` which led me to c68e5913c71badc89ff346d1c6948517ba720c93, which says:

> Run builds in a user namespace
>
> This way, all builds appear to have a uid/gid of 0 inside the
> chroot. In the future, this may allow using programs like
> systemd-nspawn inside builds, but that will require assigning a larger
> UID/GID map to the build.
>
> Issue #625.

And neither that nor issue #625 seem to shed any light on this implementation detail.

**Comment by edolstra** [comment]
I don't remember why it's done this way. Maybe the kernel required it at the time?

**Comment by Ericson2314** [comment]
Thanks @edolstra. Yes I too vaguely recall user namespace used to be very finicky. That is also my best guess.

**Comment by Ericson2314** [comment]
Rebased as #8023

**Pull request closed without merging**
