### PR TITLE
Rename download to filetransfer

### PR DESCRIPTION
**Pull request by knl**
This change renames all instances of Download to FileTransfer. I initially was taken by surprise that `getDownloader->download()` would also do uploads, depending on whether `Download` struct has data field or not. Thus, in order to ease the cognitive burden of the future readers of the code, I went in and did a rename.

In addition, this change introduces a new method called `upload`, which is exactly the same as `download`, which in turns just enqueues the request and synchronously waits. This is to make it more readable at the call site what is happening.

All the changes will be squashed into a single one prior to (hopefully) approval and merging.

### CODE REVIEW

**Comment by edolstra** [comment]
Could you rebase this?

**Comment by knl** [comment]
> Could you rebase this?

@edolstra Done

**Comment by domenkozar** [comment]
Once again :)

**Comment by knl** [comment]
@domenkozar @edolstra Done, again :)

**Pull request merged**
