### PR TITLE
Only require libsystem on darwin

### LINKED ISSUE #688: libSystem.so requested on NixOS
When I'm trying to run `nix-env -e '*'` on `master` or `nixUnstable` from `nixpkgs`, it reports this:
```
 nix git:(master) ✗ result/bin/nix-env -e '*'
building path(s) ‘/nix/store/w4i5afc8sp7n3rn45h8x2sck7zz2ji2w-user-environment’
error: derivation '/nix/store/0rr1w7i86fnqsr5rhkny0g4abfvs8y28-user-environment.drv' requested impure path ‘/usr/lib/libSystem.dylib’, but it was not in allowed-impure-host-deps (‘/bin/usr/bin’)
 nix git:(master) ✗ 
```
Same story is with `nix-channel --update`. `nixStable` works fine.

### PR DESCRIPTION
**Pull request by shlevy**
Fixes #688

### CODE REVIEW

**Comment by shlevy** [comment]
@abbradar @joachifm Can either of you test with this applied to see if it fixes the problem?

**Comment by shlevy** [comment]
cc @pikajude

**Comment by pikajude** [comment]
@shlevy do we support i686-darwin?

**Comment by shlevy** [comment]
No, I don't think so. `10.7` was the last version that supported it and we're well beyond that in our stdenv, right?

**Comment by shlevy** [comment]
I mean `10.6` was, `10.7` was 64-bit only

**Comment by pikajude** [comment]
Officially pure-darwin is 10.9+, so :+1:

**Comment by copumpkin** [comment]
There are only a handful of Mac models ever that haven't supported x64. I think the last ones were made in 2006 :smile:

**Comment by abbradar** [comment]
It works now, thanks.

**Pull request merged**
