### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by pSub**
This pull requests takes up the work for @fkz on the travis job discussed in #775. After a bit of testing it turned out, that everything works as expected if we use the standard virtual environment.

### CODE REVIEW

**Comment by pSub** [comment]
You can find example logs here https://travis-ci.org/pSub/nix/branches. Look at the builds for the master branch. The first uses the standard environment, the second the trusty environment.

**Comment by edolstra** [comment]
Hm, what do we need this for, given that we're already building Nix in Hydra?

**Comment by copumpkin** [comment]
It can build and run tests on PRs in this repo, which Hydra can't (yet?) do

**Comment by Ericson2314** [comment]
Yeah this seems like a good idea as a stop gap until hydra-github integration is working (I think @shlevy is pretty close).

**Comment by pSub** [comment]
Anything that prevents this from being merged? This could test PRs until hydra-github integration is ready.

**Comment by domenkozar** [comment]
I think it would be better to run as many of the tests/build attributes in http://hydra.nixos.org/eval/1275169#tabs-still-fail

**Comment by siddharthist** [comment]
@copumpkin @domenkozar Anything blocking this?

**Comment by domenkozar** [comment]
We should build Nix from this source, not fetch the stable version. For starters, but really we should run the tests as Hydra does it.

**Comment by siddharthist** [comment]
@domenkozar I'm happy to make a new PR. How does Hydra do it? Can you link me to those tests?

**Comment by domenkozar** [comment]
@siddharthist basically run https://github.com/NixOS/nix/blob/master/release.nix

**Comment by matthewbauer** [comment]
Does Travis actually succeed in building Nix? I'm always getting errors on builds:

```
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
make: *** [mk/patterns.mk:2: src/libexpr/eval.o] Error 4
make: *** Waiting for unfinished jobs....
build time elapsed:  0m0.104s 0m0.038s 2m26.154s 0m33.986s
builder for ‘/nix/store/vzqs399phx74y85l3yxnqhcl68xjphm6-nix-1.12pre1234_abcdef.drv’ failed with exit code 2
```

https://travis-ci.org/matthewbauer/nix/jobs/146402147

**Comment by zimbatm** [comment]
#1152 replaces this PR by using the now builtin Travis Nix integration

**Pull request closed without merging**
