### PR TITLE
optionally dont run functors when finding along an attrpath

### PR DESCRIPTION
**Pull request by cleverca22**

### CODE REVIEW

**Comment by blaggacao** [comment]
@tomberek @edolstra 

This closes https://github.com/NixOS/nix/issues/6152 & https://github.com/NixOS/nix/issues/4415

I have tested this successfully.

Thank you @cleverca22

**Comment by kamadorueda** [comment]
Having a regression test would be awesome

It's just creating a file like: https://github.com/NixOS/nix/blob/master/tests/flake-bundler.sh
and then adding the file name here: https://github.com/NixOS/nix/blob/master/tests/local.mk

**Comment by edolstra** [comment]
It is not clear whether this is desirable behaviour. Due to the interaction between functors and auto-call, it's ambiguous whether you want the attributes from the original set or the output of the functor. E.g. in 
```
outputs = { ... }: {
  x = 123;
  __functor = self: { }: { x = 456; };
};
```
it's not obvious whether `.#x` should evaluate to 123 or 456.

Some possibilities:
* Disallow functors here. I think this is okay since you can always call the functor explicitly.
* Always apply the functor (i.e. `.#x` evaluates to 456).

**Comment by cleverca22** [comment]
the original fault in https://github.com/NixOS/nix/issues/6152 is because a `__functor` is used similarly to `.extend`, and it should only be called with a set of changes

so when you have:
```
{
__functor = ...;
key = 123;
}
```
nix flakes should never run the functor, and just directly use the `.key`

and the exact error, is because `autoCallFunction` ran the functor with the unexpected args, got the wrong result, and everything failed

this PR should just disable `__functor` any time a flake based code is doing an attrpath lookup

**Comment by edolstra** [comment]
If the functor should not be called, then it shouldn't be a functor...

Especially for the flakes case, it seems better to simply forbid the `outputs` function to be a functor.

**Comment by roberth** [comment]
It'd be least surprising if command line attribute syntax behaves close to expression language attribute syntax.

I've also run into this problem trying to define passthru-style tests for fetchers.

 - https://github.com/NixOS/nixpkgs/pull/136022#issuecomment-923944541

**Comment by roberth** [comment]
I find no elegance in functor. It tends to violate single responsibility, and it obfuscates code due to its lack of visibility at the call site / ambiguity with regular application. I try to restrict my use of functor to backward compatibility.

**Comment by tomberek** [comment]
I'm confused at this point. I can come up with instances to use __functor (eg: i'm using it for backward-compat [here](https://github.com/NixOS/bundlers/blob/master/flake.nix#L32)), but my presumptions would be that one can argue for either behavior.

As I was thinking about this I became even more confused about why autoCallFunction is even used. This seems to be a hold-over from trying to have files of this form easily used from CLI.
```
{ pkgs ? import <nixpkgs>{}):
blah
```
To ask another way, why are we auto-calling functions/functors here? Why does `findAlongAttrPath` call functions? Should it?

[another random and possibly horrible thought: there is some open syntax that can capture this distinction `someflake#usingFunctor` and `someflake#.bypassFunctorAndUseAttr` with the extra leading "."]

**Comment by edolstra** [comment]
@tomberek Yeah, I think we shouldn't be auto-calling functions (including functors) at all for flakes. Auto-calling only makes sense if there are arguments to pass, which we don't support for flakes.

**Comment by tomberek** [comment]
Perhaps we have findAlongAttrPath use a "callFunctions" (not sure what the right name should be) and remove the possibility of auto-calling either a function or a functor during attrPath traversal from the flake CLI. Normal attrPath auto-calling should not be impacted as it is relied upon all over the place.

**Comment by disassembler** [comment]
So what's the solution @edolstra? From what I gather how it currently works is incorrect but you're not happy with how this resolves it. Do you have a suggestion that we can try to resolve the issue?

**Comment by blaggacao** [comment]
- @edolstra Would it be possible to reconsider this for 2.8?
- @cleverca22 Can you rebase to make it cheaper to merge?

**Comment by blaggacao** [comment]
superseded by #6399 (rebase)

**Comment by blaggacao** [comment]
This is fixed in `2.8.0`. This can be closed. :rocket:

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nix/pull/6399 links to https://github.com/NixOS/nix/pull/6400 which links to https://github.com/NixOS/nix/pull/6404 which was merged.

@cleverca22 As author, do you agree this can be closed?

**Pull request closed without merging**
