### PR TITLE
Release manager, initial commit.

### PR DESCRIPTION
**Pull request by talbergs**
# Motivation
There is an opportunity to reflect on achievements.

# Context
Developers themselves and consumers are thinking together on this tool. And you can't think if you do not see what is happing with the project.

Some day the release-manager role should be picked up by someone who can.

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] documentation in the internal API docs
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
I don't understand what this PR is about, neither from the description nor from the change. 

The manual contains release notes, e.g. for [release 2.17](https://nixos.org/manual/nix/unstable/release-notes/rl-2.17), if that's what you were missing.

**Comment by talbergs** [comment]
My apologies, here it is https://github.com/NixOS/nix/blob/master/doc/manual/src/release-notes/rl-2.17.md within source. Very good.

Two action points still comes to mind:
1. also have the changelog in github releases section (automated via .github-workflows or smth)
2. have an RSS feeder on manual and/or release notes. (whilst, anyone can craft a personal script for this, RSS is more convenient)

**Comment by fricklerhandwerk** [comment]
I think the easiest would be to link to the release notes from the README. You could use this PR for that purpose or close it otherwise.

RSS sounds like a good idea in principle. Currently releases are announced on Discourse but are somewhat hard to find if you don't know it. Here's an imprecise search query: https://discourse.nixos.org/search?context=category&context_id=8&q=Nix%20released%20in%3Atitle%20%40edolstra&skip_context=false

We could move release announcements into its own category and link to that. It's not exactly as accessible as RSS but a good first step. You'd want to register on Discourse anyway to engage with the community in meaningful ways.

**Comment by fricklerhandwerk** [comment]
@talbergs we moved the release announcements into their own category a short while after the last exchange here: https://discourse.nixos.org/c/announcements/nix-releases/51

Would you be interested in providing an automation for GitHub releases?

**Pull request closed without merging**
