### PR TITLE
[2.3-maintenance] Override socket path with `NIX_DAEMON_SOCKET_PATH` so we can test 2.4+ compat

### PR DESCRIPTION
**Pull request by Ericson2314**
This is the first step to testing compatibility with 2.3 in 2.4 and
master.

(adapted from commit 223fbe644a4cde45269c01e971331d9414971d46)

### CODE REVIEW

**Comment by Ericson2314** [comment]
@regnat this is in response to your comment
https://github.com/NixOS/nix/blob/b367f1061c34f8f358ebf1f02c7bdbb7be6df645/flake.nix#L508-L510
from a0866c8ea4bc66f9aacc7ad19139d57946b3df18. #5572 can be updated to show the interesting failures we are currently trying to fix once this is merged.

**Review by regnat — APPROVED** [review]
> @regnat this is in response to your comment

Yup’ indeed. Dunno why I didn’t backport it at the time.

43d4d75e22ea1f7ee2936fe725c1f7ea7a5005e6 might even be a better thing to backport as it avoids the need for a short drv name, but it might be a bit more involved, so this is a good middle-ground

**Comment by Ericson2314** [comment]
Yes I agree 43d4d75 a nice thing worthy of being backported, but I am not sure what the appetite is for moving things to 2.3 no matter how good, so I just did the bare minimum to unblock this testing.

**Comment by Ericson2314** [comment]
Thanks @edolstra!

**Pull request merged**
