### PR TITLE
Get rid of unicode quotes

### PR DESCRIPTION
**Pull request by layus**
Removed unicode quotes everywhere except in the documentation.
Tests still pass \o/.

The documentation may contain inappropriate unicode quotes if it reproduces output from a nix command.
I quickly went through the doc, and found no such case.

### CODE REVIEW

**Comment by domenkozar** [comment]
I'll merge this quickly before it gets out of sync. Other PRs will get out of sync, but we can't really avoid that.

**Comment by vcunat** [comment]
Info/ping: reverted. *(I personally don't have a strong opinion on this.)*

**Comment by layus** [comment]
@vcunat I don't care either, but we need global guidelines. In #947, @domenkozar asked me to use ASCII quotes, which also made sense. This PR is just the generalisation of the later comment. Do we want to 

1. Keep unicode quotes
2. Use only ASCII quotes
3. Transition slowly (by changing only in modified files for example ?)

@edolstra: Does your commit message (hereafter) mean that there is need for any change ?
> Revert "Get rid of unicode quotes (#1140)"
>
>This reverts commit f78126b. There
>really is no need for such a massive change...

**Comment by cstrahan** [comment]
Ah, bummer. I don't even know how I'd enter a non-ASCII quote, aside from copy paste... So it would seem like a nice thing to get rid of them. (They don't look/feel significantly better, and they tend to trip up text selections in terminal emulators.)

**Comment by copumpkin** [comment]
@edolstra any comment?

**Comment by domenkozar** [comment]
3) is really really painful, as each contirbutor has to change something she/he wasn't responsible for. That's why I went for 2.

**Comment by ChrisJefferson** [comment]
These unicode quotes break output on mac os x.

**Comment by ChrisJefferson** [comment]
This was an old issue:

https://github.com/NixOS/nix/issues/915

**Comment by layus** [comment]
@ChrisJefferson #915 was quite different, and was fixed since. Do you mean that the issue still applies ?

**Comment by ChrisJefferson** [comment]
#915 still isn't fixed (`curl https://nixos.org/nix/install | sh` still doesn't work). Part of the problem there was (I thought) the use of unicode quotes confusing the shell.

**Comment by Unode** [comment]
So as mentioned in #1291 seems like this issue is still coming back every now an then.
Does the benefit of unicode quotes justify the hassle?

**Comment by bjornfor** [comment]
What _is_ the benefit of unicode quotes? (My vote is for ASCII quotes.)

**Comment by vcunat** [comment]
Current discussion: https://github.com/zimbatm/rfcs/pull/4

**Pull request merged**
