### PR TITLE
Make install command in documentation compatible with fish shell

### PR DESCRIPTION
**Pull request by doubledup**
See the description in [NixOS/nix.dev/pull/422](https://github.com/NixOS/nix.dev/pull/422) for more context.

### CODE REVIEW

**Comment by edolstra** [comment]
Shouldn't we just use
```
curl -L https://nixos.org/nix/install | sh
```
since that works in both shells?

**Comment by doubledup** [comment]
@edolstra That's much better, thanks! I've updated the PR and the description. I've also updated some other install commands I found, but left the release notes alone. Is it ok to update the release notes as well?

**Review by fricklerhandwerk — APPROVED** [review]

**Comment by doubledup** [comment]
@fricklerhandwerk @edolstra The [nix.dev PR](https://github.com/NixOS/nix.dev/pull/422) has been merged, but this one seems blocked on some tests that haven't run yet. Is there anything I can do to get the tests running?

**Comment by fricklerhandwerk** [comment]
I was on vacation, sorry for the delay and thanks for hanging tight. Looks good, I'll merge this.

**Comment by doubledup** [comment]
No problem at all. Thanks for all your work on Nix!

**Comment by zegelin** [comment]
This change has removed `--daemon` from the quick-start guide's invocation of `install.sh`.

I'm new to Nix/NixOS, yet it seems like a lot of common internet advice expects Nix to be installed in multi-user mode. Even various Nix wiki pages mention editing `/etc/nix/nix.conf` and restarting `nix-daemon.service` (eg: https://nixos.wiki/wiki/NixOS_on_ARM#Compiling_through_binfmt_QEMU, see the Note box for Arch Linux users).

That change also makes the paragraph following the install instructions make no sense:
> On Linux, `--daemon` can be omitted for a single-user install.

There is no `--daemon` in the invocation to omit!

This change seems to have also missed the https://nixos.org/manual/nix/stable/installation/installation page, which still uses the `bash <(curl -L https://nixos.org/nix/install) --daemon` style invocation.

**Pull request merged**
