### PR TITLE
Switch to nixpkgs 19.09

### PR DESCRIPTION
**Pull request by Ericson2314**

### CODE REVIEW

**Comment by prusnak** [comment]
LGTM

**Comment by edolstra** [comment]
I think the VM tests currently time out on 19.09 (see e.g. https://hydra.nixos.org/build/102562444). I haven't figured out why yet.

**Comment by Ericson2314** [comment]
@edolstra right 19.09 causes problems on the flakes branch, but does it cause problems on master?

**Comment by Ericson2314** [comment]
Thanks!

**Pull request merged**
