### PR TITLE
libstore: don't forward --show-trace

### LINKED ISSUE #3101: warning: ignoring the user-specified setting 'show-trace'
nix 2.3 introduced a spurious warning when providing the CLI with `--show-trace`, despite the option otherwise working as expected (evaluation failures do include a trace when the option is provided). I believe #3037 meant to address this but was closed in favour of 7298a38, which doesn't seem to have covered the same set of options.

```
nix build --show-trace nixpkgs.hello
warning: ignoring the user-specified setting 'show-trace', because it is a restricted setting and you are not a trusted user
```

### PR DESCRIPTION
**Pull request by zimbatm**
Fixes #3101

I didn't do much testing except make sure that it compiles.

What is a good way to test these type of changes without re-installing my system?

### CODE REVIEW

**Comment by edolstra** [comment]
Just stop the running Nix daemon, start the new one, run a client program that connects to it.

**Comment by flokli** [comment]
@zimbatm did this fix somehow end up being backported to NixOS 19.09?

Just had somebody reporting this error on a pretty recent nixos stable…

**Comment by zimbatm** [comment]
It will be part of the next release of Nix

**Comment by flokli** [comment]
It already is part of Nix 2.3.1, but stable still is on 2.3. Do you see any reason not to backport the 2.3.1 bump to stable?

**Pull request merged**
