### PR TITLE
Remove Vim syntax file, point to wiki

### PR DESCRIPTION
**Pull request by phunehehe**

### CODE REVIEW

**Comment by spwhitt** [comment]
I'm not convinced the Nix repository is the right place for Vim syntax files to start with. Putting them here just makes them difficult to install through a plugin manager (pathogen, Vundle, etc...). Additionally, there is a [duplicate copy in nixpkgs which must be kept up to date](https://github.com/NixOS/nixpkgs/blob/ce0cea8938f75afec37b3d2c55300371baab0725/pkgs/applications/editors/vim/ft-nix-support.patch), and which appears to be much more up-to-date than the version of the script located here.

For this reason, I created [my own vim-nix repository](https://github.com/spwhitt/vim-nix). It should be trivial to install through a plugin manager, it already contains your change, and it has numerous improvements over all other nix syntax scripts at the moment. It's still a work in progress, but it's doing the job for me so far.

You may also be interested in [Marc Webber's vim-addon-nix](https://github.com/MarcWeber/vim-addon-nix), which contains a collection of nix related vim tweaks, including the syntax script. I created my repository because I didn't want all the features and dependencies vim-addon-nix has, I was merely interested in the syntax files.

**Comment by phunehehe** [comment]
Wow I never knew there are this many existing tools. It is indeed not ideal to have Vim syntax files here.
I created https://nixos.org/wiki/Vim_configuration and pointed it to (hopefully) the right places.

Modified the commit to delete the dangling .vim file.

**Comment by phunehehe** [comment]
One funny thing: I expect [ft-nix-support.patch](https://github.com/NixOS/nixpkgs/blob/ce0cea8938f75afec37b3d2c55300371baab0725/pkgs/applications/editors/vim/ft-nix-support.patch) to provide Nix syntax highlighting in Vim (my Vim is installed via Nix), but it doesn't seem to. Any idea?

**Comment by edolstra** [comment]
Applied, thanks!

**Pull request closed without merging**
