### PR TITLE
Update toml11

### PR DESCRIPTION
**Pull request by p01arst0rm**
# Motivation
Changes to the source structure are required in preparation for accepting the meson buildsystem. including thirdparty files inside the nix source is not recommended, as it impacts portability and complicates building, and introduces unknown/undeclared dependencies which may cause conflicts on user's systems. these issues are fixed by separating out thirdparty code and properly declaring it, as in #3160. 

# Context
- The Toml11 source has been moved to `/subprojects/toml11`
- The Toml11 source has been updated to offficial version 3.8.1
- The Toml11 source has been patched to fix building.

### CODE REVIEW

**Comment by p01arst0rm** [comment]
related: 

https://github.com/NixOS/nix/pull/3160
https://github.com/NixOS/rfcs/pull/132

**Comment by edolstra** [comment]
Can't we just remove the vendored toml11 and pull it in as an external dependency?

**Comment by p01arst0rm** [comment]
> Can't we just remove the vendored toml11 and pull it in as an external dependency?

this is fixed in the meson build. for now, the files only have to be moved. assuming that the meson build is committed, there is no need to fix this issue twice in the old and new buildsystem.

**Comment by p01arst0rm** [comment]
while i agree moving away from vendoring the files is ideal, and is exactly what the goal is, there are a lot of other annoying issues with allowing either nix or meson to provide toml11. toml11 is already currently vendored, so this PR changes nothing other than the file locations and versions to allow the meson build to use them.

If youre absolutely  sure that these files are not movable and should be deleted, an issue should be opened and the nix flake updated.

**Comment by p01arst0rm** [comment]
any update on merging?

**Comment by Ericson2314** [comment]
Closing in favor of #10972: un-vendoring is better than updating a vendor. :)

**Pull request closed without merging**
