### PR TITLE
remote-store: don't log raw stderr by default

### LINKED ISSUE #3556: `nix build -L` prints each log-line twice when using a `ssh-ng` store.
**Describe the bug**

When building a derivation with a `ssh-ng` store and allowing `nix build` to print all log-lines using `-L`, I get every log-line twice.

**Steps To Reproduce**

1. Configure an arbitrary remote SSH-host to a machine with a running `nix-daemon` (I reproduced this with the [aarch64 build-box](https://github.com/nix-community/aarch64-build-box/) and my personal build-server).
2. Run e.g. `nix build -f . package -L --option experimental-features nix-command --store ssh-ng://builder`

The log-output looks e.g. like this when building `nixops` from a recent `nixpkgs`:

```
Finished executing pipInstallPhase
nixops> Finished executing pipInstallPhase
post-installation fixup
nixops> post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7
nixops> shrinking RPATHs of ELF executables and libraries in /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7
gzipping man pages under /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7/share/man/
nixops> gzipping man pages under /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7/share/man/
strip is /nix/store/3b3ighb83nhifa1v4n7855hlbdl1mhf9-binutils-2.31.1/bin/strip
nixops> strip is /nix/store/3b3ighb83nhifa1v4n7855hlbdl1mhf9-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7/lib  /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7/bin
nixops> stripping (with command strip and flags -S) in /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7/lib  /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7/bin
patching script interpreter paths in /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7
nixops> patching script interpreter paths in /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7
/nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7/share/nix/nixops/generate-ec2-properties.py: interpreter directive changed from " /usr/bin/env python2" to "/nix/store/l9in14pg5smp2gw1mys40zw0r8k8h7la-python-2.7.18/bin/python2"
nixops> /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7/share/nix/nixops/generate-ec2-properties.py: interpreter directive changed from " /usr/bin/env python2" to "/nix/store/l9in14pg5smp2gw1mys40zw0r8k8h7la-python-2.7.18/bin/python2"
checking for references to /build/ in /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7...
nixops> checking for references to /build/ in /nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7...
Rewriting #! /nix/store/kgp3vq8l9yb8mzghbw83kyr3f26yqvsz-bash-4.4-p23/bin/bash -e to #!/nix/store/l9in14pg5smp2gw1mys40zw0r8k8h7la-python-2.7.18
nixops> Rewriting #! /nix/store/kgp3vq8l9yb8mzghbw83kyr3f26yqvsz-bash-4.4-p23/bin/bash -e to #!/nix/store/l9in14pg5smp2gw1mys40zw0r8k8h7la-python-2.7.18
Rewriting #!/nix/store/l9in14pg5smp2gw1mys40zw0r8k8h7la-python-2.7.18/bin/python2.7 to #!/nix/store/l9in14pg5smp2gw1mys40zw0r8k8h7la-python-2.7.18
nixops> Rewriting #!/nix/store/l9in14pg5smp2gw1mys40zw0r8k8h7la-python-2.7.18/bin/python2.7 to #!/nix/store/l9in14pg5smp2gw1mys40zw0r8k8h7la-python-2.7.18
wrapping `/nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7/bin/.nixops-wrapped'...
nixops> wrapping `/nix/store/p5fpq9a68izn34f9xsw0p69s299dkvl5-nixops-1.7/bin/.nixops-wrapped'...
Executing pythonRemoveTestsDir
nixops> Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
nixops> Finished executing pythonRemoveTestsDir
running install tests
nixops> running install tests
NixOps 1.7
nixops> NixOps 1.7
pythonCatchConflictsPhase
nixops> pythonCatchConflictsPhase
pythonRemoveBinBytecodePhase
nixops> pythonRemoveBinBytecodePhase
pythonImportsCheckPhase
nixops> pythonImportsCheckPhase
Executing pythonImportsCheckPhase
nixops> Executing pythonImportsCheckPhase
[1 built, 0.0 MiB DL]
```

**Expected behavior**

I'd expect to only get the log-lines prefixed with `nixops>`. The same log-message without the prefix shouldn't appear.

**`nix-env --version` output**

`nix-env (Nix) 2.4` (to be precise, I tested on 625868b33dab37c0750081843be8091e22808376 in my local git-checkout of Nix).

**Additional context**

* When using `ssh://builder` as store, the issue **doesn't** exist. I'm not 100% sure why yet, unfortunately.
* The messages prefixed with `nixops>` are sent from the remote daemon as `STDERR_RESULT` and therefore properly shown by the progress-bar.
* The non-prefixed duplications are sent as `STDERR_NEXT` from remote and directly printed within the logger implementation in [`remote-store.cc`](https://github.com/NixOS/nix/blob/625868b33dab37c0750081843be8091e22808376/src/libstore/remote-store.cc#L783)
* The culprit is in the [`build.cc`](https://github.com/NixOS/nix/blob/625868b33dab37c0750081843be8091e22808376/src/libstore/build.cc#L4135-L4143) where a log-line is transmitted twice (via `act->result` and via `printError`) if `verboseBuild == true`. Patching Nix on the remote machine by removing the `printError`-statement in line 4137 seems to fix the issue.

Please note that I'm not exactly sure how to proceed here. `verboseBuild` doesn't seem to be an option since it's hard-coded in `libstore/globals.hh`, also modifying this value may have further implications.

Also, the `SSHStore`-implementation for `ssh-ng` basically starts a `nix-daemon` via `ssh` remotely, so AFAICS there's no way on the remote side to determine if a `ssh-ng` store is used where the problem occurs.

I decided to open an issue first to gather some more input, but I'm happy to provide a patch to fix this in the end :) 

CCing some folks who may know about `ssh-ng` @edolstra @grahamc @lheckemann

### PR DESCRIPTION
**Pull request by LnL7**
For remote stores the log messages are already forwarded as structured
STDERR_RESULT messages so the old format is duplicate information.  But
still included with -vvv since it could be useful for debugging
problems.

    $ nix build -L /nix/store/nl71b2niws857ffiaggyrkjwgx9jjzc0-foo.drv --store ssh-ng://localhost
    Hello World!
    foo> Hello World!
    [1/0/1 built] building foo

Fixes #3556

### CODE REVIEW

**Comment by LnL7** [comment]
Actually this breaks build output of nix-build when talking to the daemon. So it seems the daemon case handles this somewhere else.

**Comment by edolstra** [comment]
@LnL7 Is this ready to be merged (given your last comment)?

**Comment by LnL7** [comment]
Yeah, that last commit resolves it.

Not entirely clear why the daemon doesn't currently suffer from this however, something related to the fact that ssh is going through the protocol twice since I'm not using root? (client -> ssh -> deamon)

**Comment by LnL7** [comment]
Thanks!

**Comment by Ma27** [comment]
Hmm, this seems to have the downside that e.g. hash-mismatch errors aren't shown @lnl7 @edolstra

**Comment by LnL7** [comment]
Oh indeed 😕, I didn't notice that yet.

**Comment by LnL7** [comment]
Only for fixed output drvs however `builtins.fetchurl` is handled correctly, I'll take a look.

**Comment by LnL7** [comment]
The following works for nix-build, but the new commands still won't show anything without `-L` so I'm not sure that's the way to go. Adding a new result type for this would be one option but that seems a bit adhoc.

```diff
diff --git a/src/libstore/build.cc b/src/libstore/build.cc
index 147093fa..a81d0101 100644
--- a/src/libstore/build.cc
+++ b/src/libstore/build.cc
@@ -3695,6 +3695,9 @@ void DerivationGoal::registerOutputs()
                 /* Throw an error after registering the path as
                    valid. */
                 worker.hashMismatch = true;
+                worker.act.result(resBuildLogLine, fmt("hash mismatch in fixed-output derivation '%s':", worker.store.printStorePath(dest)));
+                worker.act.result(resBuildLogLine, fmt("  wanted: %s", h.to_string(SRI)));
+                worker.act.result(resBuildLogLine, fmt("  got:    %s", h2.to_string(SRI)));
                 delayedException = std::make_exception_ptr(
                     BuildError("hash mismatch in fixed-output derivation '%s':\n  wanted: %s\n  got:    %s",
                         worker.store.printStorePath(dest), h.to_string(SRI), h2.to_string(SRI)));

```

**Comment by edolstra** [comment]
I'll revert this for now until we figure out what to do.

**Comment by Ma27** [comment]
@edolstra makes sense, but can you please reopen #3556 then?

**Pull request merged**
