### PR TITLE
Display progress when running copyPaths (nix copy)

### PR DESCRIPTION
**Pull request by balsoft**
# Motivation

`nix copy` operations did not show progress. This is quite confusing.

Add a `progressSink` which displays the progress during `copyPaths`,
pretty much copied from `copyStorePath`.

# Context

Fixes https://github.com/NixOS/nix/issues/8000

Here's it working: [asciicast](https://asciinema.org/a/CWP40vlv1m5tyyJlTmpleeVeQ)

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Review by thufschmitt — APPROVED** [review]
This would unfortunately be very cumbersome to test automatically, but I could manually check that it was doing the right thing :+1:

**Comment by Ericson2314** [comment]
If we use another kind of logger, is testing more feasible?

**Comment by thufschmitt** [comment]
> If we use another kind of logger, is testing more feasible?

Yes, that would likely be possible with the `internal-json` logger. Or even better with a C++ test using a mock logger. But either way would be quite a bit of work

**Comment by Ericson2314** [comment]
I might be missing something nuance, would a test like
```bash
nix copy --dest $PWD/scratch --logger internal-json $somePath | grep $somethingInEveryProgressMessage
```
not work?

 I didn't mean to say we should have a golden test for the exact output (which is indeed non-deterministic based on write sizes) or something else similarly challenging.

**Comment by thufschmitt** [comment]
Maybe :thinking: Maybe just checking for the existence of lines of the shape `@nix {"action":"result","fields":[<nonZeroValue>,<nonZeroValue>,0,0],"id":<whatever>,"type":105}` would be a good test indeed (at least these are the one corresponding to the update of the download section of the progress-bar). The thing that scares me a bit is that I've no idea whether this is reliable (is everything deterministic in the pipeline)?

**Pull request merged**
