### PR TITLE
manual: Contributing -> Development, Hacking -> Building

### PR DESCRIPTION
**Pull request by fricklerhandwerk**
# Motivation
what's currently called "hacking" are really instructions for setting up
a development environment and compiling from source. we have
a contribution guide in the repo (which rightly focuses on GitHub
workflows), and the material in the manual is more about working
on the code itself.

# Context

we may want to reorganise this in the future, and bring
contributor-oriented information closer to the code, but for now let's
stick to more accurate names to ease navigation.

This work is sponsored by [Antithesis](https://antithesis.com/) ✨

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Comment by Ericson2314** [comment]
I would call "compiling" "building". "compiling" is a weird word (fun fact, the original "compiler" was actually a linker, and the original meaning of the English word is much better suited for that rather than "translating" which it doesn't meant at all). "compilation" in today's jargon sense is also just once part of the build process too.

It is confusing when the titles and TOC are changed but the file names are are not.

**Comment by cole-h** [comment]
I think changing the filenames to match whatever heading is decided on would be fine, _if_ there are redirects for the old pages put in place. I personally navigate directly to the hacking page using my browser's history, and hitting a 404 would be a little jarring.

**Comment by Ericson2314** [comment]
We've done redirects in the past no problem

**Comment by fricklerhandwerk** [comment]
> I would call "compiling" "building". 

Then we'd have three headings on that page that say "building". I'm somewhat aware of the word's deeper implications, but the historical side note was a pleasure to read.

**Review by Ericson2314 — DISMISSED** [review]
Unfortunately `nix-shell` doesn't work so well because it doesn't set as many configure flags pertenaining to output dirs. I therefore use `nix develop` to work on Nix even though I use `nix-shell` for all other tasks.

The headings look good now, but I still really want the file names to match the heading names. Otherwise I have trouble finding what I am looking for.

**Comment by fricklerhandwerk** [comment]
Blocked by #9459 and https://github.com/NixOS/nix.dev/pull/764, as I don't want to ever deal with the synchronisation nonsense again.

**Comment by fricklerhandwerk** [comment]
It's become a lot more convoluted with the redirects now, and I can't guarantee that nothing will break, but I'll be available for fixing the mess I produce if someone complains.

**Pull request merged**
