### PR TITLE
manual: installation:  Add --daemon flag note

### PR DESCRIPTION
**Pull request by kyrias**

### CODE REVIEW

**Comment by domenkozar** [comment]
@kyrias could you resolve conflicts?

**Comment by kyrias** [comment]
@domenkozar Done.

**Comment by domenkozar** [comment]
wouldn't it make more sense to fix line 28?

**Comment by kyrias** [comment]
Good point.

**Comment by kyrias** [comment]
Actually it seems it wouldn't since #2388 got merged before anyone got around to looking at this. ;p

**Pull request closed without merging**
