### PR TITLE
builtins.validateAsJSON

### PR DESCRIPTION
**Pull request by kamadorueda**
- Add https://github.com/pboettch/json-schema-validator
  as a dependency

  `json-schema-validator` is a library that uses `nlohmann` internally,
  which is being used in other components of Nix already

  `json-schema-validator` is MIT licensed,
  complies with the latest draft of JSON schema
  and is the second one with most stars on GitHub
- Add a new builtin for validating data with a JSON schema.

  This builtin receives two arguments: `schema` and `data`,
  both in Nix format
- Demo:

  ```nix
  let
    schema = {
      title = "A person";
      properties = {
        age = {
          description = "Age of the person";
          type = "number";
          minimum = 1;
          maximum = 200;
        };
        name = {
          description = "Complete Name for the person";
          first.type = "string";
          last.type = "string";
          required = [ "first" "last" ];
          type = "object";
        };
      };
      required = [ "name" "age" ];
      type = "object";
    };
  in
  map (validateAsJSON schema) [
    { }
    { age = 24; name.first = "Jane"; }
    { age = 24; name.first = "Jane"; name.last = "Doe"; }
  ]
  ```

  ```bash
  $ nix-instantiate --eval --strict test.nix
  [
    { success = false;
      value = "At '/', required property 'name' not found in object"; }
    { success = false;
      value = "At '/name', required property 'last' not found in object"; }
    { success = true;
      value = { age = 24; name = { first = "Jane"; last = "Doe"; }; }; }
  ]
  ```
- This demo was also added to the documentation in a simplified form:
  renderized: image

- Added language tests

Mentions #5392

### CODE REVIEW

**Comment by CitadelCore** [comment]
Would be really nice to have this in.

**Comment by Princemachiavelli** [comment]
I would really like to start using this as well. I think one of the most common use cases would be validating against an external JSON schema. I plan on doing some tests with how it interacts with `fromJSON` and how URIs are handled or could be handled.

**Comment by edolstra** [comment]
Maybe this should be an experimental feature initially? This is probably the most complex builtin in the Nix language, so it's good not to commit to it too quickly.

`validateAsJSON` should not return an error string if the input fails to validate. Error strings are likely to be unstable across versions of `json-schema-validator`, which would lead to a difference in evaluation results between Nix versions.

**Comment by adrian-gierakowski** [comment]
What remains to be done for this to become mergeable?

**Comment by Ericson2314** [comment]
This seems quite heavyweight? What is the intended use-case? Just asserting something is valid before processing it, or doing something else with validation errors?

**Comment by hsjobeki** [comment]
Although I enjoyed the demo, this is excellent work. I have one criticism point:

    ```
    $ nix-instantiate --eval --strict test.nix
    [
      { success = false;
        value = "At '/', required property 'name' not found in object"; }
      { success = false;
        value = "At '/name', required property 'last' not found in object"; }
      { success = true;
        value = { age = 24; name = { first = "Jane"; last = "Doe"; }; }; }
    ]
    ```
The 'value' attribute in the returned attrset has different types and semantic meanings depending on the success field.

Maybe it is better to have just one field that contains the JSON
And an extra field for the error message, which is empty in the case of `success=true;` This clearly separates the error message from the JSON value. 

Just an idea to think of...

**Comment by thufschmitt** [comment]
We discussed it during the Nix team meeting. The agreement is that it's not something we want in Nix (if only because it would tie the language spec to the one of jsonschema). But it could be implemented as either a plugin, or in pure Nix

**Pull request closed without merging**
