### PR TITLE
restoreMountNamespace(): Restore the original root directory

### LINKED ISSUE #7602: Nix cannot run other executables in chroot (No such file or directory)
**Describe the bug**

When running a nix command that use another executable (e.g. `man`, `git`, ...) while chrooted, I get a variation of the following error:

```
# nix-env --help
error: command 'man nix-env' failed: No such file or directory
```

The culprit seems to be the restoring of the mount namespace in `restoreMountNamespace`. Using `setns` will reset the root of the process to the root of the namespace, undoing any chroot that was active before.

**Steps To Reproduce**

This only works if the OS  you are chrooting from does not have `man` in one of the locations . This means that if you are using nixos to chroot into another nixos installation, it might seem that everything is fine. Hoewever, you are unknowingly using executables from outside the chroot.

1. Obtain a nixos installation into which you can chroot (I used `nixos-generate-config` and `nixos-install` on a new partition)
2. Chroot into it, for example with `nixos-enter`
3. Run `nix-env --help`

**`nix-env --version` output**

`nix-env (Nix) 2.11.1`

**Additional context**

Note that this only affects `setns` and not `unshare`. I presume this is the case because the kernel can guarantee that the root of the chroot still exists after `unshare`, but not in the case of `setns`. Hence the problem only manifest when `restoreMountNamespace` is called.

I have two different suggestions to fix this bug:

1. Reenter the chroot after `setns` in `restoreMountNamespace`. The only way to do this (that I could find), is to pass a file descriptor of the root to the child process, have the child process obtain the path to the root with /proc, which is not guaranteed to succeed and then call chroot with that path.
2. Don't restore the mount namespace in the child process. As far as I can tell, nix only switches to a new mount namespace so that it can remount the store rw if necessary. This means that one of the following would need to be acceptable:
   1. Running all child processes before remounting the store (they will still be in the new namespace, but nothing will have changed yet, so no harm is done). This might be the case already, I haven't checked this.
   2.  Accept that these child processes can access the store rw
   3. Do all manipulations of the mounts and write accesses to the store in a child process

My preference is the second option, as it is guaranteed to work and doesn't expose anything in the chroot to the outside.

As part of my testing I have also modified `nixos-enter` to use `pivot_root` instead of `chroot` as follows:

```diff
diff --git a/nix/store/bsm9fnrh1bnqmi10nnw0z97b8s5pm9d4-nixos-enter/bin/nixos-enter b/nixos-enter
index eb6291e..d8a4ba2 100755
--- a/nix/store/bsm9fnrh1bnqmi10nnw0z97b8s5pm9d4-nixos-enter/bin/nixos-enter
+++ b/nixos-enter
@@ -107,4 +107,14 @@ chroot_add_resolv_conf "$mountPoint" || echo "$0: failed to set up resolv.conf"
 
 unset TMPDIR
 
-exec chroot "$mountPoint" "${command[@]}"
+cd "$mountPoint"
+
+OLDROOT=`mktemp -d -p tmp`
+
+pivot_root . $OLDROOT
+
+cd /
+
+/run/wrappers/bin/umount -l $OLDROOT
+
+exec "${command[@]}"
```

As now the root of the namespace is what we originally wanted to chroot into, `setns` will no longer dump us back in the original OS.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

This is necessary when we're in a chroot environment, where the process root is not the same as the root of the mount namespace (e.g. in nixos-enter).

Fixes #7602.

# Context

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [x] agreed on idea
 - [x] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [x] documentation in the manual
 - [x] documentation in the internal API docs
 - [x] code and comments are self-explanatory
 - [x] commit message explains why the change was made
 - [x] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Comment by Ericson2314** [comment]
Can we do an `unshare` user namespace + `chroot` test?

**Review by Ericson2314 — COMMENTED** [review]
Everything else but lack of tests looks good.

**Comment by edolstra** [comment]
A test for this would be great, but is probably pretty non-trivial and error-prone, since it requires setting up a chroot environment in which to run Nix. It may be easier to test this as part of the NixOS installation tests.

**Comment by SuperSandro2000** [comment]
Can this be backported?

**Comment by Ericson2314** [comment]
For a behavior change like this I am worry of skipping over 2.15 (2.14 too, but it is sort of a broken release so less so) to 2.13. I will try to backport the backsports.

**Pull request merged**
