### PR TITLE
Make RegexCache thread-safe

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

This is required to make the evaluator thread-safe.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by Mic92** [comment]
Just because it's relevant for me as a maintainer of nix-eval-jobs and other CI stuff. What is the long-term goal with making the nix evaluation thread-safe? Is it to run multiple evaluator threads that eval independent code or is about making the nix evaluation itself parallel.

**Comment by edolstra** [comment]
Both, if you're using the same `EvalState`. If you use a separate `EvalState` per thread, it's already safe since `RegexCache` is per `EvalState`.

**Review by Ericson2314 — APPROVED** [review]

**Review by roberth — CHANGES_REQUESTED** [review]
I don't know about this.
When reviewing partial applications of `builtins.match`, I've told users to just rely on regexes being cached efficiently, but this is making it more expensive to query them.

The performance impact of these lookups (for each call!) could be significant.

I think we should either
- make this an arity 1 primop that returns a function that has the compiled regex in its closure, in which case I'll adjust my recommendations
  - perhaps `tApp` with an `ExternalValue`? or something more direct
  - this functionality could take over the role for direct use of `ExternalValue` in plugins and the C API
- (micro?)benchmark this to measure the impact
- use STM so that lookups don't require sync (this cache is heavily read)

As of now, this change adds no value, yet slows the evaluator down by an unknown amount.

**Comment by Ericson2314** [comment]
If we could use read-write locks, that would be nice.

**Comment by roberth** [comment]
> If we could use read-write locks, that would be nice.

That's still doing unnecessary synchronization though. It's potentially better than the current PR, but probably only improves the multi-threaded case, and does not reduce "single-threaded" overhead to what it was.

**Comment by Ericson2314** [comment]
Since it's just a cache, we can also make a thread-local data structure so no one is doing synchronization but there is slightly more duplication (in the multi-threaded) case.

**Comment by edolstra** [comment]
> but this is making it more expensive to query them.

The cost of futexes in the uncontested (single-threaded) case is basically zero, just a single atomic compare-and-swap instruction to determine that the lock is unlocked, and definitely completely dwarfed by the cost of a regex search.

**Review by roberth — APPROVED** [review]
Checks out. Thanks!

**Pull request merged**
