### PR TITLE
Document store CLI argument

### LINKED ISSUE #5171: Document `--store` option
I can't find any documentation on the `--store` option, which instructs Nix to use a store path other than `/nix/store`. The way I undestand it is that `--store` takes a string of the format `nix-root-path?store-path`, where `nix-root-path` is an actual location in the filesystem where the `nix` directory resides, and `store-path` is the store prefix used by Nix to build packages (usually `/nix/store` -- if it is something else, then cache.nixos.org will not be of much use). My understanding may or may not be correct; it would be great to have some official documentation to clear things up.

### PR DESCRIPTION
**Pull request by tomberek**
Fixes #5171 and #1556

Mostly took verbiage from previous issues and release notes.

### CODE REVIEW

**Comment by regnat** [comment]
There’s a `nix describe-stores` command that generates a documentation for all the existing stores and their options. It would be great to use it to generate this documentation (or possibly an appendix as it’s more exhaustive but also less reader-friendly)

**Comment by Ericson2314** [comment]
Yeah we should generate that appendix and basically just point to it.

**Comment by Ericson2314** [comment]
I think we can close this now that we have `nix --extra-experimental-features nix-command help-stores`?

**Comment by fricklerhandwerk** [comment]
Yes!

**Pull request closed without merging**
