### PR TITLE
Use single underscore for sandboxProfile

### PR DESCRIPTION
**Pull request by pikajude**
@shlevy @nbp @edolstra

### CODE REVIEW

**Comment by shlevy** [comment]
@pikajude the problem was with *propagated*. `sandboxProfile` is indeed internal so it should have the two underscores.

**Comment by nbp** [comment]
Oh, I did not noticed that this was a special attribute expected by the Nix derivations.
Sorry for my mistake.

**Comment by pikajude** [comment]
@nbp does propagatedSandboxProfile need only one underscore in that case?

**Comment by nbp** [comment]
@pikajude I cannot find any references to `propagatedSandboxProfile` which might be an addition inside Nixpkgs. In such case we should probably entirely get rid of of these prefixes, unless there is an unknown semantic behind having `__` prefixes in derivations.

**Pull request closed without merging**
