### PR TITLE
improved help command listing.

### PR DESCRIPTION
**Pull request by henrik-ch**
# Motivation
more complete description in the help commands

fixes https://github.com/NixOS/nix/issues/7956

# Context

This pull request came about as a stepping stone to #7646.

If we think that these suggested changes are a good idea, a corresponding update should happen in unison on:
./src/nix/repl.md

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests
 - [ ] documentation in the manual **- still needs doing in repl.md**
 - [] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or bug fix: updated release notes

### CODE REVIEW

**Comment by edolstra** [comment]
Maybe all of this should be converted into Markdown and moved into the `nix repl` manpage (`repl.md`). And then `:?` can just show that via `showHelp()` in `main.cc`.

**Comment by fricklerhandwerk** [comment]
I suggest making that a follow-up. @henrik-ch please open an issue just in case we lose track of this.

**Comment by henrik-ch** [comment]
Opened #7956, hope that I got it roughly right.

**Comment by Ericson2314** [comment]
Sorry CI seems stuck. Please and the hopefully the problem will go away.

**Comment by treyfortmuller** [comment]
Any reason why this RP stalled? I'm happy to pick it up if there's action items left to burn down

**Comment by henrik-ch** [comment]
@treyfortmuller I replied on your contact form with some more details. I am happy to collaborate and if you prefer I think you can also progress on this without my involvement.

**Pull request merged**
