### PR TITLE
darwin installer: fix on High Sierra

### LINKED ISSUE #1684: Installation fails on macOS High Sierra 10.13.2 beta
This seems to be failing at a different point than #1582 .

```
Michaels-MacBook-Pro:~ curry$ sh ./install-nix
downloading Nix 1.11.15 binary tarball for x86_64-darwin from 'https://nixos.org/releases/nix/nix-1.11.15/nix-1.11.15-x86_64-darwin.tar.bz2' to '/var/folders/25/h6pww5l537d8vfykld5dgp940000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.l6TJusD6'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25.8M  100 25.8M    0     0   456k      0  0:00:58  0:00:58 --:--:--  573k
Switching to the Multi-User Darwin Installer
Welcome to the Multi-User Nix Installation

This installation tool will set up your computer with the Nix package
manager. This will happen in a few stages:

1. Make sure your computer doesn't already have Nix. If it does, I
   will show you instructions on how to clean up your old one.

2. Show you what we are going to install and where. Then we will ask
   if you are ready to continue.

3. Create the system users and groups that the Nix daemon uses to run
   builds.

4. Perform the basic installation of the Nix files daemon.

5. Configure your shell to import special Nix Profile files, so you
   can use Nix.

6. Start the Nix daemon.

Would you like to see a more detailed list of what we will do?
[y/n] n


---- let's talk about sudo -----------------------------------------------------
This script is going to call sudo a lot. Every time we do, it'll
output exactly what it'll do, and why.

Just like this:

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo echo

to demonstrate how our sudo prompts look


This might look scary, but everything can be undone by running just a
few commands. We used to ask you to confirm each time sudo ran, but it
was too many times. Instead, I'll just ask you this one time:

Can we use sudo?
[y/n] y

Yay! Thanks! Let's get going!

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo test -e /var/root/.nix-defexpr

making sure that /var/root/.nix-defexpr doesn't exist


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo test -e /var/root/.nix-channels

making sure that /var/root/.nix-channels doesn't exist


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo test -e /var/root/.nix-profile

making sure that /var/root/.nix-profile doesn't exist


---- hardware report -----------------------------------------------------------
           Cores:	8

---- Nix config report ---------------------------------------------------------
        Temp Dir:	/var/folders/25/h6pww5l537d8vfykld5dgp940000gn/T/tmp.XXXXXXXXXX.OK7d4a9c
        Nix Root:	/nix
     Build Users:	8
  Build Group ID:	30000
Build Group Name:	nixbld

build users:
    Username:	UID
     nixbld1:	30001
     nixbld2:	30002
     nixbld3:	30003
     nixbld4:	30004
     nixbld5:	30005
     nixbld6:	30006
     nixbld7:	30007
     nixbld8:	30008

Ready to continue?
[y/n] y


~~> Setting up the build group nixbld
            Exists:	Yes

~~> Setting up the build user nixbld1

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/sysadminctl -addUser -fullName Nix build user 1 -home /var/empty -UID 30001 -addUser nixbld1

Creating the Nix build user, nixbld1

2017-11-15 17:31:49.208 sysadminctl[6602:237284] Failed to authenticate with SystemAdministration framework.

---- oh no! --------------------------------------------------------------------
Jeeze, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

We'd love to help if you need it.

If you can, open an issue at https://github.com/nixos/nix/issues

Or feel free to contact the team,
 - on IRC #nixos on irc.freenode.net
 - on twitter @nixos_org
```

### PR DESCRIPTION
**Pull request by grahamc**
closes #1684 thanks to @orivej for the good tip on dscl still working!

cc @LnL7 @copumpkin

### CODE REVIEW

**Comment by grahamc** [comment]
Note I've not been able to build this:

```
building path(s) ‘/nix/store/6vfv3gcqir51qms7jg67kn348h8cwc0v-remove-references-to’
killing process 78190
killing process 78089
killing process 78144
killing process 78333
killing process 78056
killing process 78348
error: a ‘i686-linux’ is required to build ‘/nix/store/zlq3ynw0cay1zx1xm7mkpk26flixr2vv-remove-references-to.drv’, but I am a ‘x86_64-darwin’

ndndx:nix graham$ grep -ri remove-references-to .
grep: ./result: No such file or directory

```

**Comment by grahamc** [comment]
Pretty sure this doesn’t work because I’m being silly. I’ll get back on
that.

**Comment by grahamc** [comment]
yep, tested, this works. I have another patch I'd love to land, so don't release just yet please :)

**Comment by orivej** [comment]
#1582 is obscure, are you sure this fixes it?

You may prefer to append "10.13.2" to "High Sierra" in the commit message, since the installer works on the current High Sierra.

**Comment by grahamc** [comment]
As far as I'm aware, and online documentation suggests, the current installer does not work on any version of High Sierra.

**Comment by grahamc** [comment]
I'm not sure about the other bug, I removed it from thee description.

**Comment by orivej** [comment]
I have successfully installed Nix as a non-root user on a fresh macOS 10.13.1 (and then faced #1583 trying to build anything). The title of #1684 is correct to be so specific.

**Comment by orivej** [comment]
(I used `curl https://nixos.org/nix/install | sh` and was asked for the password just once.)

**Comment by grahamc** [comment]
That's fine, I'm happy with the commit message as is.

**Comment by orivej** [comment]
OK, however I'd like to thank @currymj for the early notice!

**Comment by orivej** [comment]
I could not leave this without investigation. (@currymj has used `sh ./install-nix`, not `curl | sh`,  and I was not sure what it was.) I've confirmed that the issue is about 10.13.2.

On macOS 10.13.1:
```
mac:~ user$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.1
BuildVersion:   17B48

mac:~ user$ id
uid=501(user) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(1),707(7),706(6),705(5),703(3),702(2),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),704(4)

mac:~ user$ sudo sysadminctl -addUser abcd
Password:
2017-11-26 03:16:06.277 sysadminctl[1505:9783] ----------------------------
2017-11-26 03:16:06.277 sysadminctl[1505:9783] No clear text password or interactive option was specified (adduser, change/reset password will not allow user to use FDE) !
2017-11-26 03:16:06.277 sysadminctl[1505:9783] ----------------------------
2017-11-26 03:16:06.337 sysadminctl[1505:9783] Creating user record…
2017-11-26 03:16:07.173 sysadminctl[1505:9783] Assigning UID: 502
2017-11-26 03:16:07.206 sysadminctl[1505:9783] Creating home directory at /Users/abcd
```

After upgrade to 10.13.2 beta 4:
```
mac:~ user$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.2
BuildVersion:   17C79a

mac:~ user$ id
uid=501(user) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(1),703(3),702(2),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),704(4)

mac:~ user$ sudo sysadminctl -addUser abcd
Password:
2017-11-26 03:17:44.484 sysadminctl[97888:3988670] Failed to authenticate with SystemAdministration framework.
```

**Comment by currymj** [comment]
One thing I noticed on my local machine was that after using the fix given in #1684, all the nixbld users showed up on the login list when I'd boot up the system, because I'm using FileVault and for some reason they were added to the list of users who can decrypt the drive. I had to manually remove them using `fdesetup`.

It might be worth testing at least once on a drive encrypted with FileVault to check whether this happens with users created using `dscl`, and if it does either adding a fix or documenting for non-sysadmin-savvy users that they can use the `fdesetup` tool to fix it.

I'm not sure how easy it would be to test this. I can do it myself if needed, but I am very happily using Nix right now and would prefer not to uninstall it.

**Comment by orivej** [comment]
That fix did not mark users as hidden. The actual installer hides users with `dscl . -create /Users/nixbld$i IsHidden 1`. (That part is not touched by this PR.)

**Comment by grahamc** [comment]
To test, I've uninstalled Nix and am turning on FV. Hilariously, with Nix installed the "enable filevault" window warns that some users cannot unlock the disk and invites me to see which users and type their passwords in ... but the list is empty because the users are hidden ...

**Comment by LnL7** [comment]
Does dscl work for users pre 10.13? I seem to recall trying that before finding sysadminctl.

**Comment by grahamc** [comment]
This branch passed Travis tests on 10.11: https://travis-ci.org/grahamc/nix#L1

> instance: 6c392d69-c0b0-4c4a-bd86-75632f0c2947 travis-ci-osx10.11-xcode7.3-1480691248 (via amqp)

**Comment by orivej** [comment]
@edolstra This is an important PR, could you merge and release this?

We should also warn the users of macOS 10.13.1 that their OS is not supported, see
https://github.com/NixOS/nixpkgs/issues/32310

**Comment by edolstra** [comment]
IMHO changes should go to master first and then be cherry-picked to the release branch, rather than the other way around.

**Comment by grahamc** [comment]
OK a PR against master is opened (#1719) and this branch is cherry-picks from master.

**Comment by grahamc** [comment]
Travis tests passed again

**Comment by cransom** [comment]
I wasn't aware of the proper way to rebuild a full installer and run from it, but I did recently purge my nix install on my primary 10.13.2 machine, partially run the installer and then drop in the updated `install-darwin-multi-user.sh` and everything works nominally.

**Comment by copumpkin** [comment]
@edolstra can we get this merged and a new release put out? It would be nice to not put off macOS newcomers with a broken install 😄

**Comment by mpcsh** [comment]
@edolstra When will this be up? `curl https://nixos.org/nix/install | sh` still results in a broken install for me. 10.13.2.

**Pull request merged**
