### PR TITLE
Add ``--search`` option to nix-env

### PR DESCRIPTION
**Pull request by tailhook**
The option does substring search on name, attribute name, and meta-description for all the words specified on command-line. So for example `nix-env -qa --search python amqp` gives you expected result.

I believe it should have short alias, but I'm not sure which one. Both `-S` and `-s` are used. May be `-F` (i.e. find or filter)

### CODE REVIEW

**Comment by lheckemann** [comment]
I guess this is to some extent obsoleted by the existence of the [nox](/madjar/nox) tool which provides a much better UX for searching?

**Comment by tailhook** [comment]
@lheckemann, well, I'd better prefer this solution, because:

1. `nox "python amqp"`, shows me nothing, while `nix-env -qaP | grep python | grep amqp | wc -l` yields `16` (which means `nix-env --search python amqp` would work too)
2. `nox` is 3x slower when there is no cache (and I use it so rarely that there is always no cache)
3. `nox python | grep amqp` yields some garbage. I.e. `nox` can be used only interactively.
4. And it's yet another tool comparing to just 50 lines of code that does job well

So while was lazy to update this patch it's still good to have. And I would stop using nox if this patch is applied (because I don't feel comfortable with interactivity of nox). On the other hand, nobody was interested in this for two years....

**Comment by vcunat** [comment]
Side-note: there's also this newly-developed `nix` command. (In any case, I do *not* have push access here.)

**Comment by lheckemann** [comment]
We have nix search now, so I guess there's no point in this one?

**Comment by edolstra** [comment]
Indeed.

**Pull request closed without merging**
