### PR TITLE
Clarify that not all nix packages will use the default build phases

### PR DESCRIPTION
**Pull request by arafangion**
As suggested by @domenkozar in https://github.com/NixOS/nix/pull/758#issuecomment-928308931 I have attempted to provide a conservative pull request to make the change.

This is my first PR for nix, so I'm not entirely sure about conventions.  Happy to adjust and amend as required.

### CODE REVIEW

**Comment by arafangion** [comment]
@domenkozar - you mean, similar to how it was done in #758 ?  Why are there potentially different environment variables in that case, then?  In #758, they used $configurePhase-configurePhase but in my own example I tried locally, I had to use $configurePhase instead as the environment variable.

Also, I'm confused as to why we would have the regular configurePhase exposed, then - are we working around (what seems to be) a bug by basically telling people not to use the exposed commands, or are we working around specific derivations that just happen to not use those default commands?

I would have thought that using the commands (configurePhase), as an example, was how it was supposed to be done and that that these other nix files override it without changing that default was a (temporary?) aberration?

**Comment by domenkozar** [comment]
`$configurePhase-configurePhase`is a typo, it should be `$configurePhase:-configurePhase`

I'm not sure why it needs to fall back, it's probably one of those bash things.

That needs to be looked into, but I don't have time at the moment.

**Comment by Ericson2314** [comment]
I thought we needed the braces? `${configurePhase:-configurePhase}`

**Comment by tomberek** [comment]
Thoughts on something like: https://github.com/flox/nix/commit/c03252cab70379214fabcd839cf432d447a13c42

**Pull request merged**
