### PR TITLE
Check if NIX_LINK_NEW exists instead of checking that NIX_LINK doesn't exist

### PR DESCRIPTION
**Pull request by cole-h**
# Motivation

For brand new installations, neither NIX_LINK_NEW
(`$XDG_STATE_HOME/nix/profile` or `~/.local/state/nix/profile`), nor NIX_LINK (`~/.nix-profile`) will exist.

This restores functionality to nix-env, which is relied upon by GitHub Actions such as https://github.com/cachix/cachix-action and the Nixpkgs EditorConfig (and other) CI.

# Context

Earlier today, Nixpkgs GHA CI started failing because it was relying on `nix-env`. Although this has since been fixed by switching to `nix-shell`, there are other places in the ecosystem that rely on 1) the latest Nix version; and 2) `nix-env`.

See the conversation in https://github.com/NixOS/nix/pull/5588 (starting at https://github.com/NixOS/nix/pull/5588#issuecomment-1448726090).

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

---

This might not be the right solution, but it is _a_ solution that fixes the regression. I'm happy to close this in favor of a more comprehensive solution, however.

There's an extra commit pinning the cachix actions to Nix 2.13.3 to see if that will allow CI to pass (it's failing weirdly on `master` and prior to this change) -- feel free to force-push it away if this overall approach is "good enough" for now.

This should be backported to 2.14.

### CODE REVIEW

**Comment by cole-h** [comment]
I tested this in an Ubuntu 22.04.1 VM using the following (from a now-force-pushed-away commit, but the changes are ~the same):

```#!/usr/bin/env bash
set -eux
export XDG_STATE_HOME=
curl -L https://cole-h-nix-install-tests.cachix.org/serve/6k97myldi0hn3jq36m323cynafdnsb7z/install > install
chmod +x install
cat /dev/null | ./install --tarball-url-prefix https://cole-h-nix-install-tests.cachix.org/serve --daemon

. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

nix-env \
-iA editorconfig-checker \
-f '<nixpkgs>' \
-I nixpkgs=flake:nixpkgs \
--extra-experimental-features flakes

echo does-not-exist | xargs -r editorconfig-checker || echo FAILED!!!!!!!!! # if the file doesn't exist, it will print red text but not hit this "FAILED!!!" print; only if the command can't be found will it hit this print
nix-env -e editorconfig-checker
```

**Comment by fricklerhandwerk** [comment]
@balsoft @thufschmitt

**Review by balsoft — APPROVED** [review]
I'm generally in favor of a fix, but I think there's a better solution. I'll try working on it separately

**Review by Ericson2314 — APPROVED** [review]
Agreed with @balsoft's plan to move this first. Beyond the reasons given, when we make this feature non-experimental but still don't to immediately migrate all existing users, this will be the logic we want.

**Comment by cole-h** [comment]
(FYI, this still included the commit pinning the `install-nix-action` to 2.13.3 -- I don't know if we want to keep that around, especially since v20 of the action fixes the incompatibility with 2.14.0)

**Comment by roberth** [comment]
This was merged without a test case. I hope that's not a pattern.

**Pull request merged**
