### PR TITLE
[WIP] standalone installer: initial work

### PR DESCRIPTION
**Pull request by garbas**
still WIP dont merge yet

[Review on Reviewable](https://reviewable.io/reviews/nixos/nix/703)

### CODE REVIEW

**Comment by lethalman** [comment]
But then, how is that any simpler than:
1. Download the linux tar.gz
2. Extract
3. Run ./install

**Comment by garbas** [comment]
@lethalman still a preview, wont be calling /*/install in final version. one of the goals is also to support multi user installation

**Comment by cillianderoiste** [comment]
I've tested this on Ubuntu 15.10 (x86_64) and it seems to work fine.

**Comment by domenkozar** [comment]
@garbas you still working on this?

**Comment by garbas** [comment]
yes, i'm still working on this but lets close this ticket for now. and i'll reopen when i have something working.

if anybody is interested project is here https://github.com/garbas/nix-installer

**Pull request closed without merging**
