### PR TITLE
build: only skip hash rewriting for sandboxing on linux

### PR DESCRIPTION
**Pull request by LnL7**
The sandbox on darwin, and possibly other future platforms, doesn't have
enough isolation to redirect outputs without hash rewriting.

This fixes `nix-build --check` when sandboxing is enabled on darwin as well as builds with multiple outputs where one of the outputs is already valid.

/cc @edolstra

### CODE REVIEW

**Comment by LnL7** [comment]
Thanks!

**Comment by grahamc** [comment]
Interestingly this has broken `--check` on Linux with sandboxing:

```
[nix-shell:~/projects/github.com/NixOS/nix]$ nix-build ./test.nix -A stable ; nix-build ./test.nix -A stable --check; nix-build ./test.nix -A unstable; nix-build ./test.nix -A unstable --check
these derivations will be built:
  /nix/store/z98fasz2jqy9gs0xbvdj939p27jwda38-stable.drv
building '/nix/store/z98fasz2jqy9gs0xbvdj939p27jwda38-stable.drv'...
/nix/store/yyxlzw3vqaas7wfp04g0b1xg51f2czgq-stable
checking outputs of '/nix/store/z98fasz2jqy9gs0xbvdj939p27jwda38-stable.drv'...
builder for '/nix/store/z98fasz2jqy9gs0xbvdj939p27jwda38-stable.drv' failed to produce output path '/nix/store/yyxlzw3vqaas7wfp04g0b1xg51f2czgq-stable'
error: build of '/nix/store/z98fasz2jqy9gs0xbvdj939p27jwda38-stable.drv' failed
/nix/store/a61slian4dhzajxviv1gfix29gadif3b-unstable
checking outputs of '/nix/store/dysl2dkqa8fw1f7p5b4dah6nyzr3pk9n-unstable.drv'...
builder for '/nix/store/dysl2dkqa8fw1f7p5b4dah6nyzr3pk9n-unstable.drv' failed to produce output path '/nix/store/a61slian4dhzajxviv1gfix29gadif3b-unstable'
error: build of '/nix/store/dysl2dkqa8fw1f7p5b4dah6nyzr3pk9n-unstable.drv' failed
```

with:

```nix
let
  inherit (import <nixpkgs> {}) runCommand;
in {
  stable = runCommand "stable" {} ''

    touch $out
  '';

  unstable = runCommand "unstable" {} ''
    echo $RANDOM > $out
  '';
}
```

**Comment by grahamc** [comment]
(I'm heading out for several hours, but can look in to this later today.)

**Comment by LnL7** [comment]
Hmm, I see both `/nix/store/yyxlzw3vqaas7wfp04g0b1xg51f2czgq-stable` and `/nix/store/a61slian4dhzajxviv1gfix29gadif3b-unstable` which means needsHashRewrite is true?

**Comment by grahamc** [comment]
@LnL7 ^ just opened up a new issue to track the regression (with an experiment's patch, which I think confirms what you say here.) - #2801.

**Comment by LnL7** [comment]
Oh I see what's going on, it's set in the constructor but useChroot is filled in later on.

**Pull request merged**
