### PR TITLE
nix-shell: Don't overwrite PS1.

### PR DESCRIPTION
**Pull request by ben0x539**
Set PS1 only when it's not already set, not when it's set.

### CODE REVIEW

**Comment by ben0x539** [comment]
`[ -n "$PS1" ] && PS1='\n\[\033[1;32m\][nix-shell:\w]\$\[\033[0m\] '; ` seems pretty backwards to me, we specifically try to source `~/.bashrc` earlier, so breaking a prompt set in there seems fairly rude.

**Comment by iblech** [comment]
I noticed this behaviour as well. Do we want to merge this pull request, or do we consider the setting of PS1 a feature? In the latter case, we should probably remove the conditional to express our intent more clearly.

**Comment by copumpkin** [comment]
I think this boils down to the future Nix UI thing @edolstra's been working on for Nix 1.12: there are two use cases for `nix-shell`, and they're at odds with one another: in one, you want a build environment pretty close/identical to what an actual builder uses, in order to debug failing derivation builds. That one should always be bash, have all sorts of junk environment variables set, ideally have sandboxing turned on, and always be pure.

In the other case, you want a fancy `virtualenv` replacement. For that one nobody cares about accuracy and they just want a bunch of packages in scope: there we should allow customizations, different shells, impurity, definitely have no sandboxing, shell hooks, and so on.

The two use cases currently coexist very awkwardly in `nix-shell`, which started (I believe) as a tool for the former and grew into something folks used for both by generating a fake derivation to "debug". I think if we want to address this, we should probably just take the plunge on the separation in 1.12, and not make major changes to the existing UI.

**Comment by iblech** [comment]
Thank you very much for the insightful explanation! Very appreciated. I'm thrilled by the expectation of Nix 1.12, then. :-)

**Comment by ben0x539** [comment]
Looking forward to nix 1.12!

**Pull request closed without merging**
