### PR TITLE
Solve issue #889. Add support for configurable runstatedir ( nix-daem…

### PR DESCRIPTION
**Pull request by adevress**
…on socket directory )
- Add option to configure runstatedir with configure
- Add new environment variable NIX_RUNSTATE_DIR
- Update documentation consequently

### CODE REVIEW

**Comment by adevress** [comment]
Any interest on this guys ?

**Comment by copumpkin** [comment]
I'm not the decision-maker here, but in almost all cases proposals like this flow more smoothly if you motivate the problem you're solving. What made you want this to be configurable? Is it going to affect others? With no context it's hard to distinguish between "I've never wanted this before, and I don't see why anyone else ever would either" and "wow, I'd never thought of that use case; sounds great, thanks!"

**Comment by copumpkin** [comment]
Oh I see, the motivation was in #889, never mind. Either way, I'd make commit messages and blurbs a little more self-contained. The git log is the ultimate source of truth 😄

**Comment by adevress** [comment]
@copumpkin Thank you for the answer Daniel.
The commit makes the nix-daemon socket directory configurable at configure time and runtime.

This allows to use /var/run or /run as the default directory for the socket creation:
- It allows to avoidthe  problems related to distributed file systems when deployed in shared filesystems.
- It allows to make Nix for "FHS" friendly when deployed on not nixos systems.

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by adevress** [comment]
Do not hesitate if you need any modification on this, guys. 
This is part of an effort to make Nix more "sys admin" friendly to make it run and installed on Super-computers as side package manager.

**Comment by domenkozar** [comment]
@adevress why was this closed?

**Comment by adevress** [comment]
@domenkozar  Because this thing has been opened for more than a year. And that if Eelco wanted to merge it, it would have been done already.

**Comment by domenkozar** [comment]
@edolstra does it makes sense to you to separate these directories to support NFS? Is there something to be done with backwards compatibility?

**Pull request closed without merging**
