### PR TITLE
configure.ac: check if lzma has MT support, fix deb build/etc.

### PR DESCRIPTION
**Pull request by dtzWill**
Check is simple but seems to do the job on debian at least,
more complicated checks that include linking may be required
but it seems best to keep this simple for now.

### CODE REVIEW

**Comment by shlevy** [comment]
Should this error out if the user requests parallel decompression but it's not available? Probably not, but want to raise the question...

**Comment by copumpkin** [comment]
Maybe issue a warning in that case, since we're now making an effort to be friendly when people ask for nonsense, rather than just silently ignoring them

**Comment by dtzWill** [comment]
Okay, now emits warnings.  Was a bit clumsy and redundant, so refactored a bit to try to improve things...

Not sure I love what I ended up with, but can't spend more on this right now;
included commit that just adds warnings, maybe grab that if preferred.

Also warns when requesting parallel compression with a method other than "xz".

**Comment by edolstra** [comment]
Ping @AmineChikhaoui

**Comment by dtzWill** [comment]
Beep boop pingaling @AmineChikhaoul

**Pull request merged**
