### PR TITLE
Decode string context straight to using StorePaths 

### PR DESCRIPTION
**Pull request by Ericson2314**
I gather decoding happens on demand, so I hope don't think this should
have any perf implications one way or the other.

### CODE REVIEW

**Review by thufschmitt — COMMENTED** [review]
The last commit looks good to me. Apart from the potential conflicts, is there any reason for this to depend on #6236 ?

**Comment by Ericson2314** [comment]
@thufschmitt It is probably not necessary, but I was a bit nervous about making a `Store` more accessible to the eval cache, because I didn't want to risk some any bit of store state introducing impurities.

**Comment by Ericson2314** [comment]
Squashed out the second commit so there is is no `StoreDirConfig` config in the history. I have kept it elsewhere instead.

**Comment by Ericson2314** [comment]
@edolstra how is this? The core change is the switch to `StorePath`.

The auxillary change is new names for strong contexts, but I think this is good:

1. Matches `SearchPath` and `SearchPathElem`.

2. Allows changes like the `Path` to `StorePath` to be done easily, "catch" all the `std::pair`s that need to be so changed via variable substitution. For RFC 92 I will need to modify `NixStringContext`, so this isn't even that hypothetical a benefit after this one specific renaming.

**Comment by Ericson2314** [comment]
Thank you!

**Pull request merged**
