### PR TITLE
[RFC] libstore: remove static initialisation

### PR DESCRIPTION
**Pull request by Mic92**
This is is an alternative approach to https://github.com/NixOS/nix/pull/2698
If you prefer this approach than I would go ahead and remove the other static intializers as well

### CODE REVIEW

**Comment by matthewbauer** [comment]
@edolstra can answer for sure, but I think this is how plugins are registered in Nix.

**Comment by edolstra** [comment]
Right, this breaks plugins.

**Comment by Mic92** [comment]
@edolstra Could you please elobrate how this break plugins? If you take a look at my version, I kept the old API in place and only made in-tree stores non-static.

**Comment by edolstra** [comment]
It's also much uglier. The current approach is much cleaner since it doesn't require all store implementations to be enumerated in a global header file.

**Comment by Mic92** [comment]
The implementation can be moved to its own compilation unit if necessary.

**Comment by Mic92** [comment]
https://github.com/NixOS/nix/pull/2698 is less intrusive.

**Pull request closed without merging**
