### PR TITLE
Parse mixed nested attrpaths and top-level sets in an order independant way

### PR DESCRIPTION
**Pull request by NinjaTrappeur**
Hi,

This PR implements #2077. I also added some test cases.

I am a bit confused about `tests/lang/parse-fail-dup-attrs-6.nix`.

```
{
  services.ssh.port = 23;
  services.ssh = { enable = true; };
}
```

To me, it clearly looks like the case shown in issue #2077.

Did we simply forget we should not allow mixed attrPaths and forgot to throw an error for the other way around? I am maybe missing something obvious here :).

On a side-note, from an outsider perspective, the addAttr function was confusing. I feel like it could be divided into two functions. I was unsure about this, I just added some comments.

### CODE REVIEW

**Comment by shlevy** [comment]
@NinjaTrappeur Thanks so much for this! I actually think we should *fail* in both directions, not succeed... That is, we should have a copy of `parse-fail-dup-attrs-6.nix` in the opposite direction and then get that one to fail to parse as well :smile:

**Comment by shlevy** [comment]
(I think the existence of that test case is further evidence that #2077 should be a bug :grinning: )

**Comment by NinjaTrappeur** [comment]
Mmh, I am a bit confused here.

I though that `a.b=1; <=> a={b=1;};` [1]. Is this a false assumption?

**Comment by shlevy** [comment]
No, you're correct. But mixing declaration styles like the test suite example does is confusing and unnecessary, it's better not to support it at all. Either use one or the other.

This becomes especially apparent in larger sets. If I see `a = { b = 1; };` in a set, I shouldn't have to look at the entire rest of the set to ensure that `set.a == { b = 1; }`. If we allow mixed declarations, then this becomes possible.

**Comment by shlevy** [comment]
@edolstra Can you make a call here? IMO mixing declarations is just begging for confusion.

**Comment by edolstra** [comment]
Probably it would have been better to disallow both cases from the start, but we probably don't want to break backwards compatibility. So from that perspective, it's cleaner to accept both.

Does this PR merge nested attrsets at arbitrary depths, e.g.
```
{
  services.ssh.enable = true;
  services.ssh = { port = 123; };
  services = {
    httpd.enable = true;
  };
```
?

**Comment by NinjaTrappeur** [comment]
Yes. I just added this test case to this PR.

```
src/nix/nix eval -f tests/lang/parse-okay-mixed-nested-attrs-3.nix services
{ httpd = { enable = true; }; ssh = { enable = true; port = 123; }; }
```

I have a loosely-related question: is there any way to run a CI (hydra?) on a PR?

**Comment by copumpkin** [comment]
> I have a loosely-related question: is there any way to run a CI (hydra?) on a PR?

Unfortunately not unless you have powers over Hydra. There's a thread on getting Travis support (#1152) but it's stalled.

**Comment by flokli** [comment]
What's the status of this? Is this good to merge?

**Comment by NinjaTrappeur** [comment]
It is.

The feature is tested. I can rebase the branch if needed.

I've been bitten by this particular issue several times since I pushed this PR.

**Comment by edolstra** [comment]
Thanks, merged!

**Pull request merged**
