### PR TITLE
addToStore(): Evaluate on the main stack

### LINKED ISSUE #11141: Evaluation error in flake regression test suite
**Describe the bug**

The following test has recently started failing:
```
$ ./flake-regressions/eval-flake.sh  flake-regressions/tests/Anomalocaridid/toolbox/0.1.269+rev-c41c2725b8099d3a37b0beab6afdc99470dfaefa
Evaluating https://api.flakehub.com/f/pinned/Anomalocaridid/toolbox/0.1.269%2Brev-c41c2725b8099d3a37b0beab6afdc99470dfaefa/018d8efd-c3f8-7d1d-adb3-b0101178042b/source.tar.gz...
Flake https://api.flakehub.com/f/pinned/Anomalocaridid/toolbox/0.1.269%2Brev-c41c2725b8099d3a37b0beab6afdc99470dfaefa/018d8efd-c3f8-7d1d-adb3-b0101178042b/source.tar.gz failed to evaluate:
warning: creating lock file '/home/eelco/Dev/nix/flake-regressions/tests/Anomalocaridid/toolbox/0.1.269+rev-c41c2725b8099d3a37b0beab6afdc99470dfaefa/tmp-flake/flake.lock': 
• Added input 'flake':
    'https://api.flakehub.com/f/pinned/Anomalocaridid/toolbox/0.1.269%2Brev-c41c2725b8099d3a37b0beab6afdc99470dfaefa/018d8efd-c3f8-7d1d-adb3-b0101178042b/source.tar.gz?narHash=sha256-915Vs2YX3p3SgUzC7EOeyvpYoiUFniNv01Uj0zJnDos%3D' (2024-02-09)
• Added input 'flake/nixpkgs':
    'github:NixOS/nixpkgs/7c9cc5a6e5d38010801741ac830a3f8fd667a7a0?narHash=sha256-SaTWPkI8a5xSHX/rrKzUe%2B/uVNy6zCGMXgoeMb7T9rg%3D' (2023-10-19)
error:
       … while evaluating attribute 'inventory'
         at /nix/store/badnsj7h4f7n1b2f8fnillpxqsf96ac9-source/flake.nix:113:25:
          112|                 inherit docs;
          113|                 inherit inventory;
             |                         ^
          114|               };

       … while evaluating attribute 'checks'

       … while evaluating attribute 'children'
         at /nix/store/badnsj7h4f7n1b2f8fnillpxqsf96ac9-source/flake.nix:20:48:
           19|
           20|               mkChildren = children: { inherit children; };
             |                                                ^
           21|

       … while evaluating attribute 'x86_64-linux'

       … while evaluating attribute 'children'
         at /nix/store/badnsj7h4f7n1b2f8fnillpxqsf96ac9-source/flake.nix:20:48:
           19|
           20|               mkChildren = children: { inherit children; };
             |                                                ^
           21|

       … while evaluating attribute 'whiskers'

       … while evaluating attribute 'derivation'
         at /nix/store/badnsj7h4f7n1b2f8fnillpxqsf96ac9-source/flake.nix:77:35:
           76|                                 {
           77|                                   derivation =
             |                                   ^
           78|                                     if attrs ? derivation

       … while calling the 'unsafeDiscardStringContext' builtin
         at /nix/store/badnsj7h4f7n1b2f8fnillpxqsf96ac9-source/flake.nix:79:42:
           78|                                     if attrs ? derivation
           79|                                     then builtins.unsafeDiscardStringContext attrs.derivation.drvPath
             |                                          ^
           80|                                     else null;

       … while evaluating the attribute 'derivation.drvPath'
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/lib/customisation.nix:223:7:
          222|     in commonAttrs // {
          223|       drvPath = assert condition; drv.drvPath;
             |       ^
          224|       outPath = assert condition; drv.outPath;

       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating the derivation attribute 'name'
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/pkgs/stdenv/generic/make-derivation.nix:300:7:
          299|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          300|       name =
             |       ^
          301|         let

       … while evaluating the `name` attribute passed to builtins.derivationStrict

       … from call site
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/pkgs/stdenv/generic/make-derivation.nix:318:9:
          317|         in
          318|         lib.strings.sanitizeDerivationName (
             |         ^
          319|           if attrs ? name

       … while calling anonymous lambda
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/lib/strings.nix:1157:3:
         1156|   in
         1157|   string:
             |   ^
         1158|   # First detect the common case of already valid strings, to speed those up

       … while evaluating a branch condition
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/lib/strings.nix:1159:3:
         1158|   # First detect the common case of already valid strings, to speed those up
         1159|   if stringLength string <= 207 && okRegex string != null
             |   ^
         1160|   then unsafeDiscardStringContext string

       … in the left operand of the AND (&&) operator
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/lib/strings.nix:1159:33:
         1158|   # First detect the common case of already valid strings, to speed those up
         1159|   if stringLength string <= 207 && okRegex string != null
             |                                 ^
         1160|   then unsafeDiscardStringContext string

       … in the argument of the not operator
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/lib/strings.nix:1159:26:
         1158|   # First detect the common case of already valid strings, to speed those up
         1159|   if stringLength string <= 207 && okRegex string != null
             |                          ^
         1160|   then unsafeDiscardStringContext string

       … while calling the 'lessThan' builtin
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/lib/strings.nix:1159:26:
         1158|   # First detect the common case of already valid strings, to speed those up
         1159|   if stringLength string <= 207 && okRegex string != null
             |                          ^
         1160|   then unsafeDiscardStringContext string

       … while calling the 'stringLength' builtin
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/lib/strings.nix:1159:6:
         1158|   # First detect the common case of already valid strings, to speed those up
         1159|   if stringLength string <= 207 && okRegex string != null
             |      ^
         1160|   then unsafeDiscardStringContext string

       … in the condition of the assert statement
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/pkgs/stdenv/generic/make-derivation.nix:323:13:
          322|             # we cannot coerce null to a string below
          323|             assert lib.assertMsg (attrs ? version && attrs.version != null) "The ‘version’ attribute cannot be null.";
             |             ^
          324|             "${attrs.pname}${staticMarker}${hostSuffix}-${attrs.version}"

       … from call site
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/pkgs/stdenv/generic/make-derivation.nix:323:20:
          322|             # we cannot coerce null to a string below
          323|             assert lib.assertMsg (attrs ? version && attrs.version != null) "The ‘version’ attribute cannot be null.";
             |                    ^
          324|             "${attrs.pname}${staticMarker}${hostSuffix}-${attrs.version}"

       … while calling 'assertMsg'
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/lib/asserts.nix:23:5:
           22|     # Message to throw in case `pred` fails
           23|     msg:
             |     ^
           24|     pred || builtins.throw msg;

       … in the left operand of the OR (||) operator
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/lib/asserts.nix:24:10:
           23|     msg:
           24|     pred || builtins.throw msg;
             |          ^
           25|

       … in the right operand of the AND (&&) operator
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/pkgs/stdenv/generic/make-derivation.nix:323:51:
          322|             # we cannot coerce null to a string below
          323|             assert lib.assertMsg (attrs ? version && attrs.version != null) "The ‘version’ attribute cannot be null.";
             |                                                   ^
          324|             "${attrs.pname}${staticMarker}${hostSuffix}-${attrs.version}"

       … from call site
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/pkgs/stdenv/generic/make-derivation.nix:323:54:
          322|             # we cannot coerce null to a string below
          323|             assert lib.assertMsg (attrs ? version && attrs.version != null) "The ‘version’ attribute cannot be null.";
             |                                                      ^
          324|             "${attrs.pname}${staticMarker}${hostSuffix}-${attrs.version}"

       … while calling anonymous lambda
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/lib/attrsets.nix:846:24:
          845|     let f = attrPath:
          846|       zipAttrsWith (n: values:
             |                        ^
          847|         let here = attrPath ++ [n]; in

       … while calling the 'head' builtin
         at /nix/store/4jfc6vrkmq7z5pb651jh5b4kra5f1kwp-source/lib/attrsets.nix:850:11:
          849|         || pred here (elemAt values 1) (head values) then
          850|           head values
             |           ^
          851|         else

       error: attribute 'package' missing
       at /nix/store/lnrdwxk9d0ffv78w87swjy497js2i13s-source/nix/default.nix:11:18:
           10|         inherit pname;
           11|         inherit (memberCargoToml.package) version;
             |                  ^
           12|         src = pkgs.nix-gitignore.gitignoreSource [] ../.;
```

`git bisect` pointed to b230c01f7335e9cb0403587c3b7ab352d5dacd9b (https://github.com/NixOS/nix/pull/11014), however since that didn't change anything in the evaluator, and mysterious "attribute missing" errors are often GC-related, I ran the test script with `GC_INITIAL_HEAP_SIZE=10G` and that made it succeed. So we have a GC bug somewhere.

**Steps To Reproduce**

**Expected behavior**

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

Switching from `sinkToSource()` to `sourceToSink()` causes the path filter evaluation to happen on the thread's main stack rather than on the coroutine stack. This should avoid the need for our Boehm GC coroutine workarounds, since the GC roots will be on the main stack of the thread.

Fixes #11141.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by edolstra** [comment]
Team discussion:
* Need to benchmark that this doesn't introduce a performance regression.
* Otherwise looks good.

**Review by tomberek — APPROVED** [review]
Seems to speed things up.
```
# started on Fri Aug 16 23:44:23 2024


 Performance counter stats for './run-result.sh' (4 runs):

          3,416.28 msec task-clock:u                     #    0.999 CPUs utilized               ( +-  1.50% )
                 0      context-switches:u               #    0.000 /sec                      
                 0      cpu-migrations:u                 #    0.000 /sec                      
           190,200      page-faults:u                    #   55.675 K/sec                       ( +-  0.00% )
    12,996,898,345      cycles:u                         #    3.804 GHz                         ( +-  1.21% )
    22,704,239,938      instructions:u                   #    1.75  insn per cycle              ( +-  0.72% )
     4,445,076,656      branches:u                       #    1.301 G/sec                       ( +-  0.72% )
        74,424,990      branch-misses:u                  #    1.67% of all branches             ( +-  1.36% )
                        TopdownL1                 #     24.3 %  tma_backend_bound      
                                                  #     29.4 %  tma_bad_speculation    
                                                  #     17.2 %  tma_frontend_bound     
                                                  #     29.1 %  tma_retiring             ( +-  1.06% )

            # Table of individual measurements:
            3.3201 (-0.0987) #
            3.5504 (+0.1316) #
            3.3615 (-0.0573) #
            3.4432 (+0.0244) #

            # Final result:
            3.4188 +- 0.0508 seconds time elapsed  ( +-  1.49% )

```


before:
```
# started on Fri Aug 16 23:41:00 2024


 Performance counter stats for './run-stable.sh' (4 runs):

          3,371.94 msec task-clock:u                     #    0.998 CPUs utilized               ( +-  0.12% )
                 0      context-switches:u               #    0.000 /sec                      
                 0      cpu-migrations:u                 #    0.000 /sec                      
           189,853      page-faults:u                    #   56.304 K/sec                       ( +-  0.01% )
    13,396,059,025      cycles:u                         #    3.973 GHz                         ( +-  0.22% )
    25,653,034,868      instructions:u                   #    1.91  insn per cycle              ( +-  0.02% )
     4,688,934,517      branches:u                       #    1.391 G/sec                       ( +-  0.02% )
        79,226,022      branch-misses:u                  #    1.69% of all branches             ( +-  0.11% )
                        TopdownL1                 #     16.4 %  tma_backend_bound      
                                                  #     47.7 %  tma_bad_speculation    
                                                  #     12.3 %  tma_frontend_bound     
                                                  #     23.6 %  tma_retiring             ( +-  0.12% )

           # Table of individual measurements:
           3.36667 (-0.01366) #
           3.38003 (-0.00031) #
           3.37659 (-0.00375) #
           3.39805 (+0.01772) #

           # Final result:
           3.38034 +- 0.00655 seconds time elapsed  ( +-  0.19% )

```

**Comment by tomberek** [comment]
This does make evaluation with GC slightly worse, but greatly simplifies implementation. Performance cost seems low.

I could not update this branch, but have a rebase at: https://github.com/tomberek/nix/tree/flip-coroutines

**Comment by edolstra** [comment]
I also measured and got a slight (not statistically significant) speedup:
```
elapsed time:       median =     18.8708  mean =     18.8354  stddev =      0.0964  min =     18.6845  max =     18.9424  [not rejected, p=0.10362, Δ=-0.10630±0.20030]
```

**Comment by Mic92** [comment]
Does this mean we can get rid of https://github.com/NixOS/nix/pull/4944/commits/57409244ec8f568ce6b4ecb1bde0e509942ac05f ?

**Pull request merged**
