### PR TITLE
Support statically built Nix on Darwin

### PR DESCRIPTION
**Pull request by matthewbauer**
This adds support for static Darwin Nix via https://github.com/NixOS/nixpkgs/pull/106115.

- Need to skip the `-Ur` flag for darwin cctools
- Update nixpkgs to my branch (should probably wait until merged into Nixpkgs & maybe released)
- Enable x86_64-darwin builds.

### CODE REVIEW

**Comment by edolstra** [comment]
Yes, we should stick to the Nixpkgs 20.09 branch for now. Otherwise looks good to me.

**Comment by domenkozar** [comment]
@matthewbauer care to sync with nixpkgs changes?

**Comment by domenkozar** [comment]
@matthewbauer ping :)

**Comment by matthewbauer** [comment]
Static compilation is broken by https://github.com/NixOS/nixpkgs/pull/107238 - will need to address it in nixpkgs.

**Pull request closed without merging**
