### PR TITLE
Expanded test suite

### PR DESCRIPTION
**Pull request by Mathnerd314**
- lang now verifies errors and parse output
- Some new miscellaneous tests

### CODE REVIEW

**Comment by gilligan** [comment]
Has anyone ever looked at this at all?

**Comment by Ericson2314** [comment]
This is good! Have we done tests like it since? Sure, the logging format is subject to change, but we just update the expected output once it does.

**Comment by fricklerhandwerk** [comment]
@Mathnerd314 are you by any chance still interested in moving this pull request forward? The [Nix team](https://discourse.nixos.org/t/nix-team-creation/22228) agrees these are worthwhile additions we want to merge.

On a personal note, I'm really sad your work was not been picked up in years. We are working on improving the triage and review process to be more predictable and reliable.

**Comment by Mathnerd314** [comment]
Well, I looked at this. As I recall this was part of an effort to ensure that the tests exercised all error paths in Nix. But although I use NixOS day to day, it's pretty stable, so I don't have much interest in rebasing this now.

**Comment by fricklerhandwerk** [comment]
Thank you very much for taking time!

**Comment by fricklerhandwerk** [comment]
@thufschmitt you removed the assignment, was that by accident? We wanted to pick this up and see what we can salvage, right?

**Comment by thufschmitt** [comment]
Nope, that was intended. This is a reasonably good entry-level thing to work on, and I don't plan on working on that in the foreseeable future. So there's no point in keeping myself assigned and morally prevent others from trying to give this a go.

**Comment by Ericson2314** [comment]
Rebased as #7954

**Pull request closed without merging**
