### PR TITLE
Restrict the permissions of the CI

### PR DESCRIPTION
**Pull request by thufschmitt**
Follow-up from https://github.com/NixOS/nix/pull/6746

/cc @naveensrinivasan

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
> Follow-up from #6746
> 
> /cc @naveensrinivasan

👍

**Review by naveensrinivasan — APPROVED** [review]
Thanks!

**Comment by thufschmitt** [comment]
The hydra_status job was broken because of a yaml error. Fixed it

**Comment by naveensrinivasan** [comment]
@thufschmitt  Something related to this. The actions aren't pinned by SHA which means someone can force a push tag which can be an attack vector. 

The downside of using an SHA is that it is hard to read for humans.  The SHA's are supported by dependabot.

**Pull request merged**
