### PR TITLE
error messages for issue 2238

### PR DESCRIPTION
**Pull request by bburdette**
Added a logError to build-remote to show the failure together with system info; added a check to the existing error site and reworded the error there.  Added a link to docs.

Here's the tail end of the result from 
```
sudo nix-store -j0 --realise --option substitute false --builders 'ssh://root@10.0.0.237 x86_64-linux - - - foo foo' /nix/store/crv8z01l69c3y0scq4cvdgyxrk2ldd1f-rustc-1.45.0.drv 
```

Selection_052

### CODE REVIEW

**Comment by bburdette** [comment]
#2238

**Comment by edolstra** [comment]
Thanks!

**Comment by B4dM4n** [comment]
This PR adds the following error to all `nix build`s for me, but the builds still succeed:
```shell
% nix build --impure --expr 'with import <nixpkgs> { }; runCommand "test" { } "touch $out"'
error: --- Remote build --- build-remote
Failed to find a machine for remote build!

required (system, features): (x86_64-linux, )
2 available machines:
(systems, maxjobs, supportedFeatures, mandatoryFeatures)
(x86_64-darwin, 2, , )
(x86_64-darwin, 2, , )
% realpath result
/nix/store/ml206rqibmzwffbbqssq879fj8jpivkb-test
```

**Comment by bburdette** [comment]
> This PR adds the following error to all `nix build`s for me, but the builds still succeed:

Yeah, its only in retrospect that we can say it was a critical error - when neither remote nor local build is possible.  Maybe this is better as an warning, or even just an Info level message.

**Comment by nh2** [comment]
> This PR adds the following error to all `nix build`s for me, but the builds still succeed:

You can use `--max-jobs 0` to force building on remotes only, see https://github.com/NixOS/nix/issues/1572#issuecomment-605385149 (with the exception of #3810).

**Comment by nh2** [comment]
I made a follow-up PR to add more details in #3927.

**Pull request merged**
