### PR TITLE
Don’t use `execvp` when we know the path

### LINKED ISSUE #9488: `nix run` invokes command with system `bash`?
**Describe the bug**

In some convoluted situations, `nix run` can end up executing a command with the wrong interpreter.

tl;dr
- BSD-derived kernels (like darwin) don't allow a script (with a shebang, as opposed to a binary) to be used as a shebang command interpreter.
- When this happens (as I understand it) the exec dispatcher (e.g., the shell) sometimes tries to recover. Bash recovers by simply interpreting the file itself.
- Under `nix run` on MacOS, this results in Apple's bundled Bash 3.2 being used as the interpreter (even if a newer Bash is on the `PATH`).

The context for this is that I have a wrapper script around bash that I use in shebang lines. It generally works well, but there was a case I ran into that really threw me.

Basically, BSD-derived kernels (like MacOS) don't allow scripts as shebang interpreters. They fail with `ENOEXEC` and then things get weird. ZSH (the default Mac shell) will try to run the script with the correct interpreter, completely hiding the kernel issue. Bash just says "I'll be the interpreter!" If you had a wrapper around Python or something, that would quickly lead to an error, no big deal. But my wrapper was around Bash, so _most of the time_ I couldn't tell that my wrapper was being ignored.

But with `nix run` it ends up using the system Bash, which is ancient, and so the script I was running (which expected to be run by a Nix-provided Bash 5.2 wrapped in a small script) would error out. This _only_ happens with `nix run` and it uses 3.2 even if the environment it was run in has a newer Bash.

**Steps To Reproduce**

I put up a branch of a project with some extra debugging info. It prints out the version of Bash being used. This is more obvious on a non-NixOS system (like a Mac in this case), where the system’s Bash is more likely to be a different version than the shebang line, but it should be reproducible enough anywhere.

```
$ nix run github:sellout/project-manager/nix-run-repro
/nix/store/bik3y0in6jghz2i8a81r8ncpz1i5bbac-project-manager/bin/project-manager
3.2.57(1)-release
/nix/store/h38nb91yhksxc6vqivs8nqcs1m9kqfhm-project-manager.bash: line 19: conditional binary operator expected
/nix/store/h38nb91yhksxc6vqivs8nqcs1m9kqfhm-project-manager.bash: line 19: syntax error near `NO_COLOR'
/nix/store/h38nb91yhksxc6vqivs8nqcs1m9kqfhm-project-manager.bash: line 19: `  if [[ ! -v NO_COLOR && -t 1 ]]; then'
/nix/store/bik3y0in6jghz2i8a81r8ncpz1i5bbac-project-manager/bin/project-manager: line 38: conditional binary operator expected
/nix/store/bik3y0in6jghz2i8a81r8ncpz1i5bbac-project-manager/bin/project-manager: line 38: syntax error near `VERBOSE'
/nix/store/bik3y0in6jghz2i8a81r8ncpz1i5bbac-project-manager/bin/project-manager: line 38: `  if [[ -v VERBOSE ]]; then'
```

Those errors after the Bash version are because MacOS’ included Bash (3.2) is too old to run the script. It doesn’t support `-v`. I don’t think I would have noticed otherwise.

Alternatively, running under `nix develop` still ignores the shebang, but the shell is a modern Bash, so it runs successfully:
```
$ nix develop github:sellout/project-manager/nix-run-repro

❄️$ project-manager
/nix/store/x1xxsh1gp6y389hyl40a0i74dkxiprl7-bash-5.2-p15/bin/bash
5.2.15(1)-release
…
```

**Expected behavior**

I expect it to either error, reporting the `ENOEXEC` failure, or to behave the same as under ZSH (or on Linux):
```
$ nix path-info github:sellout/project-manager/nix-run-repro
/nix/store/bik3y0in6jghz2i8a81r8ncpz1i5bbac-project-manager

$ /nix/store/bik3y0in6jghz2i8a81r8ncpz1i5bbac-project-manager/bin/project-manager
running strict-bash
strict-bash version: 5.2.15(1)-release
/nix/store/xhvxpfkb3xmicav5wdx9xfyiaw452mbl-bash-interactive-5.2-p15/bin/bash
5.2.15(1)-release
…
```
Running the script directly includes the debug output (`running strict-bash` `strict-bash version: 5.2.15(1)-release`) I added to the shebang interpreter to illustrate this issue. You can see how the `nix run` and `nix develop` versions don’t include that, because it never runs that interpreter. The last two lines are the debugging output I added to `project-manager` that shows it’s now using the version of Bash wrapped in the interpreter script, and not the old MacOS version.

I would also accept it just using a Nix-provided Bash. That just makes the incorrect behavior more invisible in my case, but at least it's a bit more consistent.

**`nix-env --version` output**
```
nix (Nix) 2.20.0pre20231128_a8fea5a
```

**Additional context**

This was hard for me to track down. I couldn't figure out why _some_ uses of the script worked while others didn’t, despite my efforts to make it reproducible. I expected `nix run` to be the _most_ hermetic way of running this (and in a way, it is – it uses the system Bash despite my best efforts), at least using a Nix-provided Bash.

Here is an issue on my own project: sellout/bash-strict-mode#10

and where I found the most helpful context: https://stackoverflow.com/a/9988275/5090651

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by sellout**
# Motivation

`execvp` (and other `exec*p*` functions) have an odd behavior when provided program can't be executed – they try to pass the program to `/bin/sh` to treat it as a POSIX shell script.

This is hard to avoid when you need to search `PATH`, but when the program is a path (like in `nix run`) we don’t need to search, which also avoids the `/bin/sh` fallback and instead reports a reasonable error.

Specifically, this crops up on MacOS when the program is a script with a shebang command interpreter – BSDs don’t support that. The previous behavior fell back to Bash 3.2 which is just reasonable enough to convince the user (like me) that they have done something wrong. This removes the fallback behavior, letting `nix` return a not-too-terrible error message instead.

There’s an example of the old & new behavior in https://github.com/NixOS/nix/issues/9488#issuecomment-1833239816.

# Context

Fixes #9488.

Conditionalize on whether or not the program can be a bare filename. This should probably be changed to avoid the `bool`, but first I’d like some confirmation that this is reasonable.

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Comment by sellout** [comment]
Hrmm, the check that’s failing here is passing for me locally. Granted, GH is running macOS 12 and I’m running macOS 14, but I wonder if it‘s possibly intermittent, as it’s not obvious to me how that failure is related to this change (but as a non-collaborator, I can’t trigger a re-run of the job).

**Comment by Ericson2314** [comment]
Yes that is a known spurious error.

**Comment by sellout** [comment]
Tangentially related, I don’t see how https://github.com/NixOS/nix/blob/3bebaefcd0c5d650f7edcd39f397bb45c4382f41/src/nix/run.cc#L53 can work. `getSelfExe` should return an absolute path (if anything), but falling back to `"nix"` will never actually be able to execute, will it? It either needs to use `execvp` or just not use `value_or`, no?

**Review by thufschmitt — CHANGES_REQUESTED** [review]
The overall change makes a lot of sense, thanks!

I wonder why you still call to `execvp` in some cases. Afaik, all the calls to `runProgramInStore` here are necessarily called with a full path. Or am I missing something?

**Comment by thufschmitt** [comment]
> Tangentially related, I don’t see how
> 
> https://github.com/NixOS/nix/blob/3bebaefcd0c5d650f7edcd39f397bb45c4382f41/src/nix/run.cc#L53
> can work. `getSelfExe` should return an absolute path (if anything), but falling back to `"nix"` will never actually be able to execute, will it? It either needs to use `execvp` or just not use `value_or`, no?

I guess it indeed doesn't work if `getSelfExe` doesn't succeed or doesn't return an absolute path. So yes, changing that to `execvp` would make sense

**Comment by roberth** [comment]
> This is hard to avoid when you need to search `PATH`,

Doesn't seem hard.
If we perform our own `PATH` lookup, we can avoid `/bin/sh` entirely, fixing the behavior for both cases, and we keep it simple.

**Review by thufschmitt — COMMENTED** [review]
@sellout oh righ, I had forgotten that we were using `bash` for these.

It's all great then! I've just pushed a small change to use an enum rather than a boolean for clarity, and I've set it on automerge.

Thanks!

**Review by thufschmitt — APPROVED** [review]

**Comment by thufschmitt** [comment]
> If we perform our own `PATH` lookup, we can avoid `/bin/sh` entirely, fixing the behavior for both cases, and we keep it simple.

Is it guaranteed that “just” iterating over `$PATH` will do the right thing, or are there some subtleties to think about here?

**Comment by roberth** [comment]
The only subtlety I'm aware of is `PATH=/foo:` bar has an empty item, equivalent to `PATH=/foo:.`, but that actually means it's ok to be naive about this part of the logic. Maybe the surprising bit is that an absolute path is not guaranteed by `PATH`.

**Comment by sellout** [comment]
@thufschmitt Thanks!

**Comment by sellout** [comment]
> If we perform our own `PATH` lookup, we can avoid `/bin/sh` entirely, fixing the behavior for both cases, and we keep it simple.

@roberth Yeah, I just worry about messing up some POSIX edge cases, but I agree having like a `nix_execvp` that does `PATH` lookup but avoids catching `ENOEXEC` would be worthwhile, and would then replace both `execvp` and `execv` throughout the project.

**Comment by roberth** [comment]
Looks like we're already parsing `PATH` anyway. I've created https://github.com/NixOS/nix/issues/9515 for this.

**Pull request merged**
