### PR TITLE
Explicitly set default branch name for git to suppress "git hint"

### PR DESCRIPTION
**Pull request by oxalica**
This fixes the "git hint" printed when running `nix flake update` to fetch a git flake input.
```
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint:   git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint:   git branch -m <name>
```

### CODE REVIEW

**Comment by oxalica** [comment]
Renamed to `__nix_dummy_branch` since the initial branch of our bare repo actually does not matter.
The reason why using `-c init.defaultBranch=<name>` instead of `--initial-branch=<name>` is to make it compatible with old version of  git.

**Review by Artturin — APPROVED** [review]

**Comment by roberth** [comment]
> Renamed to `__nix_dummy_branch` since the initial branch of our bare repo actually does not matter.
> The reason why using `-c init.defaultBranch=<name>` instead of `--initial-branch=<name>` is to make it compatible with old version of git.

Could you add something like this as an inline comment?

**Comment by oxalica** [comment]
Comments are added. Also rebased.

**Review by roberth — APPROVED** [review]

**Comment by edolstra** [comment]
Thanks!

**Pull request merged**
