### PR TITLE
straightforward implementation of 'nix copy'

### LINKED ISSUE #1639: nix copy doesn't work for drv files
With nix-copy-closure it's possible to build a drv on a remote machine without using the build hook. This is useful to avoid substituting dependencies over a slow connection.

```
$ nix copy --to ssh://desktop /path/to/build.drv
$ ssh desktop -- nix build /path/to/build.drv
cannot build missing derivation '/path/to/build.drv'
```

### PR DESCRIPTION
**Pull request by volth**
fixes #1639

### CODE REVIEW

**Comment by shlevy** [comment]
I think sign-paths has the same problem

**Comment by volth** [comment]
```nix copy``` also lacks ```--include-outputs``` feature of ```nix-copy-closure```

**Comment by volth** [comment]
And... it there any meaningful use case for ```nix copy``` without ```--recursive``` ?

**Comment by shlevy** [comment]
IMO recursive should be the default, but if you know that the rest of the closure is already there it can be more efficient to avoid several checks for the validity of the inputs.

**Comment by volth** [comment]
```--recursive``` leaded here from ```StorePathsCommand```, ```nix-copy-closure``` has it always on.

> IMO recursive should be the default, but if you know that the rest of the closure is already there it can be more efficient to avoid several checks for the validity of the inputs.

Well, if the assumption were false, and a derivation which should be copied with ```--recursive``` were copied without, would it result in dangling references in the target nix store?

**Comment by shlevy** [comment]
No, it would just fail.

**Comment by shlevy** [comment]
Anyway, we can add it later if need be.

**Comment by edolstra** [comment]
:-1: since this makes the `nix copy` interface inconsistent with other `nix` commands. For instance, you can't do something like `nix copy nixpkgs.hello` anymore.

**Comment by volth** [comment]
> For instance, you can't do something like ```nix copy nixpkgs.hello``` anymore.

Never tried to do something like this.

I am worrying about impossibility to do ```nix copy /nix/store/something.drv```.
It results with success but copies nothing (or only .patch and .sh files)

**Comment by edolstra** [comment]
I've pushed 85530bcc0b4c61499f90fa6125c19beeb0f4485e which allows copying .drv files while keeping `nix copy` consistent with other `nix` commands.

**Pull request closed without merging**
